objects/Account_Contact_Owner_Sync__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration for Account/Contact ownership synching</description>
    <fields>
        <fullName>Account_Record_Type_ID__c</fullName>
        <inlineHelpText>Must be 18 character unique record type ID</inlineHelpText>
        <label>Account Record Type ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Contact Owner Sync</label>
</CustomObject>

objects/Address_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Address objects are used to allow storing an unlimited number of current and historical addresses for Leads, Business Accounts and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>JH Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Phone_SFDC2__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SFDC2__c</fullName>
        <formula>RecordType.Name == &apos;Business SFDC2&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC2</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>WLD</fullName>
        <active>true</active>
        <description>Used by WLD</description>
        <label>WLD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Email  objects are used to allow storing an unlimited number of current and historical email addresses for Leads and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Email_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <description>Type of email. Will not necessarily match Parent Record Type, e.g. an employee contact with a Person Account could have an Email with Parent Record Type = &apos;Personal&apos; and Email Type = &apos;Primary Business&apos;</description>
        <label>Email Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Personal</fullName>
                </value>
                <value>
                    <fullName>Primary Business</fullName>
                </value>
                <value>
                    <fullName>Other Personal</fullName>
                    <default>true</default>
                    <label>Other Personal</label>
                </value>
                <value>
                    <fullName>Other Business</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>JH Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>EML-{0000}</displayFormat>
        <label>Email Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Escheat</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>New Today</fullName>
                </value>
                <value>
                    <fullName>Pending Close</fullName>
                </value>
                <value>
                    <fullName>Restricted</fullName>
                </value>
                <value>
                    <fullName>No Post</fullName>
                </value>
                <value>
                    <fullName>Charged Off</fullName>
                </value>
                <value>
                    <fullName>No Credits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account_Contact_Link_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Creates a many-to-many junction between Contacts or Person Accounts and Financial Accounts</description>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Financial_Account__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Contact Link</label>
    <nameField>
        <displayFormat>FACL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Contact Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contact Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_SFDC2__c.object
<CustomObject>
    <description>Used to capture customer financial account information for SFDC 2.0 integration</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>CD</fullName>
        <active>true</active>
        <label>CD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Phone_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phone_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Neustar_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by onclick javascript button which signals to the Phone Number trigger that a manual Phone Attr callout to Neustar has been submitted</description>
        <label>Neustar Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>Fast Busy</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Ring No Answer</fullName>
                </value>
                <value>
                    <fullName>Spoke to Customer</fullName>
                </value>
                <value>
                    <fullName>VM Confirmed</fullName>
                </value>
                <value>
                    <fullName>VM Full</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>PH-{00}</displayFormat>
        <label>Phone Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Phone_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Phone objects are used to allow storing an unlimited number of current and historical phone numbers for Leads, Business Accounts and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <displayFormat>PHN-{0000}</displayFormat>
        <label>Phone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Webservice_Callout__c.object
<CustomObject>
    <description>Used to log webservice callouts for custom functionality. Included:
- LexisNexis Account updates for Specialty Finance</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to capture Phone Number record that triggered Neustar Phone Attr callout</description>
        <label>Phone Number</label>
        <referenceTo>Phone_Number__c</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Webservice Callout</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Callout Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountTriggerHandler_Test.cls
@isTest
private class AccountTriggerHandler_Test {

  /**
  * Tests the reassignContactOwners method that is triggered in the afterUpdate for Accounts
  */
  @isTest
  static void testReassignContactOwners() {
    TriggerValidator.setIsTest();
    //create 2 test users--profiles don't matter at this time
    User[] testUsers = TestDataFactory.createTestUsers(new Set<String>{'System Administrator','Standard User'});
    
    //create a test custom setting for a specific account record type
    RecordType[] rt = [select Id from RecordType where SobjectType = 'Account' and IsActive = true and IsPersonType = false limit 2];
    Account_Contact_Owner_Sync__c cs = new Account_Contact_Owner_Sync__c(Name='Test',Account_Record_Type_ID__c=rt[1].Id);
    insert cs;
    
    //create a test business account and set the owner to the first test user
    Account a1 = TestDataFactory.createTestBusinessAccount();
    a1.OwnerId = testUsers.get(0).Id;
    a1.RecordTypeId = rt[0].Id;
    //create a test business account and set the owner to the second test user, and set record type to the test synch record type
    Account a2 = TestDataFactory.createTestBusinessAccount();
    a2.OwnerId = testUsers.get(1).Id;
    a2.RecordTypeId = rt[1].Id;
    Account[] accts = new Account[]{a1,a2};
    insert accts;   
    
    //create a test contact for the first account and set the owner to the first test user
    Contact c1 = TestDataFactory.createTestContact(accts[0]);
    c1.OwnerId = testUsers[0].Id;
    //create a test contact for the second account and set the owner to the second test user
    Contact c2 = TestDataFactory.createTestContact(accts[1]);
    c2.OwnerId = testUsers[1].Id;
    Contact[] cts = new Contact[]{c1,c2};
    insert cts;
    
    //switch ownership for the two test accounts
    Test.startTest();
    accts[0].OwnerId = testUsers[1].Id;
    accts[1].OwnerId = testUsers[0].Id;
    update accts;
    Test.stopTest();
    
    //verify appropriate contact ownership changes
    accts = [select OwnerId from Account where Id in :accts];
    for(Contact c : [select AccountId, OwnerId from Contact where AccountId in :accts]) {
        if(c.AccountId == accts[0].Id) {
            //the first account contact should not have an ownership change
            //System.assertNotEquals(accts[0].OwnerId, c.OwnerId, 'Non-synching Account inappropriately had Contact ownership change');
        } else if(c.AccountId == accts[1].Id) {
            //the second account contact should have an ownership change
            System.assertEquals(accts[1].OwnerId, c.OwnerId, 'Synching Account did not have Contact ownership change');
        }
    }
  }

  /**
  * Tests the checkSpecFinOwnerChange method that is triggered beforeUpdate for Accounts
  */
  @isTest
  static void testCheckSpecFinOwnerChange() {
    TriggerValidator.setIsTest();
    //create a new Account record
    Account acc = new Account(Name='Test');
    
    Test.startTest();
    insert acc;
    acc = [Select Id, Name, Send_Owner_Change_Notification__c from Account where Id = :acc.Id];
    System.assertEquals(false, acc.Send_Owner_Change_Notification__c, 'Send Owner Change Notification should not be set to true on account creation');
    
    //establish test users based on the flagged profiles that trigger the field update
    List<User> userList = TestDataFactory.createTestUsers(AccountTriggerHandler.flaggedSpecFinProfiles);
    
    //test 1: as admin, change owner to one of the flagged profile users; this should not cause a field update
    acc.OwnerId = userList.get(0).Id;
    update acc;
    acc = [Select Id, Name, Send_Owner_Change_Notification__c from Account where Id = :acc.Id];
    System.assertEquals(false, acc.Send_Owner_Change_Notification__c, 'Send Owner Change Notification should not be set to true when modified by non-flagged profiles');
    
    //test 2: run as a flagged profile and modify owner; this should cause a field update
    System.runAs(userList.get(0)) {
        acc.OwnerId = userList.get(1).Id;
        update acc;
    }
    acc = [Select Id, Name, Send_Owner_Change_Notification__c from Account where Id = :acc.Id];
    System.assertEquals(true, acc.Send_Owner_Change_Notification__c, 'Send Owner Change Notification should be set to true when modified by flagged profiles');
    
    Test.stopTest();
  }
  
  /**
  * Tests the capturePriorOwner method that is triggered beforeUpdate for Accounts
  */
  @isTest
  static void testCapturePriorOwner() {
    TriggerValidator.setIsTest();
    //create a new Account record
    Account acc = new Account(Name='Test');
    insert acc;
    
    acc = [Select Id, OwnerId, Prior_Owner__c From Account Where Id = :acc.Id];
    System.assertNotEquals(null, acc.OwnerId, 'Test account owner is null');
    System.assertEquals(null, acc.Prior_Owner__c, 'Test account prior owner is not null');
    
    //establish test users
    List<User> userList = TestDataFactory.createTestUsers(AccountTriggerHandler.flaggedSpecFinProfiles);
    
    Id preTestOwnerId = acc.OwnerId;
    Test.startTest();
    acc.OwnerId = userList.get(0).Id;
    update acc;
    Test.stopTest();
    
    acc = [Select Id, OwnerId, Prior_Owner__c From Account Where Id = :acc.Id];
    
    System.assertEquals(userList.get(0).Id, acc.OwnerId, 'Owner was not updated');
    System.assertEquals(preTestOwnerId, acc.Prior_Owner__c, 'Prior Owner was not updated');
  }
  
  /** Tests the updateLexisNexisCalloutStatus method for inserts */
  @isTest
  static void testUpdateLexisNexisCalloutStatus_Insert() {
    TriggerValidator.setIsTest();
    List<Id> rtIdList = new List<Id>(); 
    rtIdList.addAll(AccountTriggerHandler.lxnxSpecFinRTIdSet);
    Id sfRTid = rtIdList[0];
    
    Account sfAcc = TestDataFactory.createTestPersonAccount();
    sfAcc.RecordTypeId = sfRTid;
    sfAcc.Social_Security_Number_Person__c = '999-99-9999';
    sfAcc.Research_Status_Person__c = 'New Unresearched';
    
    Account nonSfAcc = TestDataFactory.createTestPersonAccount();
    nonSfAcc.Social_Security_Number_Person__c = '999-99-9999';
    nonSfAcc.Research_Status_Person__c = 'New Researched';
    
    Account[] accts = new List<Account>{sfAcc, nonSfAcc};
    
    try {
        Test.startTest();
        insert accts;
        Test.stopTest();
    } catch (DMLException de) {Test.stopTest();}
    
    Id nonSfAccId = accts[1].Id;
    for(Account acc : [SELECT Id, SF_LexisNexis_Callout_Status__c FROM Account WHERE Id in :accts]) {
        if(acc.Id == accts[0].Id) {
            System.assertEquals('Queued', acc.SF_LexisNexis_Callout_Status__c);
        } else if (acc.Id == accts[1].Id) {
            System.assertNotEquals('Queued', acc.SF_LexisNexis_Callout_Status__c);
        }
    }
    
  }
  
  /** Tests the updateLexisNexisCalloutStatus method for updates */
  @isTest
  static void testUpdateLexisNexisCalloutStatus_Update() {
    TriggerValidator.setIsTest();
    List<Id> rtIdList = new List<Id>(); 
    rtIdList.addAll(AccountTriggerHandler.lxnxSpecFinRTIdSet);
    Id sfRTid = rtIdList[0];
    
    Account nonSfAcc = TestDataFactory.createTestPersonAccount();
    nonSfAcc.RecordTypeId = sfRTId;
    nonSfAcc.Social_Security_Number_Person__c = '999-99-9999';
    nonSfAcc.Research_Status_Person__c = 'Hard to Find';
    
    insert nonSfAcc;
    
    nonSfAcc.Research_Status_Person__c = 'Needs Research';
    
    try {
        Test.startTest();
        update nonSfAcc;
        Test.stopTest();
    } catch (DMLException de) {Test.stopTest();}
    
    for(Account acc : [SELECT Id, SF_LexisNexis_Callout_Status__c FROM Account WHERE Id = :nonSfAcc.Id]) {
        System.assertEquals('Queued', acc.SF_LexisNexis_Callout_Status__c);
    }
  }
  
  /** Tests the triggerUpdateSFNeustarCallout method for updates */
  @isTest
  static void testTriggerUpdateSFNeustarCallout() {
    TriggerValidator.setIsTest();
    List<Id> rtIdList = new List<Id>(); 
    rtIdList.addAll(AccountTriggerHandler.neustarSpecFinRTIdSet);
    Id sfRTid = rtIdList[0];
    
    Account sfAcc = TestDataFactory.createTestPersonAccount();
    sfAcc.RecordTypeId = sfRTId;
    sfAcc.OwnerId = AccountTriggerHandler.SF_OUTBOUNDOWNERID;
    sfAcc.Research_Status_Person__c = '';
    
    insert sfAcc;
    
    Phone_Number__c phone = new Phone_Number__c();
    phone.Account_Name__c = sfAcc.Id;
    phone.Phone_Number__c = '5555551212';
    insert phone;
    
    sfAcc.Research_Status_Person__c = 'New Researched';
    
    try {
        Test.startTest();
        update sfAcc;
        Test.stopTest();
    } catch (DMLException de) {Test.stopTest();}
    
    Webservice_Callout__c[] callout = [SELECT ID FROM Webservice_Callout__c WHERE Account__c = :sfAcc.Id AND Job_Name__c = 'NeustarQueueableJob'];
    sfAcc = [SELECT Id, Owner.Name, Research_Status_Person__c, RecordType.Name FROM Account WHERE Id = :sfAcc.Id];
    System.debug(sfAcc);
    System.assert(callout.size() > 0);
  }
  
  /** Tests the handleManualNeustarTrigger method for updates */
  @isTest
  static void testHandleManualNeustarTrigger() {
    TriggerValidator.setIsTest();
    List<Id> rtIdList = new List<Id>(); 
    rtIdList.addAll(AccountTriggerHandler.neustarSpecFinRTIdSet);
    Id sfRTid = rtIdList[0];
    
    Account sfAcc = TestDataFactory.createTestPersonAccount();
    sfAcc.RecordTypeId = sfRTId;
    sfAcc.Research_Status_Person__c = '';
    
    insert sfAcc;
    
    Phone_Number__c phone = new Phone_Number__c();
    phone.Account_Name__c = sfAcc.Id;
    phone.Phone_Number__c = '5555551212';
    insert phone;
    
    sfAcc.Neustar_Trigger__c = true;
    
    try {
        Test.startTest();
        update sfAcc;
        Test.stopTest();
    } catch (DMLException de) {Test.stopTest();}
    finally {}
    
    Webservice_Callout__c[] callout = [SELECT ID FROM Webservice_Callout__c WHERE Account__c = :sfAcc.Id AND Job_Name__c = 'NeustarQueueableJob'];
    sfAcc = [SELECT Id, Owner.Name, Research_Status_Person__c, RecordType.Name FROM Account WHERE Id = :sfAcc.Id];
    System.debug(sfAcc);
    System.assert(callout.size() > 0);
  }
  
  /** 
  * SFDC 2.0: Tests the restriction of editing Accounts if the user is not an open Opp owner
  * or a System Admin
  */
  @isTest
  static void testRestrictSFDC2AccountUpdates() {
  	User[] testUsers = TestDataFactory.createTestUsers(new Set<String>{'Enterprise User', 'API Service Account'});
  	User runUser;
  	User apiUser;
  	for(User u : [SELECT LastName FROM User WHERE Id = :testUsers]) {
  		if(u.LastName.contains('Enterprise User')) {
  			runUser = u;
  		} else if (u.LastName.contains('API Service Account')) {
  			apiUser = u;
  		}
  	}
  	System.debug(runUser);
  	System.assertNotEquals(null, runUser, 'Unable to create test Enterprise User');
  	System.assertNotEquals(null, apiUser, 'Unable to create test API User');
  	Account editAccount = new Account();
  	editAccount.SFDC2__c = true;
  	editAccount.Name = 'Test1';
  	editAccount.OwnerId = apiUser.Id;
  	Account lock1Account = new Account();
  	lock1Account.SFDC2__c = true;
  	lock1Account.Name = 'Test2';
  	lock1Account.OwnerId = apiUser.Id;
  	Account lock2Account = new Account();
  	lock2Account.SFDC2__c = true;
  	lock2Account.Name = 'Test3';
  	lock2Account.OwnerId = apiUser.Id;
  	Account[] accts = new List<Account>{editAccount, lock1Account, lock2Account};
  	insert accts;
  	
  	RecordType[] rt = [SELECT Id FROM RecordType WHERE SObjectType='Opportunity' AND IsActive = true AND Description = 'SFDC2' limit 1];
  	System.assert(rt.size() > 0, 'Unable to locate SFDC2 Opportunity record type');
	
  	Opportunity openOpp = new Opportunity();
  	openOpp.Name = 'Test1';
  	openOpp.RecordTypeId = rt[0].Id;
  	openOpp.StageName = '1 - New';
  	openOpp.CloseDate = Date.today();
  	openOpp.AccountId = accts[1].Id;
  	openOpp.OwnerId = runUser.Id;
  	Opportunity closed1Opp = new Opportunity();
  	closed1Opp.Name = 'Test2';
  	closed1Opp.RecordTypeId = rt[0].Id;
  	closed1Opp.StageName = '0 - Closed - Lost';
  	closed1Opp.CloseDate = Date.today();
  	closed1Opp.AccountId = accts[1].Id;
  	closed1Opp.OwnerId = runUser.Id;
  	Opportunity closed2Opp = new Opportunity();
  	closed2Opp.Name = 'Test3';
  	closed2Opp.RecordTypeId = rt[0].Id;
  	closed2Opp.StageName = '1 - New';
  	closed2Opp.CloseDate = Date.today();
  	closed2Opp.AccountId = accts[2].Id;
  	closed2Opp.OwnerId = apiUser.Id;
  	Opportunity[] opps = new List<Opportunity>{openOpp, closed1Opp, closed2Opp};
  	insert opps;
  	
  	Test.startTest();
  	System.runAs(runUser){
  		accts[0].Name = 'TestGood';
  		accts[1].Name = 'TestBad';
  		accts[2].Name = 'TestBad';
  		Database.SaveResult[] srList = Database.update(accts, false);
  		for(Database.SaveResult sr : srList) {
  			if(sr.getId() == accts[0].Id) {
  				System.assert(sr.isSuccess(), 'Did not update Account that should have been editable');
  			} else {
  				System.assert(!sr.isSuccess(), 'Wrongly updated a locked Account');
  			}
  		}
  	}
  	Test.stopTest();
  }
  
  /** Tests creation of custom Phone objects on Account phone field modification */
  @isTest
  static void testUpdatePhoneListSfdc2() {
  	TriggerValidator.setIsTest();

	List<Account> accts1 = new List<Account>();
	List<Account> accts2 = new List<Account>();
  	
	RecordType acctRt = [select Id from RecordType where SObjectType = 'Account' and DeveloperName = 'Business_Consumer_Person_Account' limit 1];
    RecordType phoneRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Phone_SFDC2__c' AND Name = 'Account Phone'];

  	System.debug('Inserting two sets of 20 accounts to test Phone object creation.');
  	
  	// Create set of test person accounts with phone number fields populated
  	for (Integer i=0; i<40; i++) {
  		String uniqueLastName = 'Person' + i;
	  	Account acct = new Account(FirstName = 'Test', 
	  							   LastName = uniqueLastName, 
	  							   SFDC2__c = true,
	  							   Phone = '1234567890',
	  							   PersonMobilePhone = '2345678901',
	  							   PersonHomePhone = '6789012345',
	  							   PersonOtherPhone = '3456789012',
	  							   Fax = '4567890123',
	  							   Business_Phone_SFDC2__pc = '5678901234',
	  							   RecordTypeId = acctRt.Id);
	  	if (i<20) {
	  		accts1.add(acct);
	  	} else {
	  		accts2.add(acct);
	  	}
  	}
  	insert accts1;
  	insert accts2;
  	
  	for (Account acct: accts1) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 1.');
  	}
  	for (Account acct: accts2) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 2.');
  	}

  	// Add a set of Phone objects to the first account in the list
  	List<Phone_SFDC2__c> phones = new List<Phone_SFDC2__c>();
  	for (Integer i=0; i<6; i++) {
  		Phone_SFDC2__c phone = new Phone_SFDC2__c(Account__c = accts1.get(0).Id, RecordTypeId = phoneRecordType.Id);
  		if (i==0) phone.Phone__c = '7654321098';
  		if (i==1) phone.Phone__c = '1098765432';
  		if (i==2) phone.Phone__c = '2109876543';
  		if (i==3) phone.Phone__c = '3210987654';
  		if (i==4) phone.Phone__c = '4321098765';
  		if (i==5) phone.Phone__c = '5432109876';
		phones.add(phone);
  	}
  	insert phones;
  	
  	// Modify each phone field to hold a new value in the first 10 accounts.
  	// (For the first account, these numbers will already exist as Phone objects.)
  	// After the update, these accounts should have five Phone objects corresponding to
  	//   the original phone field values.
  	for (Integer i=0; i<20; i++) {  	
	  	accts1.get(i).Phone = '7654321098';
	  	accts1.get(i).PersonMobilePhone = '1098765432';
	  	accts1.get(i).PersonHomePhone = '5432109876';
	  	accts1.get(i).PersonOtherPhone = '2109876543';
	  	accts1.get(i).Fax = '3210987654';
	  	accts1.get(i).Business_Phone_SFDC2__pc = '4321098765';
  	}

  	// Modify each phone field to hold a value previously held by another phone field in the remaining accounts.
  	// After the update these accounts should have no Phone objects.
  	for (Integer i=0; i<20; i++) {  	
	  	accts2.get(i).Phone = '6789012345';
	  	accts2.get(i).PersonMobilePhone = '1234567890';
	  	accts2.get(i).PersonHomePhone = '5678901234';
	  	accts2.get(i).PersonOtherPhone = '2345678901';
	  	accts2.get(i).Fax = '3456789012';
	  	accts2.get(i).Business_Phone_SFDC2__pc = '4567890123';
  	}
  	
  	Test.startTest();
  	update accts1;
  	update accts2;
  	Test.stopTest();
  	
  	accts1 = [SELECT Id, Phone, PersonMobilePhone, PersonHomePhone, PersonOtherPhone, Fax, Business_Phone_SFDC2__pc, 
  			(SELECT Phone__c FROM Phones__r WHERE Account__c IN :accts1 )
  			FROM Account WHERE Id IN :accts1];

  	accts2 = [SELECT Id, Phone, PersonMobilePhone, PersonHomePhone, PersonOtherPhone, Fax, Business_Phone_SFDC2__pc, 
  			(SELECT Phone__c FROM Phones__r WHERE Account__c IN :accts2)
  			FROM Account WHERE Id IN :accts2];

	// Assert that the correct number of Phone objects exist for each Account.
	for (Integer i=0; i<20; i++) {
		System.assertEquals(6, accts1.get(i).Phones__r.size(), 'Incorrect number of Phone objects for first account set.');
		System.assertEquals(0, accts2.get(i).Phones__r.size(), 'Incorrect number of Phone objects for second account set.');
	}
  	
  }
  
  /** Tests creation of custom Email objects on Account email field modification */
  @isTest
  static void testUpdateEmailListSfdc2() {
  	TriggerValidator.setIsTest();

    RecordType personAccountRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Business/Consumer Person Account'];
    RecordType emailRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Email_SFDC2__c' AND Name = 'Account Email'];

	List<Account> accts1 = new List<Account>();
	List<Account> accts2 = new List<Account>();
  	
  	System.debug('Inserting two sets of 20 accounts to test Email object creation.');
  	
  	// Create set of test person accounts with email address fields populated
  	for (Integer i=0; i<40; i++) {
  		String uniqueLastName = 'Person' + i;
	  	Account acct = new Account(FirstName = 'Test', 
	  							   LastName = uniqueLastName, 
	  							   SFDC2__c = true,
	  							   PersonEmail = 'test1@test.com',
	  							   Business_Email_SFDC2__pc = 'test2@test.com',
	  							   RecordTypeId = personAccountRecordType.Id);
	  	if (i<20) {
	  		accts1.add(acct);
	  	} else {
	  		accts2.add(acct);
	  	}
  	}
  	insert accts1;
  	insert accts2;
  	
  	for (Account acct: accts1) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 1.');
  	}
  	for (Account acct: accts2) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 2.');
  	}

  	// Add a set of Email objects to the first account in the list
  	List<Email_SFDC2__c> emails = new List<Email_SFDC2__c>();
  	for (Integer i=0; i<2; i++) {
  		Email_SFDC2__c email = new Email_SFDC2__c(Account__c = accts1.get(0).Id, RecordTypeId = emailRecordType.Id);
  		if (i==0) email.Email__c = 'test3@test.com';
  		if (i==1) email.Email__c = 'test4@test.com';
  		email.Email_Type__c = 'Other Personal';
		emails.add(email);
  	}
  	insert emails;
  	
  	// Modify each email field to hold a new value in the first 10 accounts.
  	// (For the first account, these emails will already exist as Email objects.)
  	// After the update, these accounts should have two Email objects corresponding to
  	//   the original email field values.
  	for (Integer i=0; i<20; i++) {  	
	  	accts1.get(i).PersonEmail = 'test3@test.com';
	  	accts1.get(i).Business_Email_SFDC2__pc= 'test4@test.com';
  	}

  	// Modify each email field to hold a value previously held by another email field in the remaining accounts.
  	// After the update these accounts should have no Email objects.
  	for (Integer i=0; i<20; i++) {  	
	  	accts2.get(i).PersonEmail = 'test2@test.com';
	  	accts2.get(i).Business_Email_SFDC2__pc= 'test1@test.com';
  	}
  	
  	Test.startTest();
  	update accts1;
  	update accts2;
  	Test.stopTest();
  	
  	accts1 = [SELECT Id, PersonEmail, Business_Email_SFDC2__pc, 
  			(SELECT Email__c FROM Email_Addresses__r WHERE Account__c IN :accts1 )
  			FROM Account WHERE Id IN :accts1];

  	accts2 = [SELECT Id, PersonEmail, Business_Email_SFDC2__pc, 
  			(SELECT Email__c FROM Email_Addresses__r WHERE Account__c IN :accts2)
  			FROM Account WHERE Id IN :accts2];

	// Assert that the correct number of Email objects exist for each Account.
	for (Integer i=0; i<20; i++) {
		System.assertEquals(2, accts1.get(i).Email_Addresses__r.size(), 'Incorrect number of Email objects for first account set.');
		System.assertEquals(0, accts2.get(i).Email_Addresses__r.size(), 'Incorrect number of Email objects for second account set.');
	}
  	
  }

  /** Tests creation of custom Address objects on Account address field modification */
  @isTest
  static void testUpdateAddressListSfdc2() {
  	TriggerValidator.setIsTest();

	List<Account> accts1 = new List<Account>();
	List<Account> accts2 = new List<Account>();
  	
  	System.debug('Inserting two sets of 20 accounts to test Address object creation.');
  	
    RecordType personAccountRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Business/Consumer Person Account'];
    RecordType addressRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Address_SFDC2__c' AND Name = 'Account Address'];
  	
  	// Create set of test person accounts with address fields populated
  	for (Integer i=0; i<40; i++) {
  		String uniqueLastName = 'Person' + i;
	  	Account acct = new Account(RecordTypeId = personAccountRecordType.Id,
	  							   FirstName = 'Test', 
	  							   LastName = uniqueLastName, 
	  							   SFDC2__c = true,
	  							   PersonMailingStreet = '123 Main Street', 
	  							   PersonMailingCity = 'Springfield', 
	  							   PersonMailingCountry = 'USA', 
	  							   PersonMailingState = 'MA', 
	  							   PersonMailingPostalCode = '12345',
  								   BillingStreet = '456 Main Street', 
  								   BillingCity = 'Providence', 
  								   BillingCountry = 'USA', 
  								   BillingState = 'RI', 
  								   BillingPostalCode = '67890');
	  	if (i<20) {
	  		accts1.add(acct);
	  	} else {
	  		accts2.add(acct);
	  	}
  	}
  	insert accts1;
  	insert accts2;
  	
  	for (Account acct: accts1) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 1.');
  	}
  	for (Account acct: accts2) {
  		System.assertEquals(true, acct.SFDC2__c, 'Test Account lost SFDC2 status in set 2.');
  	}
  	
  	// Add a set of Address objects to the first account in the list
  	List<Address_SFDC2__c> addresses = new List<Address_SFDC2__c>();
  	for (Integer i=0; i<2; i++) {
  		Address_SFDC2__c address = new Address_SFDC2__c(Account__c = accts1.get(0).Id, RecordTypeId = addressRecordType.Id);
  		if (i==0) {
  			address.Address_Type__c = 'Other';
  			address.Street__c = '789 Main Street';
  			address.City__c = 'Hartford';
  			address.Country__c = 'USA';
  			address.State__c = 'CT';
  			address.Postal_Code__c = '54321';
  		}
  		if (i==1) {
  			address.Address_Type__c = 'Other';
  			address.Street__c = '012 Main Street';
  			address.City__c = 'Montpelier';
  			address.Country__c = 'USA';
  			address.State__c = 'VT';
  			address.Postal_Code__c = '09876';
  		}
  		addresses.add(address);
  	}
  	insert addresses;
  	
  	// Modify each set of address fields to hold new values in the first 10 accounts.
  	// (For the first account, these addresses will already exist as Address objects.)
  	// After the update, these accounts should have two Address objects corresponding to
  	//   the original address field values.
  	for (Integer i=0; i<20; i++) {  	
	  	accts1.get(i).PersonMailingStreet = '789 Main Street';
  		accts1.get(i).PersonMailingCity = 'Hartford';
  		accts1.get(i).PersonMailingCountry = 'USA';
  		accts1.get(i).PersonMailingState = 'CT';
  		accts1.get(i).PersonMailingPostalCode = '54321';
	  	accts1.get(i).BillingStreet = '012 Main Street';
  		accts1.get(i).BillingCity = 'Montpelier';
  		accts1.get(i).BillingCountry = 'USA';
  		accts1.get(i).BillingState = 'VT';
  		accts1.get(i).BillingPostalCode = '09876';
  	}

  	// Modify each address field to hold a value previously held by another address field in the remaining accounts.
  	// After the update these accounts should have no Address objects.
  	for (Integer i=0; i<20; i++) {  	
	  	accts2.get(i).PersonMailingStreet = '456 Main Street';
  		accts2.get(i).PersonMailingCity = 'Providence';
  		accts2.get(i).PersonMailingCountry = 'USA';
  		accts2.get(i).PersonMailingState = 'RI';
  		accts2.get(i).PersonMailingPostalCode = '67890';
	  	accts2.get(i).BillingStreet = '123 Main Street';
  		accts2.get(i).BillingCity = 'Springfield';
  		accts2.get(i).BillingCountry = 'USA';
  		accts2.get(i).BillingState = 'MA';
  		accts2.get(i).BillingPostalCode = '12345';
  	}
  	
  	Test.startTest();
  	update accts1;
  	update accts2;
  	Test.stopTest();
  	
  	accts1 = [SELECT Id, PersonMailingStreet, PersonMailingCity, PersonMailingCountry, PersonMailingState, PersonMailingPostalCode,
  					 BillingStreet, BillingCity, BillingCountry, BillingState, BillingPostalCode, 
  			(SELECT Street__c, City__c, Country__c, State__c, Postal_Code__c FROM Addresses__r WHERE Account__c IN :accts1 )
  			FROM Account WHERE Id IN :accts1];

  	accts2 = [SELECT Id, PersonMailingStreet, PersonMailingCity, PersonMailingCountry, PersonMailingState, PersonMailingPostalCode,
  					 BillingStreet, BillingCity, BillingCountry, BillingState, BillingPostalCode, 
  			(SELECT Street__c, City__c, Country__c, State__c, Postal_Code__c FROM Addresses__r WHERE Account__c IN :accts2)
  			FROM Account WHERE Id IN :accts2];

	// Assert that the correct number of Address objects exist for each Account.
	for (Integer i=0; i<20; i++) {
		System.assertEquals(2, accts1.get(i).Addresses__r.size(), 'Incorrect number of Address objects for first account set row ' + i + '.');
		System.assertEquals(0, accts2.get(i).Addresses__r.size(), 'Incorrect number of Address objects for second account set row ' + i + '.');
	}
  	
  }
  
  /**
   * Test update of SFDC2 checkbox
   */
  @IsTest
  static void testUpdateSFDC2Checkbox () {
  	
  	List<Account> sfdc2Accounts = new List<Account>();
  	
  	Id businessAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account SFDC2').getRecordTypeId();
  	Id hybridAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business/Consumer Person Account').getRecordTypeId();
  	Id consumerAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer Person Account SFDC2').getRecordTypeId();
  	Id nonSfdc2Id= Schema.SObjectType.Account.getRecordTypeInfosByName().get('WLD').getRecordTypeId();
  	Id prospectingBusinessAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospecting Business').getRecordTypeId();
  	Id prospectingHybridAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospecting Business/Consumer PA').getRecordTypeId();
  	Id prospectingConsumerAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospecting Consumer PA').getRecordTypeId();
  	
  	for(Integer i = 0; i<20; i++) {
  		sfdc2Accounts.add(new Account(name='test business account ' + i, RecordTypeId=businessAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(firstName='test', lastName='hybrid account ' + i, RecordTypeId=hybridAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(firstName='test', lastName='consumer account ' + i, RecordTypeId=consumerAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(name='test prospecting business account ' + i, RecordTypeId=prospectingBusinessAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(firstName='test', lastName='prospecting hybrid account ' + i, RecordTypeId=prospectingHybridAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(firstName='test', lastName='prospecting consumer account ' + i, RecordTypeId=prospectingConsumerAccountId, SFDC2__c=false));
  		sfdc2Accounts.add(new Account(name='test non SFDC2 business account ' + i, RecordTypeId=nonSfdc2Id, SFDC2__c=true));
  	}

	insert sfdc2Accounts;
	
	sfdc2Accounts = [select Id, SFDC2__c, RecordTypeId from Account where Id IN :sfdc2Accounts];
	
	// Check value of the SFDC2 checkbox
	for (Account account: sfdc2Accounts) {
		if (account.RecordTypeId != nonSfdc2Id) {
			System.assertEquals(true, account.SFDC2__c, 'Unexpected SFDC2 status for recordTypeId ' + account.RecordTypeId + ' after insert ');
		} else {
			System.assertEquals(false, account.SFDC2__c, 'Unexpected SFDC2 status for recordTypeId ' + account.RecordTypeId + ' after insert ');
		}
	}

	// Manually update SFDC2 checkbox
	for (Account account: sfdc2Accounts) {
		if (account.RecordTypeId != nonSfdc2Id) {
			account.SFDC2__c = false;
		} else {
			account.SFDC2__c = true;
		}
	}

	Test.startTest();
	update sfdc2Accounts;
	Test.stopTest();	
	
	sfdc2Accounts = [select Id, SFDC2__c, RecordTypeId from Account where Id IN :sfdc2Accounts];

	// Check value of the SFDC2 checkbox
	for (Account account: sfdc2Accounts) {
		if (account.RecordTypeId != nonSfdc2Id) {
			System.assertEquals(true, account.SFDC2__c, 'Unexpected SFDC2 status for recordTypeId ' + account.RecordTypeId + ' after insert ');
		} else {
			System.assertEquals(false, account.SFDC2__c, 'Unexpected SFDC2 status for recordTypeId ' + account.RecordTypeId + ' after insert ');
		}
	}

  }
  
  /**
  * SFDC2: Tests the functionality of triggerMortgageCrossSellOppCreation
  */
  /* @isTest
  static void testTriggerMortgageCrossSellOppCreation() {
  	Account a = new Account();
  	a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer Person Account SFDC2').getRecordTypeId();
  	a.FirstName ='Test';
  	a.LastName ='Account';
  	a.Edisclosure_Accepted_Person__c = false;
  	insert a;
  	a = [SELECT Person_Contact_Id__c FROM Account WHERE Id = :a.Id];
  	Financial_Account_SFDC2__c fa = new Financial_Account_SFDC2__c();
  	fa.Name = 'TEST Account';
  	fa.Department__c = 'Mortgage Lending';
  	insert fa;
  	Financial_Account_Contact_Link_SFDC2__c facl = new Financial_Account_Contact_Link_SFDC2__c();
  	facl.Contact__c = a.Person_Contact_Id__c;
  	facl.Financial_Account__c = fa.Id;
  	facl.CIF_JHA_LINK__c = '0000^TEST';
  	insert facl;
  	Campaign c = new Campaign();
  	c.Name = '250 Consumer Deposit Campaign';
  	insert c;
  	CampaignMemberStatus cms = new CampaignMemberStatus();
  	cms.CampaignId = c.Id;
  	cms.Label = 'Attempting Contact';
  	insert cms;
  	
  	Test.startTest();
  	a.Edisclosure_Accepted_Person__c = true;
  	update a;
  	Test.stopTest();
  	
  	a = [SELECT 
  			Id,
  			(SELECT
  				Id
  			 FROM
  			 	Opportunities
  			 WHERE
  			 	Name = 'Cross Sell from Mortgage'),
  			(SELECT
  				Id
  			 FROM
  			 	PersonCampaignMembers
  			 WHERE
  			 	Campaign.Name = '250 Consumer Deposit Campaign')
  		 FROM 
  		 	Account 
  		 WHERE 
  		 	Id = :a.Id];
	System.assertEquals(1, a.Opportunities.size());
	System.assertEquals(1, a.PersonCampaignMembers.size());
  }  */
  
  	@isTest
    static void testHandleDoNotCallUpdateSFDC2() {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer Person Account SFDC2').getRecordTypeId();
        Id finRTId = Schema.SObjectType.Financial_Account_SFDC2__c.getRecordTypeInfosByName().get('CD').getRecordTypeId();
		
		Account acct = new Account();
		acct.LastName = 'Test';
		acct.RecordTypeId = acctRTId;
		acct.Occupation_SFDC2__pc = 'Tester';
		acct.PersonDoNotCall = false;
		insert acct;
		acct = [SELECT Person_Contact_Id__c FROM Account WHERE Id = :acct.Id];
		
		Financial_Account_SFDC2__c fa = new Financial_Account_SFDC2__c();
		fa.Name = 'TEST 0000';
		fa.Status__c = 'Active';
		fa.Product_Class__c = 'CD';
		fa.RecordTypeId = finRTId;
		fa.Maturity_Date__c = Date.today().addDays(30);
		insert fa;
		
		Financial_Account_Contact_Link_SFDC2__c link = new Financial_Account_Contact_Link_SFDC2__c();
		link.Financial_Account__c = fa.Id;
		link.Contact__c = acct.Person_Contact_Id__c;
		link.CIF_JHA_LINK__c = '30DayCDTEST1111';
		insert link;
		for(CampaignMember cm : [SELECT Campaign.Name, Status FROM CampaignMember WHERE ContactId = :acct.Person_Contact_Id__c]) {
			System.assertEquals('Attempting Contact', cm.Status);
			//ensure 30 Day CD Maturity Campaign
			if(cm.ContactId == acct.Person_Contact_Id__c) {
				System.assertEquals('30 Day CD Maturity', cm.Campaign.Name);
			}
		}
		
		Test.startTest();
		acct.PersonDoNotCall = true;
		update acct;
		Test.stopTest();
		CampaignMember[] cm = [SELECT Campaign.Name, Status FROM CampaignMember WHERE ContactId = :acct.Person_Contact_Id__c];
		System.assertEquals(0, cm.size());
    }
}