objects/Account_Contact_Owner_Sync__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration for Account/Contact ownership synching</description>
    <fields>
        <fullName>Account_Record_Type_ID__c</fullName>
        <inlineHelpText>Must be 18 character unique record type ID</inlineHelpText>
        <label>Account Record Type ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Contact Owner Sync</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SFDC2__c</fullName>
        <formula>RecordType.Name == &apos;Business SFDC2&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Conversion_SFDC2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by ETL tool to trigger conversion from Contact to Person Account</description>
        <label>Trigger Conversion</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_Contact_Link_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Creates a many-to-many junction between Contacts or Person Accounts and Financial Accounts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact or Person Account related to this link</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Contact Link</label>
    <nameField>
        <displayFormat>FACL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Contact Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contact Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactTriggerHandler.cls
/**
* @description <p>Handler class for ContacttTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public class ContactTriggerHandler extends TriggerHandler{

  /** Map of Contacts before changes */
  private Map<Id, Contact> oldContMap;
  /** Map of Contacts with changes */
  private Map<Id, Contact> newContMap;
  /** List of Contact with changes */
  private List<Contact> newContList;
  
  /** Constructor */
  public ContactTriggerHandler() {
  	this.oldContMap = (Map<Id, Contact>) Trigger.oldMap;
  	this.newContMap = (Map<Id, Contact>) Trigger.newMap;
  	this.newContList = Trigger.new;
  }
  
  /**
  * Process beforeUpdate logic
  */
  public override void beforeUpdate() {
  	reassignContactOwner(newContList);
  }
  
  /**
  * Process beforeInsert logic
  */
  public override void beforeInsert() {
  	reassignContactOwner(newContList);
  }
  
  /**
   * Process afterUpdate logic
   */
  public override void afterUpdate() {
	// convertFlaggedContactsSFDC2(this.newContList);
	handleDoNotCallUpdateSFDC2();	
  }
  
  /**
   * Process afterInsert logic
   */
  public override void afterInsert() {
	// convertFlaggedContactsSFDC2(this.newContList);  	
  }
  
  /**
  * When the Do Not Call checkbox is toggled, trigger check to determine whether Contact
  * should be added to or expired from a campaign
  */
  private void handleDoNotCallUpdateSFDC2() {
  	//list of ids to verify for expiration
  	Set<Id> doNotCallList = new Set<Id>();
  	//list of ids to verify for campaign member addition
  	Set<Id> potentialCMList = new Set<Id>();
  	
  	for(Contact c : newContMap.values()) {
  		if(c.SFDC2__c) {
	  		Contact oldC = oldContMap.get(c.Id);
	  		if(c.DoNotCall != oldC.DoNotCall) {
	  			potentialCMList.add(c.Id);
	  		}
  		}
  	}
  	
  	//only contacts related to Financial Accounts should be considered for campaign updates
  	if(potentialCMList.size() > 0) {
  		List<String> membersToExpire = new List<String>();
  		List<String> finAcctLinksToVerify = new List<String>();
  		for(Financial_Account_Contact_Link_SFDC2__c links : [SELECT Contact__c from Financial_Account_Contact_Link_SFDC2__c WHERE Contact__c in :potentialCMList]) {
			if (potentialCMList.contains(links.Contact__c)) {
  				finAcctLinksToVerify.add(links.Id);
  			}
  		}
  		
  		if(finAcctLinksToVerify.size() > 0) {
  			CampaignMemberAutomationHandler.handleCampaignMemberAutomation(finAcctLinksToVerify);
  		}
  	}
  }
  
  /**
  * When Contacts related to specific Account record types inserted/updated, ensure that the Owner is synched with the Account Owner
  * @param newContList list of changed Contacts
  */
  private void reassignContactOwner(List<Contact> newContList) {
  	System.debug('**** reassignContactOwner');
    //Establish a map of Account Record Type IDs whose Contact record owners should be synched
    Set<String> acctRTSet = new Set<String>();
  	for(Account_Contact_Owner_Sync__c cs : [
  											select Account_Record_Type_ID__c
  											from Account_Contact_Owner_Sync__c
  										   ]) {
		acctRTSet.add(cs.Account_Record_Type_ID__c);
		System.debug('**** Record Type Id to sync = ' + cs.Account_Record_Type_ID__c);
	}
  	
  	//establish a set of Account Ids for the affected Contacts that match the record type IDs for synching
  	Set<Id> acctIdSet = new Set<Id>();
  	for(Contact c : newContList) {
  		acctIdSet.add(c.AccountId);
  	}
  	Map<Id,Account> acctMap = new Map<Id,Account>([select Id, OwnerId from Account where Id in :acctIdSet and RecordTypeId in :acctRTSet]);
  	
  	//any contacts related to an Account found in the map will need to have the Owner synched
  	for(Contact c : newContList) {
  		if(c.AccountId != null &&
  			acctMap.containsKey(c.AccountId) &&
  			c.OwnerId != acctMap.get(c.AccountId).OwnerId) {
  				c.OwnerId = acctMap.get(c.AccountId).OwnerId;
  		}
  	}
  }
  
  /**
   * SFDC2: When the ETL flags a set of Contact records using the Trigger_Conversion_SFDC2__c flag,
   * convert the Contacts to Hybrid Person Accounts
   */
 /* private void convertFlaggedContactsSFDC2(List<Contact> contacts) {
  	
  	Set<Id> contactsToConvert = new Set<Id>();
    Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business/Consumer Person Account').getRecordTypeId();
  	
  	for(Contact contact: contacts) {
  		if(contact.SFDC2__c && contact.Trigger_Conversion_SFDC2__c && contact.IsPersonAccount == false) contactsToConvert.add(contact.Id);
  	}
  	
  	Map<Id,Account> convertedAccounts = OpportunityTriggerHandler.convertContactsToPersonAccounts(contactsToConvert, personAccountRTId);
  	
  } 
 */ 
}