objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current Physical</fullName>
                </value>
                <value>
                    <fullName>Current Mailing</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Add-{00}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddressTriggerHandler.cls
/**
* @description <p>Handler class for AddressTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public class AddressTriggerHandler extends TriggerHandler {
  /** Map of Addresses before changes */
  private Map<Id, Address__c> oldAddressMap;
  /** Map of Addresses with changes */
  private Map<Id, Address__c> newAddressMap;
  /** Current Address Status */
  public final static String STATUS_CURRENTADDRESS = 'Current Mailing';
  /** Former Address Status */
  public final static String STATUS_FORMERADDRESS = 'Former';
  
  /** Constructor */
  public AddressTriggerHandler() {
  	this.oldAddressMap = (Map<Id, Address__c>) Trigger.oldMap;
  	this.newAddressMap = (Map<Id, Address__c>) Trigger.newMap;
  }
  
  /**
  * Process afterUpdate logic
  */
  public override void afterUpdate() {
  	handleCurrentAddress(oldAddressMap, newAddressMap);
  }
  
  /**
  * Process afterInsert logic
  */
  public override void afterInsert() {
  	handleCurrentAddress(null, newAddressMap);
  }
  
  /**
  * When Address records are set to Current Mailing, (1) ensure that associated Account records are updated with the current address
  * and (2) all other "Current Mailing" Address records are set to "Former" 
  * @param oldAcctMap map of initial state Accounts
  * @param newAcctMap map of changed Accounts
  */
  private void handleCurrentAddress(Map<Id,Address__c> oldMap, Map<Id,Address__c> newMap) {
  	Map<Id,Address__c> accountAddressIdMap = new Map<Id,Address__c>();

	//for addresses created or updated with Current Mailing status, update the corresponding Account record with the address
	for(Address__c a : newMap.values()) {
      if(!accountAddressIdMap.containsKey(a.Account_Name__c) &&
      	  ((oldMap == null ||
	     	(oldMap != null && oldMap.get(a.Id).Status__c != a.Status__c)) && a.Status__c == AddressTriggerHandler.STATUS_CURRENTADDRESS)) {
	    accountAddressIdMap.put(a.Account_Name__c, a);
	    toUpdate.add(new Account(Id=a.Account_Name__c, PersonMailingStreet=a.Address_Line__c, PersonMailingCity=a.City__c, PersonMailingState=a.State__c, PersonMailingPostalCode=a.Zip__c));
	  }
  	}
  	
  	if(accountAddressIdMap.size() == 0) {
  		//no records to update
  		return;
  	}
  	
  	//locate Address records associated with updated Accounts to ensure that statuses are set to "Former"
  	for(Address__c[] addresses : [
  									SELECT Account_Name__c, Status__c 
  									FROM Address__c 
  									WHERE Account_Name__c in :accountAddressIdMap.keyset() AND 
  									Status__c = :AddressTriggerHandler.STATUS_CURRENTADDRESS
  								  ]) {
  	  for(Address__c a : addresses) {
  	  	if(a.Id != accountAddressIdMap.get(a.Account_Name__c).Id) {
  	  	  //set any other Address record to "Former" if it currently has current mailing address status
  	  	  toUpdate.add(new Address__c(Id=a.Id, Status__c=AddressTriggerHandler.STATUS_FORMERADDRESS));
  	  	}
  	  }
  	}
  }
}