objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current Physical</fullName>
                </value>
                <value>
                    <fullName>Current Mailing</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Add-{00}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Phone_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phone_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accurint</fullName>
                </value>
                <value>
                    <fullName>Accurint - XML</fullName>
                </value>
                <value>
                    <fullName>Clear</fullName>
                </value>
                <value>
                    <fullName>Special Batch</fullName>
                </value>
                <value>
                    <fullName>Lead Source</fullName>
                </value>
                <value>
                    <fullName>Data Migration</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>Fast Busy</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Ring No Answer</fullName>
                </value>
                <value>
                    <fullName>Spoke to Customer</fullName>
                </value>
                <value>
                    <fullName>VM Confirmed</fullName>
                </value>
                <value>
                    <fullName>VM Full</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>PH-{00}</displayFormat>
        <label>Phone Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Webservice_Callout__c.object
<CustomObject>
    <description>Used to log webservice callouts for custom functionality. Included:
- LexisNexis Account updates for Specialty Finance</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_Submitted__c</fullName>
        <label>Date/Time Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (ms)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <label>Job ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to capture Phone Number record that triggered Neustar Phone Attr callout</description>
        <label>Phone Number</label>
        <referenceTo>Phone_Number__c</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Webservice Callout</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Callout Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LexisNexisAccountQueueableJob.cls
public class LexisNexisAccountQueueableJob implements Queueable, Database.AllowsCallouts {
    private static final String greerOwnerId = '005i0000003A0Gn';
    private static final String outboundOwnerId = '005i0000006ne2Z';
    private Boolean isTest = false;
    private TestDataFactory.SingleRequestMock TestHttpCallout;
    
    /** Number of person record results to return in one job call */
    public static final Integer MAXRETURNCOUNT = 100; //future enhancement may be to move to custom setting and allow for multiple callouts
    
    /** Starting record number for API search */
    private Integer startResultCount = 1;
    
    /** Account passed in from Trigger */
    private Account acct{get; set;}
    
    /** Constructor */
    public LexisNexisAccountQueueableJob(Account acct){
        this(acct, false, null);
    }
    
    /** Constructor */
    public LexisNexisAccountQueueableJob(Account acct, Boolean isTest, TestDataFactory.SingleRequestMock testCall){
        this.acct = acct;
        this.isTest = isTest;
        this.TestHttpCallout = testCall;
    }
    
    /**
     * Interface method. 
     */
    public void execute(QueueableContext context) {
        //Retrieve LexisNexist Account Callout record for this specific job
        Webservice_Callout__c currentCallout = new Webservice_Callout__c();
        if(!isTest) {
            currentCallout = [Select Id, Status__c, Date_Time_Submitted__c, Response__c, Account__c,
                                     Job_ID__c From Webservice_Callout__c Where Job_ID__c = :context.getJobId()];
        }
        //retrieve necessary Account data to perform comparisons
        acct = [SELECT
                        Id,
                        Gender_Person__c,
                        Deceased_Person__c,
                        Date_of_Death__c,
                        Social_Security_Number_Person__c,
                        (SELECT
                            Id,
                            Phone_Number__c
                         FROM Phone_Numbers__r),
                        (SELECT
                            Id, 
                            Address_Line__c
                         FROM Address__r)
                    FROM Account
                    WHERE Id = :acct.Id
                    ];
        
        //Start time - used to determine Duration of callout
        Long start = System.now().getTime();
        
        //Make the REST call
        try{
            HttpRequest req = new HttpRequest();
            HttpResponse res;
            req.setMethod('GET');
            if(!Test.isRunningTest()) {
                String searchVal = acct.Social_Security_Number_Person__c.replace('-','').trim();
                req.setEndpoint('callout:LexisNexisAccurint/WsAccurint/BpsSearch?ver_=1.87&User.GLBPurpose=1&User.DLPurpose=3&Options.ReturnCount=' + LexisNexisAccountQueueableJob.MAXRETURNCOUNT + '&Options.StartingRecord=' + this.startResultCount + '&SearchBy.SSN=' + searchVal);
                req.setTimeout(60000);
                Http h = new Http();
                res = h.send(req);
            } else {
                TestDataFactory.SingleRequestMock fakeResponse = TestHttpCallout;
                res = fakeResponse.respond(req);
            }
            
            //4a - Response OK
            if(res.getStatusCode() == 200){
                currentCallout.status__c = 'OK';
            //4b - Reponse KO
            }else{
                currentCallout.status__c = 'KO';
            }
            //Save the response body
            currentCallout.Response__c = res.getBody();
            processResponseBody(res.getBodyDocument());
        }catch(LexisNexisException lne) {
            currentCallout.status__c = 'KO';
        }catch(Exception e){
            //Callout failed (e.g. timeout)
            currentCallout.status__c = 'Failed';
            currentCallout.Response__c = e.getStackTraceString().replace('\n',' / ')+' - '+e.getMessage();
        }
        //Sets info about the job
        DateTime submittedDateTime = System.now();
        currentCallout.Date_Time_Submitted__c = submittedDateTime;
        acct.SF_LexisNexis_Callout_Status__c = currentCallout.Status__c;
        acct.SF_LexisNexis_Callout_Date_Time__c = submittedDateTime;
        currentCallout.Duration__c = submittedDateTime.getTime()-start;
        TriggerValidator.reset();
        update acct;
        if(!isTest) {
            update currentCallout;
        }
    }
   
    private void processResponseBody(DOM.Document doc) {
        Boolean isPersonFound = false;
        Boolean hasNewPhoneNumber = false;
        Boolean hasFoundAddress = false;
        Boolean hasGender = false;
        Boolean isDeceased = false;
        List<LexisNexisRecord> records = new List<LexisNexisRecord>();  
        Boolean hasUnexpectedResponse = false;
        LexisNexisException lne = new LexisNexisException('An unexpected response was returned ' +
                                        'from LexisNexis: ');
        DOM.XMLNode root = doc.getRootElement();
        DOM.XMLNode responseNode = root.getChildElements()[0];
        for(DOM.XMLNode rootChildNode : responseNode.getChildElements()) {
            if(rootChildNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                String childNodeName = rootChildNode.getName().toLowerCase();
                String childNodeValue = rootChildNode.getText();
                if(childNodeName == 'header') {
                    for(DOM.XMLNode headerNode : rootChildNode.getChildElements()) {
                        if(headerNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                            String headerNodeName = headerNode.getName().toLowerCase();
                            String headerNodeValue = headerNode.getText();
                            if(headerNodeName == 'status') {
                                if(headerNodeValue != '0') {
                                    hasUnexpectedResponse = true;
                                    lne.setMessage(lne.getMessage() + ' Status=' + headerNodeValue);
                                }
                            } else if (headerNodeName == 'message') {
                                hasUnexpectedResponse = true;
                                lne.setMessage(lne.getMessage() + ' Message=' + headerNodeValue);
                            }
                        }
                    }       
                } else if (childNodeName == 'subjecttotalcount') {
                    System.debug('*** Number of records returned from LexisNexis=' + childNodeValue);
                    If(childNodeValue != null && Integer.valueOf(childNodeValue) > 0) {
                        isPersonFound = true;
                    }
                } else if (childNodeName == 'records') {
                    for(DOM.XMLNode recordNode : rootChildNode.getChildElements()) {
                        //process all records
                        if(recordNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                            String recordNodeName = recordNode.getName().toLowerCase();
                            if(recordNodeName == 'record') {
                                LexisNexisRecord lnr = new LexisNexisRecord(recordNode);
                                records.add(lnr);
                            }   
                        }
                    }
                }
            }
        }
        if(hasUnexpectedResponse) {
            throw lne;
        }
        System.debug('*** Processed ' + records.size() + ' results from LexisNexis');
        if(records.size() > 0) {
            //if results were returned, process records
            List<SObject> toInsert = new List<SObject>();
        
            Set<String> phoneSet = new Set<String>();
            Address__c newAddress;
            Boolean hasAddress = false;
            for(LexisNexisRecord rec : records) {
                if(!hasGender && rec.Gender != null) {
                    hasGender = true;
                    acct.Gender_Person__c = rec.Gender;
                }
                if(rec.Deceased && !acct.Deceased_Person__c) {
                    isDeceased = true;
                    acct.Deceased_Person__c = true;
                }
                if(rec.DOD != null && acct.Date_of_Death__c == null) {
                    isDeceased = true;
                    acct.Deceased_Person__c = true;
                    acct.Date_of_Death__c = rec.DOD;
                }
                if(rec.Phone10 != null) {
                    Boolean hasPhone = false;
                    String lnPhone = rec.Phone10.replaceAll('[^0-9]', '');
                    for(Phone_Number__c pn : acct.Phone_Numbers__r) {
                        String acctPhone = pn.Phone_Number__c.replaceAll('[^0-9]', '');
                        if(acctPhone == lnPhone) {
                            hasPhone = true;
                            break;
                        }
                    }
                    if(!hasPhone) {
                        hasNewPhoneNumber = true;
                        phoneSet.add(lnPhone);
                    }
                }
                if(rec.AddressStreetNumber != null && !hasFoundAddress) {
                    hasFoundAddress = true;
                    for(Address__c add : acct.Address__r) {
                        if(add.Address_Line__c != null) {
                            String[] addressComponents = add.Address_Line__c.split(' '); //requirement is that only numeric portion needs to match
                            if(rec.AddressStreetNumber == addressComponents[0]) {
                                hasAddress = true;
                                break;
                            }
                        }
                    }
                    if(newAddress == null && !hasAddress) {
                        newAddress = new Address__c();
                        newAddress.Account_Name__c = acct.Id;
                        newAddress.Address_Line__c = rec.AddressStreetNumber + ((rec.AddressStreetDirection != '') ? ' ' + rec.AddressStreetDirection : '') + ' ' + rec.AddressStreetName + ' ' + rec.AddressStreetSuffix;
                        newAddress.City__c = rec.AddressCity;
                        newAddress.State__c = rec.AddressState;
                        newAddress.Zip__c = rec.AddressZip5 + ((rec.AddressZip4 != '') ? '-' + rec.AddressZip4 : '');
                        //newAddress.Status__c = 'Accurint - XML';
                        toInsert.add(newAddress);
                    }
                }
            }
            for(String pn : phoneSet) {
                Phone_Number__c phone = new Phone_Number__c();
                phone.Source__c = 'Accurint - XML';
                phone.Account_Name__c = acct.Id;
                phone.Phone_Number__c =  '(' + pn.substring(0, 3) + ') ' + pn.substring(3, 6) + '-' + pn.substring(6);
                toInsert.add(phone);
            }
            if(toInsert.size() > 0) {
                insert toInsert;
            }
        }
        //handle Research Status updates
        if(!isPersonFound) {
            acct.Research_Status_Person__c = 'Hard to Find';
            acct.OwnerId = greerOwnerId;
        } else {
            if(isDeceased) {
                acct.Research_Status_Person__c = 'Hard to Find - Deceased';
                acct.OwnerId = greerOwnerId;
            } else {
                if(hasNewPhoneNumber) {
                    acct.Research_Status_Person__c = 'New Researched';
                    acct.OwnerId = outboundOwnerId;
                } else {
                    acct.Research_Status_Person__c = 'Needs Research';
                    acct.OwnerId = greerOwnerId;
                }
            }
        }
    }
    
    /** Class used to represent a single record response from LexisNexis */
    public class LexisNexisRecord {
        public String Type {get; set;}
        public String Gender {get; set;}
        public String AddressStreetNumber {get; set;}
        public String AddressStreetDirection {get; set;}
        public String AddressStreetName {get; set;}
        public String AddressStreetSuffix {get; set;}
        public String AddressCity {get; set;}
        public String AddressState {get; set;}
        public String AddressZip5 {get; set;}
        public String AddressZip4 {get; set;}
        public Boolean Deceased {get; set;}
        public Date DOD {get; set;}
        public String Phone10 {get; set;}
        
        public LexisNexisRecord(DOM.XMLNode recordNode) {
            this.Type = '';
            this.Gender = '';
            this.AddressStreetNumber = '';
            this.AddressStreetDirection = '';
            this.AddressStreetName = '';
            this.AddressStreetSuffix = '';
            this.AddressCity = '';
            this.AddressState = '';
            this.AddressZip5 = '';
            this.AddressZip4 = '';
 
            for (DOM.XMLNode detailNode : recordNode.getChildElements()) {
                if(detailNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                    String nodeName = detailNode.getName().toLowerCase();
                    String nodeValue = detailNode.getText();
                    System.debug('**** Node "' + nodeName + '" = "' + nodeValue + '"');
                    if(nodeName == 'type') {
                        this.Type = nodeValue;
                    } else if(nodeName == 'gender') {
                        this.Gender = nodeValue;
                    } else if(nodeName == 'address') {
                        for(DOM.XMLNode addressNode : detailNode.getChildElements()) {
                            if(addressNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                                String addressNodeName = addressNode.getName().toLowerCase();
                                String addressNodeValue = addressNode.getText();
                                if(addressNodeValue == null) {
                                    addressNodeValue = '';
                                }
                                if(addressNodeName == 'streetnumber') {
                                    this.AddressStreetNumber = addressNodeValue;
                                } else if(addressNodeName == 'streetpredirection') {
                                    this.AddressStreetDirection = addressNodeValue; 
                                } else if (addressNodeName == 'streetname') {
                                    this.AddressStreetName = addressNodeValue;
                                } else if (addressNodeName == 'streetsuffix') {
                                    this.AddressStreetSuffix = addressNodeValue;
                                } else if (addressNodeName == 'city') {
                                    this.AddressCity = addressNodeValue;
                                } else if (addressNodeName == 'state') {
                                    this.AddressState = addressNodeValue;
                                } else if (addressNodeName == 'zip5') {
                                    this.AddressZip5 = addressNodeValue;
                                } else if (addressNodeName == 'zip4') {
                                    this.AddressZip4 = addressNodeValue;
                                }
                            }
                        }
                    } else if(nodeName == 'deceased') {
                        this.Deceased = (nodeValue == 'Y') ? true : false;
                    } else if (nodeName == 'dod') {
                        String yearVal;
                        String monthVal;
                        String dayVal;
                        for(DOM.XMLNode dodNode : detailNode.getChildElements()) {
                            if(dodNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                                String dodNodeName = dodNode.getName().toLowerCase();
                                String dodNodeValue = dodNode.getText();
                                if(dodNodeName == 'year') {
                                    yearVal = dodNodeValue;
                                } else if (dodNodeName == 'month') {
                                    monthVal = dodNodeValue;
                                } else if (dodNodeName == 'day') {
                                    dayVal = dodNodeValue;
                                }
                            }
                        }
                        if(yearVal != null && monthVal != null && dayVal != null) {
                            this.DOD = Date.newInstance(Integer.valueOf(yearVal), Integer.valueOf(monthVal), Integer.valueOf(dayVal));
                        }
                    } else if (nodeName == 'phoneinfo') {
                        for(DOM.XMLNode phoneNode : detailNode.getChildElements()) {
                            if(phoneNode.getNodeType() == DOM.XMLNodeType.ELEMENT) {
                                String phoneNodeName = phoneNode.getName().toLowerCase();
                                String phoneNodeValue = phoneNode.getText();
                                if(phoneNodeName == 'phone10') {
                                    this.Phone10 = phoneNodeValue;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
   

    private void updateAccount(Account acct) {
        update acct;
    }   
    public class LexisNexisException extends Exception { }
}