objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Add-{00}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/USPSAddressComp_Controller.cls
public with sharing class USPSAddressComp_Controller {

	// address coming in from component attrs
	public USPS.USPSAddress Address2Check {get; set;}

	// address coming back from USPS API call
	public USPS.USPSAddress AddressFromUSPS {get; set;}		
	
	// this is used to determine when an address changes
	public USPS.USPSAddress PreviousAddress {get; set;}

	// this is the object we are going to update
	public Address__c CurrentAddress {get; set;}	
	
	// should the panel be rendered?
	public boolean DisplayPopUp {get; set;}
	
	// did the user dismiss the panel?
	public boolean Dismissed {get; set;}
		
	//when deciding if the address is bad (and needs review), should we
	// compare just the first 5 digits (set 2 false) of the zip or all 9 (set to true)?
	public boolean CompareFullZip {get; set;}

	//MCC - USPS reports that the address is already correct
	public boolean AddressIsValidated {get; set;}

	public string USPS_ID {
		get { return USPS_ID; }
		set {
			if (value != '') {
				// only run this once a non blank ID is set . . . 
				
				USPS_ID = value;
				
				// 09/17/2012 - Salesforce doesn't have an action method for componenets
				// that gets called after the constructor and assign 2 like on pages
				// so we use this setter to call our validation method instead.

				ValidateAddress();
				
			} // value != ''
		} // end setter
	} // USPS_ID 
	
	public USPSAddressComp_Controller() {
		
		Address2Check = new USPS.USPSAddress();
		AddressFromUSPS = new USPS.USPSAddress();
		PreviousAddress = new USPS.USPSAddress();
		
		DisplayPopUp = false;
		CompareFullZip = false;
		Dismissed = false;
		
	} // constructor
	
	public boolean DidTheAddressChange() {
		// this method will look at Address2Check and compare it to AddressFromUSPS
		// to see if the user changed the address and if so tell the caller we need
		// to re-verify.
		
		// this ONLY works if called before any attempt to re-verify the address
				
		boolean ReturnValue = false;

		// this is very similar to AddressesAreDifferent except that the  full zip check is not optional

		// on the first run this will be empty so don't count that run . . . 
		if (PreviousAddress.hasData() == true) {
						
			if (Address2Check.Address2 != PreviousAddress.Address2) {			
				ReturnValue = true;
			} else if (Address2Check.City != PreviousAddress.City) {
				ReturnValue = true;
			} else if (Address2Check.State != PreviousAddress.State) {
				ReturnValue = true;
			} else if (Address2Check.getZip() != PreviousAddress.getZip()) {
				ReturnValue = true;
			} // Address2Check.Address1 != PreviousAddress.Address1
		} else {
			// if the previous address is blank, we are on the first call and need to validate
			ReturnValue = true;
		} // PreviousAddress.hasData() == true;
		
		return ReturnValue;

	} //DidTheAddressChange
	
	public boolean AddressesAreDifferent(boolean CheckZipPlus4) {
		
		// this method compares the addresses to see if USPS made any corrections
		
		// since this method is also called by the DidTheAddressChange() wrapper method
		// becareful when updating this method . . . .
			
		boolean ReturnValue = false;
		
		if (Address2Check.Address1 != AddressFromUSPS.Address1) {
			ReturnValue = true;
		} else if (Address2Check.Address2 != AddressFromUSPS.Address2) {
			ReturnValue = true;
		} else if (Address2Check.City != AddressFromUSPS.City) {
			ReturnValue = true;
		} else if (Address2Check.State != AddressFromUSPS.State) {
			ReturnValue = true;
		} else if (CheckZipPlus4 == true) {
			if (Address2Check.getZip() != AddressFromUSPS.getZip()) {
				ReturnValue = true;
			} // full zip compare
		} else if (CheckZipPlus4 == false) {
			if (Address2Check.Zip5 != AddressFromUSPS.Zip5) {
				ReturnValue = true;		
			} // compare zip 5's
		} // Address2Check.Address1 != AddressFromUSPS.Address1
		
		return ReturnValue;
		
	} // AddressesAreDifferent
	
	public void UpdateAddress2Check() {
		Address2Check.Address2 = CurrentAddress.Address_Line__c;
		Address2Check.City = CurrentAddress.City__c;
		Address2Check.State = CurrentAddress.State__c;
		Address2Check.Zip5 = CurrentAddress.Zip__c;		
	} // UpdateAddress2Check
	
	public void UpdatePreviousAddress() {		
		PreviousAddress.Address2 = Address2Check.Address2;
		PreviousAddress.City = Address2Check.City;
		PreviousAddress.State = Address2Check.State; 
		PreviousAddress.Zip5 = Address2Check.Zip5; 
	} // UpdatePreviousAddress
	
	public void ValidateAddress() {
		
		// set the var to catch any changes for future runs
		UpdatePreviousAddress();
		
		// update the object from the main controller's data
		UpdateAddress2Check();
								
		if (Address2Check.CanCheckAddress() == true) {	
		
			if (DidTheAddressChange()==true) {
				
				// use the USPS API class do validate the address				
				AddressFromUSPS = USPS.CheckAddress(Address2Check, USPS_ID);
			
				//MCC - commented out so that popup always displays with feedback to user
				DisplayPopUp = AddressesAreDifferent(CompareFullZip);
				AddressIsValidated = !(DisplayPopUp);
			} else {
				system.debug('Address Didn\'t Change!');

			} // DidTheAddressChange()==true || FirstRun == true

		}  // Address2Check.HasData() == true
		
	} // validate address
	
	public void UseCorrectedAddress() {
		// cross the addresses going out to the caller - due to USPS address2 being the 'main' street address
		// this is why we must copy field by field - instead of just doing a one line copy
 		
		CurrentAddress.Address_Line__c = AddressFromUSPS.Address2;
		CurrentAddress.City__c = AddressFromUSPS.City;
		CurrentAddress.State__c = AddressFromUSPS.State;
		CurrentAddress.Zip__c = AddressFromUSPS.getZip();
		
		DisplayPopUp = false;		
	} // UseCorrectedAddress
	
	public void Dismiss() {
		DisplayPopUp = false;
	} // Dismiss
	
	
} // end USPS_Address_Comp_Controller class