objects/Address_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Address objects are used to allow storing an unlimited number of current and historical addresses for Leads, Business Accounts and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>JH Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <label>Mortgage Lender</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <inlineHelpText>Please enter a five digit zip code, or a zip +4 code in the following format: #####-####</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Phone_SFDC2__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Consumer_Deposits</fullName>
        <active>true</active>
        <description>Campaigns for Consumer Deposits</description>
        <label>Consumer Deposits</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Email_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2__c</fullName>
        <formula>RecordType.Name == &apos;Business SFDC2&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC2</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Email  objects are used to allow storing an unlimited number of current and historical email addresses for Leads and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Email_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Status__c</fullName>
        <label>Email Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                    <default>true</default>
                    <label>Unverified</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <description>Type of email. Will not necessarily match Parent Record Type, e.g. an employee contact with a Person Account could have an Email with Parent Record Type = &apos;Personal&apos; and Email Type = &apos;Primary Business&apos;</description>
        <label>Email Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Personal</fullName>
                </value>
                <value>
                    <fullName>Primary Business</fullName>
                </value>
                <value>
                    <fullName>Other Personal</fullName>
                    <default>true</default>
                    <label>Other Personal</label>
                </value>
                <value>
                    <fullName>Other Business</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>JH Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to associated Lead record</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Email_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>EML-{0000}</displayFormat>
        <label>Email Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Manager_SFDC2__mdt.object
<CustomObject>
    <description>This custom metadate will be used to add all the Roles (Manager and Non-manager) for all SFDC2 BU</description>
    <fields>
        <fullName>Re_Assign_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field has the porpoise to apply the Lead assignment rules on the records created on the Site CreateLeadForm</description>
        <label>Re Assign Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecordType_DeveloperName__c</fullName>
        <description>Sae the developername for BU.</description>
        <label>RecordType DeveloperName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <description>SAve the recordtype name for the BU.</description>
        <label>RecordType Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLeadRT_SFDC2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field for Checking is the RT comming from SFDC2 and needs to be implemented in the LEadTriggerHandler</description>
        <label>isLeadRT</label>
        <type>Checkbox</type>
    </fields>
    <label>Manager SFDC2</label>
    <pluralLabel>Managers SFDC2</pluralLabel>
</CustomObject>

objects/Phone_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Phone objects are used to allow storing an unlimited number of current and historical phone numbers for Leads, Business Accounts and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Status__c</fullName>
        <label>Phone Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Type__c</fullName>
        <label>Phone Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Home</fullName>
                </value>
                <value>
                    <fullName>Primary Business</fullName>
                </value>
                <value>
                    <fullName>Primary Mobile</fullName>
                </value>
                <value>
                    <fullName>Primary Fax</fullName>
                </value>
                <value>
                    <fullName>Other Home</fullName>
                    <default>true</default>
                    <label>Other Home</label>
                </value>
                <value>
                    <fullName>Other Business</fullName>
                </value>
                <value>
                    <fullName>Other Mobile</fullName>
                </value>
                <value>
                    <fullName>Other Fax</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>JH Cell</fullName>
                </value>
                <value>
                    <fullName>JH Fax</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <displayFormat>PHN-{0000}</displayFormat>
        <label>Phone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Email_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Deliverable</fullName>
    </customValue>
    <customValue>
        <fullName>Undeliverable</fullName>
    </customValue>
    <customValue>
        <fullName>Hard Bounce</fullName>
        <isActive>false</isActive>
        <label>Hard Bounce</label>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
        <isActive>false</isActive>
        <label>Blocked</label>
    </customValue>
    <description>Email Verification Status</description>
    <masterLabel>Email Status</masterLabel>
</GlobalValueSet>

classes/LeadTriggerHandler.cls
/**
* @description <p>Handler class for LeadTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public class LeadTriggerHandler extends TriggerHandler{

  /** Map of Leads before changes */
  private Map<Id, Lead> oldLeadMap;
  /** Map of Leads with changes */
  private Map<Id, Lead> newLeadMap;
  /** List of new Leads */
  private List<Lead> newLeads;
  /** SFDC 2.0 : Lead status that triggers automated 2.0 conversion */
  public static final String AutoConvertStatus = 'Contacted/Converted';

  /** Constructor */
  public LeadTriggerHandler() {
    this.oldLeadMap = (Map<Id, Lead>) Trigger.oldMap;
    this.newLeadMap = (Map<Id, Lead>) Trigger.newMap;
    this.newLeads = (List<Lead>) Trigger.new;
  }

/**
  * Process beforeUpdate logic
  */
  public override void beforeUpdate() {
    if(this.newLeads[0].isFromApplication__c == false) {
        updateSFDC2Checkbox(this.newLeads);
        reassignLeadOwner_CD(this.oldLeadMap, this.newLeadMap);
        updatePhoneListSfdc2(this.oldLeadMap, this.newLeadMap);
        updateEmailListSfdc2(this.oldLeadMap, this.newLeadMap);
        updateAddressListSfdc2(this.oldLeadMap, this.newLeadMap);
        //SFDC2 - MC - checks to see if Lead needs to be reassigned to Business Unit queue
        reassignLeadToQueue();
    }
  }
  
  /**
   * Process afterUpdate logic
   */
  public override void afterUpdate() {
    handleLeadConversion(this.oldLeadMap, this.newLeadMap);
    if(this.newLeads[0].isFromApplication__c == false) {
        // 2.0 auto lead conversion
        handleAutoConvertLead();
    }
  }
  /**
  * Process afterInsert logic    
  */  
  public override void afterInsert() {
    assignmentRule(this.newLeads);
  } 
    
  /**
   * Process beforeInsert logic
   */
  public override void beforeInsert() {
    updateSFDC2Checkbox(this.newLeads);
  }   
  
  /*
    The Lead Assignment rules are applied for all the Record Types in SFDC2 
  in the afterInsert event
  */
    
    public static void assignmentRule(List<Lead> ltsLeads){
        
        
        Set<String> setMgr = new Set<String>();
          
          for (Manager_SFDC2__mdt rtName : [Select RecordType_Name__c from Manager_SFDC2__mdt where Re_Assign_Lead__c = true]){       
              setMgr.add(Schema.SObjectType.Lead.getRecordTypeInfosByName().get(rtName.RecordType_Name__c).getRecordTypeId()); 
          }
 

        List<Lead> leadList = new List<Lead>();

        //list<Manager_SFDC2__mdt> lstToReAssign = [SELECT RecordType_DeveloperName__c, RecordType_Name__c, Re_Assign_Lead__c FROM Manager_SFDC2__mdt WHERE Re_Assign_Lead__c = true ];
		System.debug('*******************Metodo After');
        for (Lead leadObj : ltsLeads) {
          if (leadObj.OwnerId  == UserInfo.getUserId() && setMgr.contains(leadObj.RecordTypeId)) {

            leadList.add(new Lead(id = leadObj.id));
          }
        }
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.assignmentRuleHeader.useDefaultRule = true;
        Database.update(leadList, dml);        
    }
   
  /**
  * SFDC 2.0 MC: When the Lead Status changes to Contacted/Converted, auto-convert
  * the Lead
  */
  private void handleAutoConvertLead() {
    Set<String> leadIdSet = new Set<String>();
    for(Lead l : newLeadMap.values()) {
        Lead oldLead = oldLeadMap.get(l.Id);
        //determine if this lead should auto convert
        if(!l.IsConverted &&
            l.SFDC2__c &&
            l.Status == LeadTriggerHandler.AutoConvertStatus) {
            leadIdSet.add(l.Id);
        }
    }
    if(!leadIdSet.isEmpty()) {
        List<String> leadList = new List<String>();
        leadList.addAll(leadIdSet);
        autoConvertLeads(leadList);
    }
  }
  
  /**
  * SFDC 2.0 MC: Future method to handle auto conversion of leads
  * @param idList list of lead ids to convert
  */
  @future
  private static void autoConvertLeads(List<String> idList) {
        List<Database.LeadConvert> leadConverts = new List<Database.LeadConvert>();
        Map<Id, Lead> leadConvertMap = new Map<Id, Lead>([
          SELECT Name, Opportunity_NameSFDC2__c, Primary_Campaign_SFDC2__c, OwnerId, Account_Record_Type_SFDC2__c, RecordTypeId , IPL_Channel_SFDC2__c
          FROM Lead 
          WHERE Id IN :idList
        ]);

        for(Lead l : leadConvertMap.values()) {
            Database.LeadConvert lc = new Database.LeadConvert();
            String oppName = l.Opportunity_NameSFDC2__c;
            if(oppName == null || oppName == '') {
                oppName = l.Name;
            }
               
            lc.setLeadId(l.Id);
            lc.setOpportunityName(oppName);
            lc.setConvertedStatus(LeadTriggerHandler.AutoConvertStatus);
            lc.setOwnerId(l.OwnerId);
            lc.setSendNotificationEmail(true);
            leadConverts.add(lc);
        }

        if (!leadConverts.isEmpty()) {
            // Record type ID for C&I SFDC2
            //Id rtId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('C&I SFDC2').getRecordTypeId();
            // Map of Account Record Types
            Map<String, RecordType> mapAccountRecordTypesByName = UtilsSFDC2.getRecordTypesMap('Account', 'Name');

            List<Database.LeadConvertResult> lcrList = Database.convertLead(leadConverts);
            List<sObject> futureUpdate = new List<sObject>();
            for(Database.LeadConvertResult lcr : lcrList) {
              Lead currentLead = leadConvertMap.get(lcr.getLeadId());

              // Don't process non successful conversions or Lead record types different from C&I SFDC2
              if(lcr.isSuccess() == false) {
                continue;
              }

              // Assign account Record Type and Owner
                Account a = new Account(Id=lcr.getAccountId());
                RecordType selectedAccountRecType = mapAccountRecordTypesByName.get(currentLead.Account_Record_Type_SFDC2__c);
                /*****IPL SFDC2 assingment*******/
                id idIPLRT = [Select id from RecordType where Name = 'IPL SFDC2' and SobjectType = 'Lead'].Id; 
                if(currentLead.RecordTypeId   == idIPLRT && currentLead.IPL_Channel_SFDC2__c == 'Direct'){
                    selectedAccountRecType = [Select id, IsPersonType, DeveloperName, Name from RecordType where Name = 'Consumer Person Account SFDC2'];
                }else if(currentLead.RecordTypeId   == idIPLRT && currentLead.IPL_Channel_SFDC2__c == 'Broker is Customer'){
                    selectedAccountRecType = [Select id, IsPersonType, DeveloperName, Name from RecordType where Name = 'Business/Consumer Person Account'];
                }
                /*****IPL SFDC2 assingment*******/
              if (selectedAccountRecType != null) { 
                a.RecordTypeId = selectedAccountRecType.Id; 
                // Update Contact Owner just for Non Person Account types
                if (selectedAccountRecType.IsPersonType == true) {
                  update a;
                } else {
                  Contact c = new Contact(Id=lcr.getContactId());
                  c.OwnerId = UserTriggerHandler.APIAccountId;
                  futureUpdate.add(c);
                }
              } else {
                  
                Contact c = new Contact(Id=lcr.getContactId());
                c.OwnerId = UserTriggerHandler.APIAccountId;
                futureUpdate.add(c);
              }

              // Update Account Owner
              a.OwnerId = UserTriggerHandler.APIAccountId;
              a.SFDC2__c = true;
              futureUpdate.add(a);

              // Assign Opportunity Campaign
              Opportunity o = new Opportunity(Id=lcr.getOpportunityId());
              o.CampaignId = leadConvertMap.get(lcr.getLeadId()).Primary_Campaign_SFDC2__c;
              futureUpdate.add(o);
            }

            if(!futureUpdate.isEmpty()) {
              update futureUpdate;
            }
        }
    }
  
  /**
  * SFDC 2.0 MC: When a Lead has Reassign To Queue ticked, reassign record to business unit
  * corresponding to owner's role
  */
  private void reassignLeadToQueue() {
    for(Lead l : newLeads) {
        //determine if the Lead is owned by a user who is a member of a role corresponding
        //to a business lead queue
        if(l.Reassign_To_Queue_SFDC2__c &&
            l.Owner_Role_SFDC2__c != null &&
            l.Owner_Role_SFDC2__c != '') {
            String queueName = UserTriggerHandler.roleLeadQueueMap.get(l.Owner_Role_SFDC2__c);
            if(queueName != null) {
                for(Group queue : UserTriggerHandler.queueMap.values()) {
                    if(queue.DeveloperName == queueName) {
                        l.OwnerId = queue.Id;
                        break;
                    }
                }
            }
        }
        //reset checkbox field
        l.Reassign_To_Queue_SFDC2__c = false;
    }
  }
  
 /**
  * For Consumer Deposits, when a Lead owned by a queue is updated by a member of the Consumer Deposits Team role,
  * reassign ownership to that user.
  * @param oldMap map of initial state Leads
  * @param newMap map of changed Leads
  */
  private void reassignLeadOwner_CD(Map<Id,Lead> oldMap, Map<Id,Lead> newMap) {
    // Filter to allow Sharepoint controller create leads without the reassignment
	if(!String.isBlank(UserInfo.getUserRoleId())){
      
        //determine the user's role
        UserRole ur = [SELECT DeveloperName FROM UserRole WHERE Id = :UserInfo.getUserRoleId()];
        
        //retrieve the Consumer Deposits Lead record type Id
        Id rtId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Consumer Deposits').getRecordTypeId();
        //RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer_Deposits' AND SobjectType = 'Lead'];
        
        if(ur != null &&  (ur.DeveloperName == 'Consumer_Deposits' || ur.DeveloperName == 'Consumer_Deposits_Manager')  && rtId != null) {
            for(Lead lead : newMap.values()) {
                String ownerId = Id.valueOf(lead.OwnerId);
                //if the record is a Consumer Deposits Lead and is not owned by a User, set the current user as the owner
                if(lead.RecordTypeId == rtId &&
                    !ownerId.startsWith('005') && lead.isFromApplication__c != true) {
                        lead.OwnerId = Userinfo.getUserId();
                }
            }
        }
	}
  }
  
  /**
  * When phone fields change on a Lead, update the list of custom Phone objects to include
  * the original phone number. (Except when the object is associated with an account.)
  * @param oldLeadMap map of original state Leads
  * @param newLeadMap map of changed Leads
  */
  private void updatePhoneListSfdc2(Map<Id,Lead> oldLeadMap, Map<Id,Lead> newLeadMap) {

    // Get original Lead phone fields and related Phone objects
    List<Lead> leadsWithPhones = [select id, Phone, MobilePhone, Fax,
                                  (select id, Lead__c, Phone__c, Phone_Status__c, Phone_Type__c from Phones__r where 
                                         Lead__c IN :newLeadMap.keySet() and Account__c = null)
                                  from Lead where id IN :newLeadMap.keySet() and SFDC2__c = true];
    
    // Prepare collection of Phone objects to insert and delete 
    List<Phone_SFDC2__c> phonesToInsert = new List<Phone_SFDC2__c>();
    List<Phone_SFDC2__c> phonesToDelete = new List<Phone_SFDC2__c>();
    
    Boolean foundRecord = false;
    String currPhone = null;
    String newPhone = null;
    String phoneType = null;

    // Loop through Leads and create Phone objects when phone fields have been updated
    for (Lead lead : leadsWithPhones) {

        // Skip converted Leads
        if (newLeadMap.get(lead.id).IsConverted) continue;

        // Mark any Phone objects that are now a primary phone field value for deletion
        for (Phone_SFDC2__c phone : lead.Phones__r) {
            if (phone.Phone__c == newLeadMap.get(lead.id).Phone ||
                phone.Phone__c == newLeadMap.get(lead.id).MobilePhone ||
                phone.Phone__c == newLeadMap.get(lead.id).Fax) {
                    phonesToDelete.add(phone); 
                    continue;
                }       
        }
        
        // Search each phone field for changes
        for (Integer i = 0; i<3; i++) {
            if (i==0) {currPhone = oldLeadMap.get(lead.id).Phone; newPhone = newLeadMap.get(lead.id).Phone; if (newLeadMap.get(lead.id).Company == null) {phoneType = 'Other Home';} else {phoneType = 'Other Business';}}
            if (i==1) {currPhone = oldLeadMap.get(lead.id).MobilePhone; newPhone = newLeadMap.get(lead.id).MobilePhone; phoneType = 'Other Mobile';}
            if (i==2) {currPhone = oldLeadMap.get(lead.id).Fax; newPhone = newLeadMap.get(lead.id).Fax; phoneType = 'Other Fax';}

            // Find phone field values that have changed
            if (currPhone != newPhone && currPhone != null && currPhone != '') {

                // Make sure a Phone object does not already exist for this phone number
                foundRecord = false;
                for (Phone_SFDC2__c phone : lead.Phones__r) {
                    if (phone.Phone__c == currPhone) foundRecord = true;
                }

                // Do not add a Phone object if a different Lead phone field has the original phone number value
                if (currPhone == newLeadMap.get(lead.id).Phone ||
                    currPhone == newLeadMap.get(lead.id).MobilePhone ||
                    currPhone == newLeadMap.get(lead.id).Fax ) foundRecord = true;

                // Create new Phone objects as necessary
                if (!foundRecord) {
                    Phone_SFDC2__c phone = new Phone_SFDC2__c();
                    phone.Lead__c = lead.Id;
                    phone.Phone__c = currPhone;
                    phone.Phone_Type__c = phoneType;
                    phone.Phone_Status__c = 'Verified';
                    phonesToInsert.add(phone);
                }
            }   
        }
    }
    
    insert phonesToInsert;
    delete phonesToDelete;
    
  }

  /**
  * When email address fields on a Lead change, update the related Emails list
  * to include the original email address (Except when the object is associated with an Account)
  * @param oldLeadMap map of original state Leads
  * @param newLeadMap map of changed Leads
  */
  private void updateEmailListSfdc2(Map<Id,Lead> oldLeadMap, Map<Id,Lead> newLeadMap) {
    
    // Get original Lead email fields and related Email objects
    List<Lead> leadsWithEmails = [select id, Email,
                                  (select id, Lead__c, Email__c, Email_Status__c, Email_Type__c from Email_Addresses__r where 
                                      Lead__c IN :newLeadMap.keySet() and Account__c = null) 
                                  from Lead where id IN :newLeadMap.keySet() and SFDC2__c = true];
                                         
    // Prepare collection of Email objects to insert and delete 
    List<Email_SFDC2__c> emailsToInsert = new List<Email_SFDC2__c>();
    List<Email_SFDC2__c> emailsToDelete = new List<Email_SFDC2__c>();
    
    Boolean foundRecord = false;
    String currEmail = null;
    String newEmail = null;
    String emailType = null;
    
    // Loop through Leads and create Email objects when email fields have been updated
    for (Lead lead : leadsWithEmails) {

        // Skip converted Leads
        if (newLeadMap.get(lead.id).IsConverted) continue;

        // Mark any email addresses that are now in a primary field for deletion
        for (Email_SFDC2__c email : lead.Email_Addresses__r) {
            if (email.Email__c == newLeadMap.get(lead.id).Email) {
                    emailsToDelete.add(email); 
                    continue;
            }                       
        }

        // Search each email field for changes
        for (Integer i = 0; i<1; i++) {
            if (i==0) {currEmail = oldLeadMap.get(lead.id).Email; newEmail = newLeadMap.get(lead.id).Email; if (newLeadMap.get(lead.id).Company == null) {emailType = 'Other Personal';} else {emailType = 'Other Business';}}

            // Find email field values that have changed
            if (currEmail != newEmail && currEmail != null && currEmail != '') {

                // Make sure a Email object does not already exist for this email address
                foundRecord = false;
                for (Email_SFDC2__c email : lead.Email_Addresses__r) {
                    if (email.Email__c == currEmail) foundRecord = true;
                }

                // Do not add an Email object if a different Account email field has the original email address value
                if (currEmail == newLeadMap.get(lead.id).Email) foundRecord = true;

                // Create new Email objects as necessary
                if (!foundRecord) {
                    Email_SFDC2__c email = new Email_SFDC2__c();
                    email.Lead__c = lead.Id;
                    email.Email__c = currEmail;
                    email.Email_Type__c = emailType;
                    email.Email_Status__c = 'Verified';
                    emailsToInsert.add(email);
                }
            }   
        }
    }
    
    insert emailsToInsert;
    delete emailsToDelete;
    
  }

  /**
   * When address fields on a Lead change, update the Address related list to include
   * the original address (Except when the Address is associated with an Account.)
   * @param oldAcctMap map of original state Accounts
   * @param newAcctMap map of changed Accounts
   */
  private void updateAddressListSfdc2(Map<Id,Lead> oldLeadMap, Map<Id,Lead> newLeadMap) {
    
    // Get original Lead addresss fields and related Address objects
    List<Lead> leadsWithAddresses = [select id, Street, City, Country, State, PostalCode, Primary_Loan_Type_SFDC2__c, Primary_Mortgage_Lender_SFDC2__c, 
                                     Primary_Purchase_Amount_SFDC2__c, Primary_Purchase_Date_SFDC2__c,
                                     (select id, Lead__c, Street__c, City__c, Country__c, State__c, Postal_Code__c, Address_Type__c,
                                            Mortgage_Lender__c, Loan_Type__c, Purchase_Date__c, Purchase_Amount__c from Addresses__r where 
                                            Lead__c IN :newLeadMap.keySet() and Account__c = null) 
                                     from Lead where id IN :newLeadMap.keySet() and SFDC2__c = true];
                                         
    // Prepare collection of Address objects to insert and delete   
    List<Address_SFDC2__c> addressesToInsert = new List<Address_SFDC2__c>();
    List<Address_SFDC2__c> addressesToDelete = new List<Address_SFDC2__c>();
    
    Boolean foundRecord = false;
    String currStreet = null;
    String currCity = null;
    String currCountry = null;
    String currState = null;
    String currPostalCode = null;
    String currLender = null;
    String currLoanType = null;
    Date currPurchaseDate = null;
    Double currPurchaseAmount = null;

    String newStreet = null;
    String newCity = null;
    String newCountry = null;
    String newState = null;
    String newPostalCode = null;
    String newLender = null;
    String newLoanType = null;
    Date newPurchaseDate = null;
    Double newPurchaseAmount = null;

    String addressType = null;
    
    // Loop through Leads and create Address objects when address fields have been updated
    for (Lead lead : leadsWithAddresses) {

        // Skip converted leads
        if (newLeadMap.get(lead.id).IsConverted) continue;

        // Mark any Address object that is now a primary field value for deletion
        for (Address_SFDC2__c address : lead.Addresses__r) {
            if (address.Street__c == newLeadMap.get(lead.id).Street && address.City__c == newLeadMap.get(lead.id).City && address.Postal_Code__c == newLeadMap.get(lead.id).PostalCode
                && address.Mortgage_Lender__c == newLeadMap.get(lead.id).Primary_Mortgage_Lender_SFDC2__c && address.Loan_Type__c == newLeadMap.get(lead.id).Primary_Loan_Type_SFDC2__c
                && address.Purchase_Date__c == newLeadMap.get(lead.id).Primary_Purchase_Date_SFDC2__c && address.Purchase_Amount__c == newLeadMap.get(lead.id).Primary_Purchase_Amount_SFDC2__c) {
                    addressesToDelete.add(address); 
                    continue;
            }               
        }

        // Search each address field for changes
        for (Integer i = 0; i<1; i++) {
            if (i==0) {
                currStreet          = oldLeadMap.get(lead.id).Street; 
                currCity            = oldLeadMap.get(lead.id).City; 
                currCountry         = oldLeadMap.get(lead.id).Country; 
                currState           = oldLeadMap.get(lead.id).State; 
                currPostalCode      = oldLeadMap.get(lead.id).PostalCode; 
                currLender          = oldLeadMap.get(lead.id).Primary_Mortgage_Lender_SFDC2__c;
                currLoanType        = oldLeadMap.get(lead.id).Primary_Loan_Type_SFDC2__c;
                currPurchaseDate    = oldLeadMap.get(lead.id).Primary_Purchase_Date_SFDC2__c;
                currPurchaseAmount  = oldLeadMap.get(lead.id).Primary_Purchase_Amount_SFDC2__c;
                newStreet           = newLeadMap.get(lead.id).Street; 
                newCity             = newLeadMap.get(lead.id).City; 
                newCountry          = newLeadMap.get(lead.id).Country; 
                newState            = newLeadMap.get(lead.id).State; 
                newPostalCode       = newLeadMap.get(lead.id).PostalCode; 
                newLender           = newLeadMap.get(lead.id).Primary_Mortgage_Lender_SFDC2__c;
                newLoanType         = newLeadMap.get(lead.id).Primary_Loan_Type_SFDC2__c;
                newPurchaseDate     = newLeadMap.get(lead.id).Primary_Purchase_Date_SFDC2__c;
                newPurchaseAmount   = newLeadMap.get(lead.id).Primary_Purchase_Amount_SFDC2__c;
                addressType = 'Other';
            }

            // Find address field values that have changed
            if ((currStreet != newStreet && currStreet != null && currStreet != '')
                || (currCity != newCity && currCity != null && currCity != '')
                || (currPostalCode != newPostalCode && currPostalCode != null && currPostalCode != '')) {

                // Make sure a Address object does not already exist for this address
                foundRecord = false;
                for (Address_SFDC2__c address : lead.Addresses__r) {
                    if (address.Street__c == currStreet && address.City__c == currCity && address.Postal_Code__c == currPostalCode
                        && address.Mortgage_Lender__c == currLender && address.Loan_Type__c == currLoanType
                        && address.Purchase_Date__c == currPurchaseDate && address.Purchase_Amount__c == currPurchaseAmount) foundRecord = true;
                }

                // Do not add an Address object if a different Account address fields have the original address value
                if (currStreet == newLeadMap.get(lead.id).Street && currCity == newLeadMap.get(lead.id).City && currPostalCode == newLeadMap.get(lead.id).PostalCode
                    && currLender == newLeadMap.get(lead.id).Primary_Mortgage_Lender_SFDC2__c && currLoanType == newLeadMap.get(lead.id).Primary_Loan_Type_SFDC2__c
                    && currPurchaseDate == newLeadMap.get(lead.id).Primary_Purchase_Date_SFDC2__c && currPurchaseAmount == newLeadMap.get(lead.id).Primary_Purchase_Amount_SFDC2__c) foundRecord = true;

                // Create new Address objects as necessary
                if (!foundRecord) {
                    Address_SFDC2__c address = new Address_SFDC2__c();
                    address.Lead__c = lead.Id;
                    address.Street__c = currStreet;
                    address.City__c = currCity;
                    address.Country__c = currCountry;
                    address.State__c = currState;
                    address.Postal_Code__c = currPostalCode;
                    address.Loan_Type__c = currLoanType;
                    address.Mortgage_Lender__c = currLender;
                    address.Purchase_Date__c = currPurchaseDate;
                    address.Purchase_Amount__c = currPurchaseAmount;
                    address.Address_Type__c = addressType;
                    addressesToInsert.add(address);
                }
            }   
        }
    }
    
    insert addressesToInsert;
    delete addressesToDelete;
    
  }
  
  /**
   * Handle custom field updates and updating Account lookups on custom objects after Lead conversion
   * @param oldAcctMap map of original state Accounts
   * @param newAcctMap map of changed Accounts
   */
  private void handleLeadConversion(Map<Id,Lead> oldLeadMap, Map<Id,Lead> newLeadMap) {
    
    // Get converted Leads in SFDC2 with associated custom objects
    List<Lead> newLeads = [select id, Street, City, Country,Email, State, PostalCode, Primary_Loan_Type_SFDC2__c, Primary_Mortgage_Lender_SFDC2__c, 
                                Primary_Purchase_Amount_SFDC2__c, Primary_Purchase_Date_SFDC2__c, Corporation_Type_HBD__c, Other_Corporation__c,
                                convertedAccountId, convertedContactId, convertedOpportunityId, Date_of_Birth__c, LeadSource, Opportunity_NameSFDC2__c,
                                (select id, Account__c from Phones__r where Lead__c IN :newLeadMap.keySet() and Account__c = null), 
                                (select id, Account__c from Email_Addresses__r where Lead__c IN :newLeadMap.keySet() and Account__c = null), 
                                (select id, Account__c from Addresses__r where Lead__c IN :newLeadMap.keySet() and Account__c = null) 
                            from Lead where id IN :newLeadMap.keySet() and SFDC2__c = true and IsConverted = true];

    // Assemble converted id sets
    Set<Id> convertedAccountIds = new Set<Id>();
    Set<Id> convertedContactIds = new Set<Id>();
    Set<Id> convertedOpportunityIds = new Set<Id>();
    
    for (Lead lead: newLeads) {
        if (lead.convertedAccountId != null) convertedAccountIds.add(lead.convertedAccountId);
        if (lead.convertedContactId != null) convertedContactIds.add(lead.convertedContactId);
        if (lead.convertedOpportunityId != null) convertedOpportunityIds.add(lead.convertedOpportunityId);
    }
    
    // Get records associated with converted ids
    List<Account> accounts = [select Id, RecordTypeId, PersonMailingStreet, PersonMailingCity, PersonMailingCountry, PersonMailingState, PersonMailingPostalCode,
                                Mailing_Loan_Type_SFDC2__pc, Mailing_Mortgage_Lender_SFDC2__pc, Mailing_Purchase_Amount_SFDC2__pc, 
                                Mailing_Purchase_Date_SFDC2__pc, Email__c, BillingStreet, BillingCity, BillingCountry, BillingState, BillingPostalCode,
                                Billing_Loan_Type_SFDC2__c, Billing_Mortgage_Lender_SFDC2__c, Billing_Purchase_Amount_SFDC2__c, Billing_Purchase_Date_SFDC2__c,
                                Corporation_Type__c, Other_Corporation__c, 
                                isPersonAccount, PersonBirthdate, AccountSource from Account where Id IN :convertedAccountIds];
    Map<Id, Account> accountMap = new Map<Id, Account>(accounts);
    
    List<Contact> contacts = [select Id, RecordTypeId, Birthdate from Contact where Id IN :convertedContactIds];
    Map<Id, Contact> contactMap = new Map<Id, Contact>(contacts);
    
    //List<Opportunity> opportunities = [select Id, RecordTypeId from Opportunity where Id IN :convertedOpportunityIds];
    //Map<Id, Opportunity> opportunityMap = New Map<Id, Opportunity>(opportunities);
    
    List<Account> accountsToUpdate = new List<Account>();
    List<Contact> contactsToUpdate = new List<Contact>();
    List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
    List<Phone_SFDC2__c> phonesToUpdate = new List<Phone_SFDC2__c>();
    List<Email_SFDC2__c> emailsToUpdate = new List<Email_SFDC2__c>();
    List<Address_SFDC2__c> addrsToUpdate = new List<Address_SFDC2__c>();
    
    // Get record types for Accounts and Contacts
    Id businessAccountRtId =    Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account SFDC2').getRecordTypeId();
    Id personAccountRtId =      Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer Person Account SFDC2').getRecordTypeId();
    RecordType contactRT =      [select id from RecordType where Name = 'Business SFDC2' and SObjectType = 'Contact'];
    
    // Loop through updated Leads, find those that whose conversion triggered this update, and set RecordTypes and Lookup values on related records
    for (Lead lead : newLeads) {
             
        // Find newly converted Leads
        if (oldLeadMap.get(lead.id).IsConverted == false) {
        
            // Update Account lookup for Phone objects
            for (Phone_SFDC2__c phone : lead.Phones__r) {
                phone.Account__c = lead.ConvertedAccountId;
                phonesToUpdate.add(phone);
            }

            // Update Account lookup for Email objects              
            for (Email_SFDC2__c email : lead.Email_Addresses__r) {
                email.Account__c = lead.ConvertedAccountId;
                emailsToUpdate.add(email);
            }
            
            // Update Account lookup for Address objects
            for (Address_SFDC2__c addr : lead.Addresses__r) {
                addr.Account__c = lead.ConvertedAccountId;
                addrsToUpdate.add(addr);
            }
            
            // Set Account fields and record type
            Account account = accountMap.get(lead.convertedAccountId);
            if (account.IsPersonAccount) {
                account.RecordTypeId = personAccountRtId;
                account.PersonMailingStreet     = lead.Street;
                account.PersonMailingCity       = lead.City;
                account.PersonMailingState      = lead.State;
                account.PersonMailingCountry    = lead.Country;
                account.PersonMailingPostalCode = lead.PostalCode;
                account.Mailing_Loan_Type_SFDC2__pc         = lead.Primary_Loan_Type_SFDC2__c;
                account.Mailing_Mortgage_Lender_SFDC2__pc   = lead.Primary_Mortgage_Lender_SFDC2__c;
                account.Mailing_Purchase_Amount_SFDC2__pc   = lead.Primary_Purchase_Amount_SFDC2__c;
                account.Mailing_Purchase_Date_SFDC2__pc     = lead.Primary_Purchase_Date_SFDC2__c;
                account.PersonBirthdate         = lead.Date_of_Birth__c;
                account.AccountSource           = lead.LeadSource;  
            } else {
                account.RecordTypeId = businessAccountRtId;
                account.Email__c                = lead.Email;
                account.BillingStreet           = lead.Street;
                account.BillingCity             = lead.City;
                account.BillingState            = lead.State;
                account.BillingCountry          = lead.Country;
                account.BillingPostalCode       = lead.PostalCode;
                account.Billing_Loan_Type_SFDC2__c          = lead.Primary_Loan_Type_SFDC2__c;
                account.Billing_Mortgage_Lender_SFDC2__c    = lead.Primary_Mortgage_Lender_SFDC2__c;
                account.Billing_Purchase_Amount_SFDC2__c    = lead.Primary_Purchase_Amount_SFDC2__c;
                account.Billing_Purchase_Date_SFDC2__c      = lead.Primary_Purchase_Date_SFDC2__c;  
                account.AccountSource           = lead.LeadSource;
                account.Corporation_Type__c               = lead.Corporation_Type_HBD__c;
                account.Other_Corporation__c              = lead.Other_Corporation__c;                
            }
            accountsToUpdate.add(account);
            
            // Set Contact record type
            Contact contact = contactMap.get(lead.convertedContactId);
            contact.RecordType = contactRT;
            contactsToUpdate.add(contact);
            
        }
        
    }
    
    // Update objects as necessary
    if (accountsToUpdate.size() > 0) update accountsToUpdate;
    if (contactsToUpdate.size() > 0) update contactsToUpdate;
    if (opportunitiesToUpdate.size() > 0) update opportunitiesToUpdate;
    if (phonesToUpdate.size() > 0) update phonesToUpdate;
    if (emailsToUpdate.size() > 0) update emailsToUpdate;
    if (addrsToUpdate.size() > 0) update addrsToUpdate;
        
  }

  /**
   * Update SFDC2 checkbox based on Lead record type
   * @param newLeads list of updated or inserted Leads
   */
    /**
   * Update SFDC2 checkbox based on Lead record type
   * @param newLeads list of updated or inserted Leads
   */
    private void updateSFDC2Checkbox(List<Lead> newLeads) {
        
        Set<Id> sfdc2Ids = new set<Id>();
        for (Manager_SFDC2__mdt rtName : [Select RecordType_Name__c from Manager_SFDC2__mdt where isLeadRT_SFDC2__c = true]){       
            sfdc2Ids.add(Schema.SObjectType.Lead.getRecordTypeInfosByName().get(rtName.RecordType_Name__c).getRecordTypeId()); 
        }
        for(Lead lead: newLeads) {
            //Sync with Marketo field Update
            
            if( sfdc2Ids.contains(lead.RecordTypeId))  { 
                lead.SFDC2__c = true; 
                if(lead.Email != Null && !lead.HasOptedOutOfEmail   )lead.Sync_with_Marketo__c = true;
            }
            else  lead.SFDC2__c = false;
        }
    } 
}