objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current Physical</fullName>
                </value>
                <value>
                    <fullName>Current Mailing</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Add-{00}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddressTriggerHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AddressTriggerHandler_Test {

  /**
  * Tests the handleCurrentAddress method that is triggered in the afterInsert and afterUpdate for Address object
  */
  @isTest
  static void testHandleCurrentAddress() {
  	Account a = TestDataFactory.createAndInsertTestPersonAccount();
  	
  	Address__c add1 = new Address__c(Account_Name__c=a.Id,Address_Line__c='123 Elm St',City__c='San Diego',State__c='CA',Zip__c='92122',Status__c=AddressTriggerHandler.STATUS_CURRENTADDRESS);
  	Address__c add2 = new Address__c(Account_Name__c=a.Id,Address_Line__c='987 Pine Ave',City__c='Washington',State__c='DC',Zip__c='20012',Status__c=AddressTriggerHandler.STATUS_FORMERADDRESS);
  	Address__c[] add = new Address__c[]{add1,add2};
  	insert add;
  	test.startTest();
  	a = [SELECT PersonMailingStreet, PersonMailingCity, PersonMailingState, PersonMailingPostalCode FROM Account where Id = :a.Id];
  	System.assertEquals('123 Elm St', a.PersonMailingStreet);
  	System.assertEquals('San Diego', a.PersonMailingCity);
  	System.assertEquals('CA', a.PersonMailingState);
  	System.assertEquals('92122', a.PersonMailingPostalCode);
  	add[1].Status__c = AddressTriggerHandler.STATUS_CURRENTADDRESS;
  	update add;
  	test.stopTest();
  	a = [SELECT PersonMailingStreet, PersonMailingCity, PersonMailingState, PersonMailingPostalCode FROM Account where Id = :a.Id];
  	System.assertEquals('987 Pine Ave', a.PersonMailingStreet);
  	System.assertEquals('Washington', a.PersonMailingCity);
  	System.assertEquals('DC', a.PersonMailingState);
  	System.assertEquals('20012', a.PersonMailingPostalCode);
  	for(Address__c address : [SELECT Status__c FROM Address__c WHERE Id in :add]) {
  	  if(address.Id == add[0].Id) {
  	  	System.assertEquals(AddressTriggerHandler.STATUS_FORMERADDRESS, address.Status__c);
  	  } else if (address.Id == add[1].Id) {
  	  	System.assertEquals(AddressTriggerHandler.STATUS_CURRENTADDRESS, address.Status__c);
  	  }
  	}
  }
}