objects/Address_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Address objects are used to allow storing an unlimited number of current and historical addresses for Leads, Business Accounts and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>JH Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Lender__c</fullName>
        <label>Mortgage Lender</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <inlineHelpText>Please enter a five digit zip code, or a zip +4 code in the following format: #####-####</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AddressSfdc2TriggerHandler.cls
/**
 * @description <P>Handler class for Address_SFDC2__c object functionality
 * @author Matt Dawson, BofI Federal
 */
public class AddressSfdc2TriggerHandler extends TriggerHandler {
    
    /** Map of new/updated Address_SFDC2__c objects with changes */
    private Map<Id, Address_SFDC2__c> newAddrMap;
	
	/** Map of updated/deleted Address_SFDC2__c objects without changes */
    private Map<Id, Address_SFDC2__c> oldAddrMap;

	/** List of new/updated Address_SFDC2__c objects with changes */
    private List<Address_SFDC2__c> newAddrList;
    
    /** Profile Id for System Admins **/
    private static Id adminProfileId = '00ei0000000qJ9OAAU';
        
    /** Constructor */
    public AddressSfdc2TriggerHandler() {
    	this.newAddrMap = (Map<Id, Address_SFDC2__c>) Trigger.newMap;
		this.oldAddrMap = (Map<Id, Address_SFDC2__c>) Trigger.oldMap;
    	this.newAddrList = (List<Address_SFDC2__c>) Trigger.new;
    }
    
    /** Process after insert logic */
    public override void afterInsert() {
    	updatePrimaryAddresses(this.newAddrMap);
    }
    
    /** Process after update logic */
    public override void afterUpdate() {
    	updatePrimaryAddresses(this.newAddrMap);
    }
    
    /** Process before insert logic */
    public override void beforeInsert() {
    	blockJhAddressInserts();
    }

	/** Process before update logic */
	public override void beforeUpdate() {
		blockJhAddressChanges();
    	blockJhAddressInserts();
	}

	/** Process before delete logic */
	public override void beforeDelete() {
		blockJhAddressChanges();
	}
    
    /**
     * Block changes to a JH Address record
     */
    private void blockJhAddressChanges() {
    	for (Address_SFDC2__c addr : this.oldAddrMap.values()) {
    		if (addr.Address_Type__c == null) continue;
    		if (addr.Address_Type__c.equals('JH Address') && UserInfo.getProfileId() != adminProfileId) {
    			if (Trigger.isDelete) {
   					addr.addError('JH Address objects cannot be changed or deleted.');
    			} else {
   					this.newAddrMap.get(addr.Id).addError('JH Address objects cannot be changed or deleted.');
    			}
    		}
    	}
    }
    
    /**
     * Block inserts of JH Address records
     */
    private void blockJhAddressInserts() {
    	for (Address_SFDC2__c addr : this.newAddrList) {
    		if (addr.Address_Type__c == null) continue;
    		if (addr.Address_Type__c.equals('JH Address') && UserInfo.getProfileId() != adminProfileId) {
    			addr.addError('JH Address objects cannot created manually.');
    		}
    	}
    }

    /**
     * Check Address_SFDC2__c objects for 'Primary' type and update master record
     * primary address fields.
     * @param newAddrMap map of new/updated address objects
     */
    private void updatePrimaryAddresses(Map<Id, Address_SFDC2__c> newAddrMap) {
    	
     	// List of Addresses with Account and Lead ids
        List<Address_SFDC2__c> addresses = [select Account__r.Id, Lead__r.Id from Address_SFDC2__c where id IN :newAddrMap.keySet()];

        // List of Account Ids associated with addresses
		List<Id> accountIds = new List<Id>();
		for (Address_SFDC2__c address: addresses) accountIds.add(address.Account__r.Id);
        
        // List of Accounts to update
    	List<Account> accountsToUpdate = new List<Account>();
     	
    	// Set appropriate Account primary email field values
    	for (Account account : [select id, PersonMailingStreet, PersonMailingCity, PersonMailingCountry, PersonMailingState, PersonMailingPostalCode,
  										Mailing_Loan_Type_SFDC2__pc, Mailing_Mortgage_Lender_SFDC2__pc, Mailing_Purchase_Amount_SFDC2__pc, Mailing_Purchase_Date_SFDC2__pc,
  										BillingStreet, BillingCity, BillingCountry, BillingState, BillingPostalCode, Billing_Loan_Type_SFDC2__c, 
  										Billing_Mortgage_Lender_SFDC2__c, Billing_Purchase_Amount_SFDC2__c, Billing_Purchase_Date_SFDC2__c, isPersonAccount,
							    	(select id, Street__c, City__c, Country__c, State__c, Postal_Code__c, Address_Type__c, Mortgage_Lender__c, Loan_Type__c, 
							    		Purchase_Date__c, Purchase_Amount__c from Addresses__r where id IN :newAddrMap.keySet())
  									 from Account where SFDC2__c = true and id IN :accountIds ]) {
			Boolean updateAccount = false;
			for (Address_SFDC2__c addr : account.Addresses__r) {
				if (addr.Address_Type__c.equals('Primary')) {
					if (account.isPersonAccount) {
						account.PersonMailingStreet 			  = addr.Street__c;
						account.PersonMailingCity	 			  = addr.City__c;
						account.PersonMailingCountry 			  = addr.Country__c;
						account.PersonMailingState 				  = addr.State__c;
						account.PersonMailingPostalCode 		  = addr.Postal_Code__c;
						account.Mailing_Mortgage_Lender_SFDC2__pc = addr.Mortgage_Lender__c;
						account.Mailing_Loan_Type_SFDC2__pc 	  = addr.Loan_Type__c;
						account.Mailing_Purchase_Date_SFDC2__pc   = addr.Purchase_Date__c;
						account.Mailing_Purchase_Amount_SFDC2__pc = addr.Purchase_Amount__c;
						updateAccount = true;
					} else {
						account.BillingStreet 			 		 = addr.Street__c;
						account.BillingCity	 			 		 = addr.City__c;
						account.BillingCountry 			 		 = addr.Country__c;
						account.BillingState 				 	 = addr.State__c;
						account.BillingPostalCode 		 		 = addr.Postal_Code__c;
						account.Billing_Mortgage_Lender_SFDC2__c = addr.Mortgage_Lender__c;
						account.Billing_Loan_Type_SFDC2__c 		 = addr.Loan_Type__c;
						account.Billing_Purchase_Date_SFDC2__c 	 = addr.Purchase_Date__c;
						account.Billing_Purchase_Amount_SFDC2__c = addr.Purchase_Amount__c;		
						updateAccount = true;				
					}
				} 
			}
			if (updateAccount) accountsToUpdate.add(account);
    	}
    	
    	update accountsToUpdate;

    	// List of Lead Ids associated with email addresses
    	List<Id> leadIds = new List<Id>();
    	for (Address_SFDC2__c address: addresses) leadIds.add(address.Lead__r.Id);
    	
    	// List of Leads to update
    	List<Lead> leadsToUpdate = new List<Lead>();

    	// Set appropriate Lead primary email field values
    	for (Lead lead : [select id, Street, City, Country, State, PostalCode, Primary_Loan_Type_SFDC2__c, Primary_Mortgage_Lender_SFDC2__c, 
    						Primary_Purchase_Amount_SFDC2__c, Primary_Purchase_Date_SFDC2__c,
							(select id, Street__c, City__c, Country__c, State__c, Postal_Code__c, Address_Type__c, Mortgage_Lender__c, Loan_Type__c, 
							    Purchase_Date__c, Purchase_Amount__c from Addresses__r where id IN :newAddrMap.keySet())
  							from Lead where SFDC2__c = true and IsConverted = false and id IN :leadIds ]) {
			Boolean updateAddress = false;
			for (Address_SFDC2__c addr : lead.Addresses__r) {
				if (addr.Address_Type__c.equals('Primary')) {
					lead.Street 			  				= addr.Street__c;
					lead.City	 			  				= addr.City__c;
					lead.Country 			  				= addr.Country__c;
					lead.State 				  				= addr.State__c;
					lead.PostalCode 		  				= addr.Postal_Code__c;
					lead.Primary_Mortgage_Lender_SFDC2__c 	= addr.Mortgage_Lender__c;
					lead.Primary_Loan_Type_SFDC2__c 	  	= addr.Loan_Type__c;
					lead.Primary_Purchase_Date_SFDC2__c   	= addr.Purchase_Date__c;
					lead.Primary_Purchase_Amount_SFDC2__c 	= addr.Purchase_Amount__c;
					updateAddress = true;
				} 
			}
			if (updateAddress) leadsToUpdate.add(lead);
    	}
    	
    	update leadsToUpdate;

    }    
    
    
}