objects/Amendment__c.object
<CustomObject>
    <description>Used by C&amp;I to record loan amendments</description>
    <fields>
        <fullName>Additional_Fees__c</fullName>
        <label>Additional Fee(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Intended to be hidden field that is set during approval process and displayed in related lists/reports</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <label>Collateral</label>
        <length>750</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Extension_Options__c</fullName>
        <label>Extension Option(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Guarantor_Types__c</fullName>
        <label>Guarantor Type(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Guarantors__c</fullName>
        <label>Guarantor(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Structure__c</fullName>
        <label>Loan Structure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Multi Draw Term</fullName>
                </value>
                <value>
                    <fullName>Revolving</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The parent Opportunity must be in a Closed Won stage before an Amendment can be created</errorMessage>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>Closed Won</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Amendments</relationshipLabel>
        <relationshipName>Amendments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <type>TextArea</type>
    </fields>
    <label>Amendment</label>
    <nameField>
        <displayFormat>AMEND-{YYYYMMDD}-{000}</displayFormat>
        <label>Amendment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AmendmentTriggerHandler.cls
/**
* @description <p>Handler class for AmendmentTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public with sharing class AmendmentTriggerHandler extends TriggerHandler {
  /** Map of Amendments before changes */
  private Map<Id, Amendment__c> oldAmendMap;
  /** Map of Amendments with changes */
  private Map<Id, Amendment__c> newAmendMap;
  
  /** Constructor */
  public AmendmentTriggerHandler() {
  	this.oldAmendMap = (Map<Id, Amendment__c>) Trigger.oldMap;
  	this.newAmendMap = (Map<Id, Amendment__c>) Trigger.newMap;
  }
  
  /**
  * Process afterUpdate logic
  */
  public override void afterUpdate() {
  	updateOppModSummaryFields(this.oldAmendMap, this.newAmendMap);
  }
  
  /**
  * When Amendments are approved, update respective fields in Modification Summary on parent Opportunity
  * @param oldAmendMap map of initial state Amendments
  * @param newAmendMap map of changed Amendments
  */
  private void updateOppModSummaryFields(Map<Id, Amendment__c> oldMap, Map<Id, Amendment__c> newMap) {
  	for(Amendment__c amend : newMap.values()) {
  		Amendment__c oldAmend = oldMap.get(amend.Id);
  		if(amend.Approval_Status__c == 'Approved' && oldAmend.Approval_Status__c != 'Approved') {
  			Opportunity opp = new Opportunity(Id=amend.Opportunity__c);
  			opp.CI_Additional_Fees_Amend__c = amend.Additional_Fees__c;
  			opp.CI_Extension_Options_Amend__c = amend.Extension_Options__c;
  			opp.CI_Guarantor_Types_Amend__c = amend.Guarantor_Types__c;
  			opp.CI_Guarantors_Amend__c = amend.Guarantors__c;
  			opp.CI_Loan_Amount_Amend__c = amend.Loan_Amount__c;
  			opp.CI_Loan_Structure_Amend__c = amend.Loan_Structure__c;
  			opp.CI_Other_Amend__c = amend.Other__c;
  			opp.CI_Rate_Amend__c = amend.Rate__c;
  			opp.CI_Term_Amend__c = amend.Term__c;
  			opp.CI_Collateral_Amend__c = amend.Collateral__c;
  			toUpdate.add(opp);
  		}
  	}
  }
}