objects/Applicant_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Used to capture Applicant data from external systems</description>
    <fields>
        <fullName>Application_Id__c</fullName>
        <description>Application associated with Applicant</description>
        <label>Application Id</label>
        <referenceTo>Application_SFDC2__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>Application_Id__r.Application_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <description>Mobile phone</description>
        <label>Cell Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Primary email</description>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant-{0000000}</displayFormat>
        <label>Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <recordTypes>
        <fullName>Enrollment</fullName>
        <active>true</active>
        <description>Applicants received from the Enrollment system</description>
        <label>Enrollment</label>
    </recordTypes>
    <recordTypes>
        <fullName>TCI</fullName>
        <active>true</active>
        <description>Applicants received from the TCI system</description>
        <label>TCI</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Application_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Used to capture Application data from external systems</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Status of Application</description>
        <label>Application Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_id__c</fullName>
        <description>Unique identifier for application</description>
        <externalId>true</externalId>
        <label>Application Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Enrollment</fullName>
        <active>true</active>
        <description>Applications received from the Enrollment system</description>
        <label>Enrollment</label>
    </recordTypes>
    <recordTypes>
        <fullName>TCI</fullName>
        <active>true</active>
        <description>Applications received from the TCI system</description>
        <label>TCI</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApplicantTriggerHandler_test.cls
@isTest
private class ApplicantTriggerHandler_test {
    
    @testSetUp 
    static void testSetup() {
        Database.insert(new campaign(Name = 'Incomplete Application'));
        Database.insert(new campaign(Name = 'Abandoned Enrollment Opps'));
        Id partId = [select Id from RecordType where DeveloperName = 'Business_Consumer_Person_Account'].Id;
        Id lrtId = [select Id from RecordType where DeveloperName = 'Dealer_Services_Applicant_SFDC2' and SObjectType = 'Lead'].Id;
       
        Account a = new Account(
            FirstName = 'Test',
            LastName = 'Account',
            PersonHomePhone = '(123) 123-1234',
            PersonMobilePhone =  '(678) 678-6789',
            PersonEmail = 'test.contact@test.com',
            RecordTypeId = partId
        );

        insert a;

        Account a2 = new Account(
                FirstName = 'Test Enrollment',
                LastName = 'Account',
                PersonHomePhone = '(123) 123-1234',
                PersonMobilePhone =  '(678) 678-6789',
                PersonEmail = 'test.contact@test.com',
                RecordTypeId = partId
            );

        insert a2;

        Account a3 = new Account(
                FirstName = 'Test Enrollment 2',
                LastName = 'Account',
                PersonHomePhone = '(123) 123-1234',
                PersonMobilePhone =  '(678) 678-6789',
                PersonEmail = 'test.contact@test.com',
                RecordTypeId = partId
            );

        insert a3;

    }

    @isTest
    static void testProcessTCIApplicationForPersonAccount() {
        Test.startTest();
            Id tciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Applicant_SFDC2__c'].Id;
            Id apptciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Application_SFDC2__c'].Id;
            Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test Application',
                Application_Status__c = 'Pending',
                RecordTypeId = apptciRTId
            );
            insert app;
            Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'Test',
                Last_Name__c = 'Account',
                Email__c = 'test.contact@test.com',
                RecordTypeId =  tciRTId
            );
            insert applnt;
        Test.stopTest();
    }

    @isTest
    static void testProcessTCIApplicationForPersonAccount2() {
        Test.startTest();
            Id tciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Applicant_SFDC2__c'].Id;
            Id apptciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Application_SFDC2__c'].Id;
            Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test Application',
                Application_Status__c = 'Approved',
                RecordTypeId = apptciRTId
            );
            insert app;
            Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'Test',
                Last_Name__c = 'Account',
                Email__c = '',
                Cell_Phone__c = '(678) 678-6789',
                RecordTypeId =  tciRTId
            );
            insert applnt;
        Test.stopTest();
    }

    @isTest
    static void testProcessTCIApplicationForPersonAccount3() {
        Test.startTest();
            Id tciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Applicant_SFDC2__c'].Id;
            Id apptciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Application_SFDC2__c'].Id;
            Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test Application',
                Application_Status__c = 'Counter Offer',
                RecordTypeId = apptciRTId
            );
            insert app;
            Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'Test',
                Last_Name__c = 'Account',
                Email__c = '',
                Cell_Phone__c = '(678) 678-6789',
                RecordTypeId =  tciRTId
            );
            insert applnt;
        Test.stopTest();
    }
    
    @isTest
    static void testProcessTCIApplicationForCreateLead() {
        Test.startTest();
            Id tciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Applicant_SFDC2__c'].Id;
            Id apptciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Application_SFDC2__c'].Id;
            Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test Application',
                Application_Status__c = 'Pending',
                RecordTypeId = apptciRTId
            );
            insert app;
            Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'New',
                Last_Name__c = 'Lead',
                Email__c = 'new.lead@test.com',
                RecordTypeId =  tciRTId
            );
            insert applnt;
        Test.stopTest();
    }

    @isTest
    static void testProcessTCIApplicationForLeadConversion() {
        Test.startTest();
        Id tciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Applicant_SFDC2__c'].Id;
        Id apptciRTId = [select Id from RecordType where DeveloperName = 'TCI' and SObjectType = 'Application_SFDC2__c'].Id;

        Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test Application Lead Conversion',
                Application_Status__c = 'Approved',
                RecordTypeId = apptciRTId
            );

        insert app;

        Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'Test 3',
                Last_Name__c = 'Lead 3',
                Email__c = 'test.lead@test.com',
                RecordTypeId =  tciRTId
            );

        insert applnt;
        Test.stopTest();
    }

}