objects/Applicant_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Used to capture Applicant data from external systems</description>
    <fields>
        <fullName>Application_Id__c</fullName>
        <description>Application associated with Applicant</description>
        <label>Application Id</label>
        <referenceTo>Application_SFDC2__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>Application_Id__r.Application_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Primary email</description>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>Applicant-{0000000}</displayFormat>
        <label>Applicant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <recordTypes>
        <fullName>TCI</fullName>
        <active>true</active>
        <description>Applicants received from the TCI system</description>
        <label>TCI</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Application_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Used to capture Application data from external systems</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Status of Application</description>
        <label>Application Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_id__c</fullName>
        <description>Unique identifier for application</description>
        <externalId>true</externalId>
        <label>Application Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>TCI</fullName>
        <active>true</active>
        <description>Applications received from the TCI system</description>
        <label>TCI</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApplicationTriggerHandler_Test.cls
@isTest
private class ApplicationTriggerHandler_Test {

   @TestSetUp static void initData(){
        Database.insert(new campaign(Name = 'Incomplete Application'));
        Map<String,RecordType> mapApplcntRTsByDevName = UtilsSFDC2.getRecordTypesMap('Applicant_SFDC2__c','DeveloperName');
        Map<String,RecordType> mapAppsRTsByDevName = UtilsSFDC2.getRecordTypesMap('Application_SFDC2__c','DeveloperName');
        Application_SFDC2__c app = new Application_SFDC2__c(
                Name = 'Test TCI Application',
                Application_Status__c = 'Pending',
                RecordTypeId = mapAppsRTsByDevName.get('TCI').Id
            );
        insert app;
        Applicant_SFDC2__c applnt = new Applicant_SFDC2__c(
                Application_Id__c = app.Id,
                First_Name__c = 'Test',
                Last_Name__c = 'TCI',
                Email__c = 'test.contacttci@test.com',
                RecordTypeId =  mapApplcntRTsByDevName.get('TCI').Id
            ); 
        insert applnt;
    }

    @isTest
    static void updateTCIRecord() {
        List<Application_SFDC2__c> updApp = new List<Application_SFDC2__c>();
        Test.startTest();
            for(Application_SFDC2__c a : [select Id, Application_Status__c from Application_SFDC2__c where Name = 'Test TCI Application' limit 1]) {
                a.Application_Status__c = 'Approved';
                updApp.add(a);
            }
            if(!updApp.isEmpty()) {
                update updApp;
            }
        Test.stopTest();
        System.assertEquals('Approved', updApp[0].Application_Status__c);
    }

}