objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/APXTConga4__Conga_Template__c.object
<CustomObject>
    <description>Template manager for use with Conga Composer and Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APXTConga4__Template_Type__c</fullName>
        <label>Template Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Document</fullName>
                    <default>true</default>
                    <label>Document</label>
                </value>
                <value>
                    <fullName>Label</fullName>
                </value>
                <value>
                    <fullName>Envelope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Conga Template</label>
    <nameField>
        <displayFormat>CMT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>BF_Status__c</fullName>
        <label>BF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BF In Progress</fullName>
                    <default>true</default>
                    <label>BF In Progress</label>
                </value>
                <value>
                    <fullName>BF Submitted for Pre-Approval</fullName>
                </value>
                <value>
                    <fullName>BF Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>BF Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>BF Approved</fullName>
                </value>
                <value>
                    <fullName>BF Rejected</fullName>
                </value>
                <value>
                    <fullName>BF Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used to provide ability to display BF on Opportunity page layout easily through related list.</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Boarding Forms</relationshipLabel>
        <relationshipName>Boarding_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Related_LOQ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the Loan Ops Questionaire record Name which is an auto number.</description>
        <label>Related LOQ</label>
        <referenceTo>Loan_Ops_Questionnaire__c</referenceTo>
        <relationshipLabel>Boarding Form</relationshipLabel>
        <relationshipName>Boarding_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>Boarding_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boarding Form</label>
        <referenceTo>Boarding_Form__c</referenceTo>
        <relationshipLabel>Loan Ops Questionnaires</relationshipLabel>
        <relationshipName>Loan_Ops_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>contains</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF, IPL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Ops Questionnaires</relationshipLabel>
        <relationshipName>Loan_Ops_Questionnaires</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BF_Conga_Doc_Generate_SFDC2_Test.cls
@isTest
public class BF_Conga_Doc_Generate_SFDC2_Test {
    
    static testmethod void generateDocTest(){
        
               Id recordTypeId = Schema.SObjectType.Boarding_Form__c.getRecordTypeInfosByName().get('Pre LOQ Approval').getRecordTypeId();
               Id opprecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRESL SFDC2').getRecordTypeId();
        Account acc = new Account(Name='test');
        insert acc;
       
       Opportunity opp = new Opportunity(
            StageName = '1 - New',
            CloseDate = Date.today(),
            AccountId = acc.Id,
           RecordTypeId = opprecordTypeId,
            Name = 'Test Opportunity Triggers'
            
        );
        insert opp;
        APXTConga4__Conga_Merge_Query__c ccq = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'C&I SFDC2: Guarantors to BF');

        APXTConga4__Conga_Merge_Query__c ccq1 = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'C&I SFDC2: Borrowers to BF');
        APXTConga4__Conga_Template__c    cct =  new APXTConga4__Conga_Template__c ( APXTConga4__Name__c  = 'C&I Boarding Form Lightning', APXTConga4__Template_Type__c = 'Document');
        insert ccq;
        insert ccq1;
        insert cct;
        system.debug('ccq' +ccq.Id);
        Loan_Ops_Questionnaire__c LOQFrm = new Loan_Ops_Questionnaire__c(Opportunity__c = opp.Id);
        insert LOQFrm;
        Boarding_Form__c brdFrm = new Boarding_Form__c(Opportunity__c = opp.Id, RecordTypeId = recordTypeId, BF_Status__c = 'BF Approved', Related_LOQ__c = LOQFrm.Id);

        insert brdFrm;      
        Test.startTest();
        BF_Conga_Doc_Generate_SFDC2.generateDocument(String.valueOf(brdFrm.Id));
        Test.stopTest();
    }
}