objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>LOQ_Status__c</fullName>
        <description>Change in field values is controlled by approval process</description>
        <label>LOQ Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LOQ In Progress</fullName>
                    <default>true</default>
                    <label>LOQ In Progress</label>
                </value>
                <value>
                    <fullName>LOQ Submitted for approval</fullName>
                </value>
                <value>
                    <fullName>LOQ Approved</fullName>
                </value>
                <value>
                    <fullName>LOQ Rejected</fullName>
                </value>
                <value>
                    <fullName>LOQ Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LOQ_Conga_Doc_Generate_SFDC2.cls
public class LOQ_Conga_Doc_Generate_SFDC2 {

    @AuraEnabled
    public static String generateDocument(String LOQId){
        system.debug('LOQId' +LOQId);
        Loan_Ops_Questionnaire__c LOQFrm = [SELECT Name, LOQ_Status__c FROM Loan_Ops_Questionnaire__c WHERE Id = :LOQId];
        if(LOQFrm.LOQ_Status__c != 'LOQ Approved')
            return 'Warning: LOQ status should be approved.';
        APXTConga4__Conga_Merge_Query__c Congaquery = [SELECT Id FROM APXTConga4__Conga_Merge_Query__c WHERE APXTConga4__Name__c = 'C&I: LOQ Opportunity Fields'];
        String retURL = '';
        String orgId = UserInfo.getOrganizationId();
        
        retURL = '/apex/APXTConga4__Conga_Composer' + '?sessionId=' + UserInfo.getSessionId() + '&serverUrl=' + URL.getSalesforceBaseUrl().toExternalForm()
            +orgId+'&id=' + LOQId + '&DefaultPDF=0&SC0=1&SC1=Attachments&BML=' + LOQFrm.Name + 'Boarding Form Questionnaire Creation&QueryId=' 
            + Congaquery.Id + '&OFN=' + LOQFrm.Name + '+ Boarding+Form+Questionnaire&TemplateId= a0Ni000001wxUqt';
        return retURL;
    }
}