objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/APXTConga4__Conga_Template__c.object
<CustomObject>
    <description>Template manager for use with Conga Composer and Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Conga Template</label>
    <nameField>
        <displayFormat>CMT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>BF_Status__c</fullName>
        <label>BF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BF In Progress</fullName>
                    <default>true</default>
                    <label>BF In Progress</label>
                </value>
                <value>
                    <fullName>BF Submitted for Pre-Approval</fullName>
                </value>
                <value>
                    <fullName>BF Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>BF Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>BF Approved</fullName>
                </value>
                <value>
                    <fullName>BF Rejected</fullName>
                </value>
                <value>
                    <fullName>BF Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BF_Conga_Doc_Generate_SFDC2.cls
public class BF_Conga_Doc_Generate_SFDC2 {

    @AuraEnabled
    public static String generateDocument(String boardingFormId){
        
        Boarding_Form__c brdFrm = [SELECT Name, BF_Status__c FROM Boarding_Form__c WHERE Id = :boardingFormId];
        if(brdFrm.BF_Status__c != 'BF Approved')
            return 'Warning: Boarding form status should be approved.';
        
        String Congaquery;
        String Congaquery1;
       // if(!test.isRunningTest()){
            Congaquery = [SELECT Id FROM APXTConga4__Conga_Merge_Query__c WHERE APXTConga4__Name__c = 'C&I SFDC2: Borrowers to BF' limit 1].Id;
        	Congaquery1 = [SELECT Id FROM APXTConga4__Conga_Merge_Query__c WHERE APXTConga4__Name__c = 'C&I SFDC2: Guarantors to BF' limit 1].Id;
            String template = [select Id from APXTConga4__Conga_Template__c where APXTConga4__Name__c  = 'C&I Boarding Form Lightning'].Id;
        //}
       
        //a0Ni000001wxUq5
        String retURL = '';
        String orgId = UserInfo.getOrganizationId();
        
        retURL = '/apex/APXTConga4__Conga_Composer' + '?sessionId=' + UserInfo.getSessionId() + '&serverUrl=' + URL.getSalesforceBaseUrl().toExternalForm() +orgId+'&id=' + boardingFormId + '&DefaultPDF=0&SC0=1&SC1=Attachments&BML=' + brdFrm.Name + ' Boarding Form Creation&TemplateGroup=CI_BF&OFN=' + brdFrm.Name +
                 '+Boarding+Form&TemplateId=' + template + '&QueryId=[Borrowers]' + Congaquery+ ',[Guarantors]' + Congaquery1;

        return retURL;
    }
}