objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>Addl_LOQ_Options__c</fullName>
        <label>8. Select all that apply:</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Agent</fullName>
                </value>
                <value>
                    <fullName>Bridge A&amp;D</fullName>
                </value>
                <value>
                    <fullName>Bridge IR Requirement</fullName>
                </value>
                <value>
                    <fullName>Committed loan</fullName>
                </value>
                <value>
                    <fullName>Construction financing</fullName>
                </value>
                <value>
                    <fullName>Fund Control</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Bridge Interest Reverse Requirement</fullName>
                    <isActive>false</isActive>
                    <label>Bridge Interest Reverse Requirement</label>
                </value>
                <value>
                    <fullName>Participation</fullName>
                    <isActive>false</isActive>
                    <label>Participation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Borrower_Relationship__c</fullName>
        <label>4. Borrower to collateral relationship:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Participation</fullName>
                </value>
                <value>
                    <fullName>Lender Participation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>RE Acquisition</fullName>
                    <isActive>false</isActive>
                    <label>RE Acquisition</label>
                </value>
                <value>
                    <fullName>RE Construction</fullName>
                    <isActive>false</isActive>
                    <label>RE Construction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Secured__c</fullName>
        <label>5. Is collateral?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type_RE__c</fullName>
        <label>7. If RE, collateral type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notes</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                </value>
                <value>
                    <fullName>Recorded Mortgage</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type__c</fullName>
        <label>1. Collateral Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Business Loans</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Account/Lease Receivable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <label>3. Interest Rate Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adjustable</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOQ_Status__c</fullName>
        <description>Change in field values is controlled by approval process</description>
        <label>LOQ Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LOQ In Progress</fullName>
                    <default>true</default>
                    <label>LOQ In Progress</label>
                </value>
                <value>
                    <fullName>LOQ Submitted for approval</fullName>
                </value>
                <value>
                    <fullName>LOQ Approved</fullName>
                </value>
                <value>
                    <fullName>LOQ Rejected</fullName>
                </value>
                <value>
                    <fullName>LOQ Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>contains</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF, IPL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Ops Questionnaires</relationshipLabel>
        <relationshipName>Loan_Ops_Questionnaires</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>6. If RE, property type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFR</fullName>
                </value>
                <value>
                    <fullName>MF</fullName>
                </value>
                <value>
                    <fullName>CRE</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                    <isActive>false</isActive>
                    <label>NPL</label>
                </value>
                <value>
                    <fullName>Notes</fullName>
                    <isActive>false</isActive>
                    <label>Notes</label>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                    <isActive>false</isActive>
                    <label>Tax Lines</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Type__c</fullName>
        <label>2. Term Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Revolving LOC</fullName>
                </value>
                <value>
                    <fullName>Straight LOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LOQ_Conga_Doc_Generate_SFDC2_Test.cls
@isTest
public class LOQ_Conga_Doc_Generate_SFDC2_Test {

     static testmethod void generateDocTest(){
        
        Id opprecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRESL SFDC2').getRecordTypeId();
        Account acc = new Account(Name='test');
        insert acc;
       
       Opportunity opp = new Opportunity(
            StageName = 'Open',
            CloseDate = Date.today(),
            AccountId = acc.Id,
           RecordTypeId = opprecordTypeId,
            Name = 'Test Opportunity Triggers'
            
        );
        insert opp;
        APXTConga4__Conga_Merge_Query__c ccq = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'C&I: LOQ Opportunity Fields');
        insert ccq;
        Loan_Ops_Questionnaire__c LOQFrm = new Loan_Ops_Questionnaire__c(Opportunity__c = opp.Id,  Collateral_Type__c = 'Real Estate' ,  Term_Type__c = 'Term', Interest_Rate_Type__c = 'Adjustable' ,
                                                                         Borrower_Relationship__c = 'Direct', Property_Type__c = 'SFR', Collateral_Secured__c = 'Secured', Addl_LOQ_Options__c = 'Committed loan',
                                                                          Collateral_Type_RE__c = 'Notes' , LOQ_Status__c = 'LOQ Approved');

        insert LOQFrm;      
        Test.startTest();
        LOQ_Conga_Doc_Generate_SFDC2.generateDocument(String.valueOf(LOQFrm.Id));
        Test.stopTest();
    }
    
}