objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>Default set by trigger from Opp. field
CI_Loan_Amount__c</description>
        <inlineHelpText>Max credit facility being offered to the Borrower. Support doc (1 of the following): Note, Loan Agreement, other legal agreement executed by both BofI and Borrower.</inlineHelpText>
        <label>Loan Amount *</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used to provide ability to display BF on Opportunity page layout easily through related list.</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Boarding Forms</relationshipLabel>
        <relationshipName>Boarding_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <recordTypes>
        <fullName>Post_LOQ_Approval</fullName>
        <active>true</active>
        <label>Post LOQ Approval</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Borrower__c.object
<CustomObject>
    <description>C&amp;I Borrowers (Linked to Boarding Forms)</description>
    <fields>
        <fullName>Boarding_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boarding Form</label>
        <referenceTo>Boarding_Form__c</referenceTo>
        <relationshipLabel>Borrowers</relationshipLabel>
        <relationshipName>Borrowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class_Code__c</fullName>
        <inlineHelpText>A – Personal
B – Business Profit
C – Business Non-Profit
D – Employee/Direct Loan</inlineHelpText>
        <label>Class Code *</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A – Personal</fullName>
                </value>
                <value>
                    <fullName>B – Business Profit</fullName>
                </value>
                <value>
                    <fullName>C – Business Non-Profit</fullName>
                </value>
                <value>
                    <fullName>D – Employee/Direct Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_Address_City__c</fullName>
        <label>Mailing Address City *</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Country__c</fullName>
        <label>Mailing Address Country *</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Postal_Code__c</fullName>
        <label>Mailing Address Postal Code *</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_State__c</fullName>
        <label>Mailing Address State *</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Street__c</fullName>
        <label>Mailing Address Street *</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_City__c</fullName>
        <description>City</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_Class_Code__c</fullName>
        <description>Class Code</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_Country__c</fullName>
        <description>Country</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_Legal_Name__c</fullName>
        <description>Legal Name</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_Postal_Code__c</fullName>
        <description>Postal Code</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_State__c</fullName>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_Street__c</fullName>
        <description>Street</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_TaxID_Type__c</fullName>
        <description>Tax ID Number Type</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Page_TaxID__c</fullName>
        <description>Tax ID</description>
        <label>Source &amp; Page</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_ID_Number_Types__c</fullName>
        <label>Tax ID Number Types *</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tax_ID_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID_Number__c</fullName>
        <label>Tax ID Number *</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Borrower</label>
    <nameField>
        <label>Borrower Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Borrowers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Tax_ID_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>I - Individual</fullName>
    </customValue>
    <customValue>
        <fullName>T - TIN</fullName>
    </customValue>
    <masterLabel>Tax ID Types</masterLabel>
</GlobalValueSet>

classes/BorrowerIsReady_test.cls
@IsTest
public class BorrowerIsReady_test {
    @testSetup
    static void setup() {
        Map<String, RecordType> mapOpportunityRecordTypes = UtilsSFDC2.getRecordTypesMap('Opportunity', 'DeveloperName');
        Map<String, RecordType> mapAccountRecordTypes = UtilsSFDC2.getRecordTypesMap('Account', 'DeveloperName');
        Map<String, RecordType> mapBFRecordTypes = UtilsSFDC2.getRecordTypesMap('Boarding_Form__c', 'DeveloperName');

        Account acc = new Account(
            RecordTypeId = mapAccountRecordTypes.get('Business_Account_SFDC2').Id,
            Is_Converted__c = true,
            Name = 'TEST ACCOUNT'
        );

        insert acc;

        Opportunity opp = new Opportunity(
            RecordTypeId = mapOpportunityRecordTypes.get('CRESL_SFDC2').Id,
            Name = 'TEST OPP',
            StageName = '1 - New',
            CloseDate = System.today().addDays(10),
            AccountId = acc.Id,
            Loan_Amount__c = 100.55,
            Estimated_Rate_at_Close__c = 5.0,
            C_I_Sub_Stage__c = 'Gathering Information',
            CI_Projected_Initial_Funding__c = 100.55
        );
        insert opp;
        
        
        Boarding_Form__c  bf = new Boarding_Form__c(
       			RecordTypeId = mapBFRecordTypes.get('Post_LOQ_Approval').Id, 
        		Opportunity__c = opp.Id);
        
        insert bf;
        
    }    
    
    @isTest
    static void borrowerReady() {
        Boarding_Form__c bf = [Select id from Boarding_Form__c limit 1];

        Borrower__c b = new Borrower__c( Boarding_Form__c = bf.Id,
            Name = 'NewBorrower 30-03',
            Class_Code__c = 'D – Employee/Direct Loan',
            Mailing_Address_City__c = 'Personal',
            Mailing_Address_Country__c = 'MEX',       
            Mailing_Address_Postal_Code__c = '07222',
            Mailing_Address_State__c = 'JA',
            Mailing_Address_Street__c	 = 'JAJAJA',
            Tax_ID_Number__c = '99-9801234' , 
            Tax_ID_Number_Types__c = 'T - TIN',                     
                                          
            
            Source_Page_TaxID__c = 'test',
            Source_Page_TaxID_Type__c = 'test',
            Source_Page_Street__c = 'test',       
            Source_Page_State__c = 'test',
            Source_Page_Postal_Code__c = 'test',
            Source_Page_Legal_Name__c = 'test',
            Source_Page_Country__c = 'test' ,  
            Source_Page_Class_Code__c = 'test',
            Source_Page_City__c = 'test'
            
        );
        insert b;
		
        List<Borrower__c> idB  = new List<Borrower__c>();
        idB.add(b);
        
        BorrowerIsReady.getBorrowerIds(idB);

    }
    
}