objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>BF_Status__c</fullName>
        <label>BF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BF In Progress</fullName>
                    <default>true</default>
                    <label>BF In Progress</label>
                </value>
                <value>
                    <fullName>BF Submitted for Pre-Approval</fullName>
                </value>
                <value>
                    <fullName>BF Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>BF Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>BF Approved</fullName>
                </value>
                <value>
                    <fullName>BF Rejected</fullName>
                </value>
                <value>
                    <fullName>BF Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>Default set by trigger from Opp. field
CI_Loan_Amount__c</description>
        <inlineHelpText>Max credit facility being offered to the Borrower. Support doc (1 of the following): Note, Loan Agreement, other legal agreement executed by both BofI and Borrower.</inlineHelpText>
        <label>Loan Amount *</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used to provide ability to display BF on Opportunity page layout easily through related list.</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Boarding Forms</relationshipLabel>
        <relationshipName>Boarding_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>SFDC2_24hReminderDate__c</fullName>
        <label>SFDC2 24h Reminder Date</label>
        <type>DateTime</type>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <recordTypes>
        <fullName>Post_LOQ_Approval</fullName>
        <active>true</active>
        <label>Post LOQ Approval</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BoardingFormSLA24hReminderSFDC2_Test.cls
/*******************************************************************************
Developed by: Unosquare
Author: Daniel Peñaloza
Project: BOFI - C&I
Description: Apex Test class for BoardingFormSLARemindersSFDC2

--------- ---------- -------------------------- -----------------------------------
Version   Date       Author                     Change Description
--------- ---------- -------------------------- -----------------------------------
1.0    29/01/2018 Daniel Peñaloza            Class created
*******************************************************************************/

@isTest
private class BoardingFormSLA24hReminderSFDC2_Test {
    
    @testSetup
    static void setup() {
        Map<String, RecordType> mapOpportunityRecordTypes = UtilsSFDC2.getRecordTypesMap('Opportunity', 'DeveloperName');
        Map<String, RecordType> mapAccountRecordTypes = UtilsSFDC2.getRecordTypesMap('Account', 'DeveloperName');
        Map<String, RecordType> mapBFRecordTypes = UtilsSFDC2.getRecordTypesMap('Boarding_Form__c', 'DeveloperName');
        
        Account acc = new Account(
            RecordTypeId = mapAccountRecordTypes.get('Business_Account_SFDC2').Id,
            Is_Converted__c = true,
            Name = 'TEST ACCOUNT'
        );
        
        insert acc;
        
        Opportunity opp = new Opportunity(
            RecordTypeId = mapOpportunityRecordTypes.get('CRESL_SFDC2').Id,
            Name = 'TEST OPP',
            StageName = '1 - New',
            CloseDate = System.today().addDays(10),
            AccountId = acc.Id,
            Loan_Amount__c = 100.55,
            Estimated_Rate_at_Close__c = 5.0,
            C_I_Sub_Stage__c = 'Gathering Information',
            CI_Projected_Initial_Funding__c = 100.55
        );
        insert opp;
        
        Boarding_Form__c  bf = new Boarding_Form__c(
            RecordTypeId = mapBFRecordTypes.get('Post_LOQ_Approval').Id, 
            Opportunity__c = opp.Id);
        
        insert bf;
    }
    
    @isTest
    static void should_set_bf_24h_reminder_date() {
        Boarding_Form__c[] lstBoardingForms = [
            SELECT Id, SFDC2_24hReminderDate__c
            FROM Boarding_Form__c limit 1
        ];
        
        System.assert(!lstBoardingForms.isEmpty());
        
        for (Boarding_Form__c bf: lstBoardingForms) {
            bf.BF_Status__c = 'BF Submitted for Approval';
        }
        
        // Execute test
        Test.startTest();
        update lstBoardingForms;
        
        BoardingFormSLA24hReminderSFDC2.setBoardingForm24hReminderDates(lstBoardingForms); 
        Test.stopTest();
        /*
        // Verify test results
        lstBoardingForms = [
            SELECT Id, SFDC2_24hReminderDate__c
            FROM Boarding_Form__c
        ];
        
        Boolean allValid = true;
        for (Boarding_Form__c bf: lstBoardingForms) {
            allValid = (allValid && bf.SFDC2_24hReminderDate__c != null);
        }
        
        System.assertEquals(true, allValid); */
    }
}