objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>GuarantorReadyForSubmmit_SFDC2_del__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Garantor have the requiered fields populated for submmited for approval</description>
        <label>Guarantor Info Ready</label>
        <type>Checkbox</type>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Guarantor__c.object
<CustomObject>
    <description>This is the name of anyone guarantying the loan with BofI. This may be recourse or non-recourse. Source doc (1 of the following): Guaranty Agreement, SS-4, IRS TIN Verification. The IRS TIN Verification can be requested from C&amp;I Operations.</description>
    <fields>
        <fullName>Boarding_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationshio with the Boarding Form object</description>
        <label>Boarding Form</label>
        <referenceTo>Boarding_Form__c</referenceTo>
        <relationshipLabel>Guarantors</relationshipLabel>
        <relationshipName>Guarantors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Guarantor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GuaratorIsReady.cls
public class GuaratorIsReady {
    
    @InvocableMethod(label='Get Guarator' description='desc Invocable method')
    public static void  getGuaratorIds(List<Guarantor__c> idG) {
        
        Guarantor__c g = new Guarantor__c();
        g= idG[0]; 
        updateBF(g.Boarding_Form__c);
    }
    
    
    @future 
    public static void updateBF(Id bfId){
        
       Boarding_Form__c bf = new Boarding_Form__c(id=bfId, GuarantorReadyForSubmmit_SFDC2_del__c = true);
        update bf;        
        
    }
    
}