objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>BorrowerReadyForSubmmit_SFDC2_del__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Chech if the Related borrower record is populated the required fields to send BF for Approval</description>
        <label>Borrower Info Ready</label>
        <type>Checkbox</type>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Borrower__c.object
<CustomObject>
    <description>C&amp;I Borrowers (Linked to Boarding Forms)</description>
    <fields>
        <fullName>Boarding_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boarding Form</label>
        <referenceTo>Boarding_Form__c</referenceTo>
        <relationshipLabel>Borrowers</relationshipLabel>
        <relationshipName>Borrowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Borrower</label>
    <nameField>
        <label>Borrower Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Borrowers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BorrowerIsReady.cls
public class BorrowerIsReady {
    
    @InvocableMethod(label='Get Borrower' description='desc Invocable method')
    public static void  getBorrowerIds(List<Borrower__c> idB) {
        
        Borrower__c b = new Borrower__c();
        b= idB[0]; 
        updateBF(b.Boarding_Form__c);
        System.debug('Borrower process');
    }
    
    
    @future 
    public static void updateBF(Id bfId){
        
       Boarding_Form__c bf = new Boarding_Form__c(id=bfId, BorrowerReadyForSubmmit_SFDC2_del__c = true);
        update bf;        
        
    }
}