objects/Boarding_Form__c.object
<CustomObject>
    <description>Used for C&amp;I to create a Boarding Form for their Boarding Documentation Process. A Boarding Form record will be created from the LOQ object.</description>
    <fields>
        <fullName>GTR_1_Class_Code_Source_Page__c</fullName>
        <label>GTR 1 Class Code Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Contingent_Source_Page__c</fullName>
        <label>GTR 1 Contingent? Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_City_Source_Page__c</fullName>
        <label>GTR 1 Mailing City Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Country_Source_Page__c</fullName>
        <label>GTR 1 Mailing Country Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_State_Source_Page__c</fullName>
        <label>GTR 1 Mailing State Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Street_Source_Page__c</fullName>
        <label>GTR 1 Mailing Street Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Name_Source_Page__c</fullName>
        <label>GTR 1 Name Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Postal_Code_Zip_Source_Page__c</fullName>
        <label>GTR 1 Postal Code/Zip Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_Number_Source_Page__c</fullName>
        <label>GTR 1 Tax ID Number Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_Number_Type_Source_Page__c</fullName>
        <label>GTR 1 Tax ID Number Type Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>Default set by trigger from Opp. field
CI_Loan_Amount__c</description>
        <inlineHelpText>Max credit facility being offered to the Borrower. Support doc (1 of the following): Note, Loan Agreement, other legal agreement executed by both BofI and Borrower.</inlineHelpText>
        <label>Loan Amount *</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used to provide ability to display BF on Opportunity page layout easily through related list.</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Boarding Forms</relationshipLabel>
        <relationshipName>Boarding_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Boarding Form</label>
    <nameField>
        <displayFormat>BF-{00000}</displayFormat>
        <label>Boarding Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boarding Forms</pluralLabel>
    <recordTypes>
        <fullName>Post_LOQ_Approval</fullName>
        <active>true</active>
        <label>Post LOQ Approval</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Guarantor__c.object
<CustomObject>
    <description>This is the name of anyone guarantying the loan with BofI. This may be recourse or non-recourse. Source doc (1 of the following): Guaranty Agreement, SS-4, IRS TIN Verification. The IRS TIN Verification can be requested from C&amp;I Operations.</description>
    <fields>
        <fullName>Boarding_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationshio with the Boarding Form object</description>
        <label>Boarding Form</label>
        <referenceTo>Boarding_Form__c</referenceTo>
        <relationshipLabel>Guarantors</relationshipLabel>
        <relationshipName>Guarantors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GTR_1_Class_Code_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Class_Code__c</fullName>
        <description>Save  Class Code for the Guarantor</description>
        <inlineHelpText>Option C requires additional verification from https://apps.irs.gov/app/eos/. Provide screenshot from website of findings. A, B, or D: No additional source doc required.</inlineHelpText>
        <label>Class Code *</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A – Personal</fullName>
                </value>
                <value>
                    <fullName>B – Business Profit</fullName>
                </value>
                <value>
                    <fullName>C – Business Non-Profit</fullName>
                </value>
                <value>
                    <fullName>D – Employee/Direct Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTR_1_Contingent_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Contingent__c</fullName>
        <description>Save the Contingent  for the Guarantor</description>
        <inlineHelpText>Select Yes if this a recourse guaranty. Select No for non-recourse. Source doc: Guaranty agreement(s).</inlineHelpText>
        <label>Contingent ? *</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_City_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_City__c</fullName>
        <description>Save the City Name for the Guarantor</description>
        <label>Mailing City *</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Country_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Country__c</fullName>
        <description>Save the Country Name for the Guarantor</description>
        <label>Mailing Country *</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Postal_Code_Zip__c</fullName>
        <description>Save the Postal Code/Zip for the Guarantor</description>
        <label>Mailing Postal Code/Zip *</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_State_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_State__c</fullName>
        <description>Save the State Name for the Guarantor</description>
        <label>Mailing State *</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Street_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Mailing_Street__c</fullName>
        <description>Save the Street Name for the Guarantor</description>
        <label>Mailing Street *</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Name_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Postal_Code_Zip_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_Number_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_Number_Type_Source_Page__c</fullName>
        <label>Source &amp; Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_Number_Type__c</fullName>
        <description>Save the Tax ID Number Type for the Guarantor</description>
        <inlineHelpText>Source doc: SS-4, IRS TIN Verification. The IRS TIN Verification can be requested from C&amp;I Operations.</inlineHelpText>
        <label>Tax ID Number Type *</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I - Individual</fullName>
                </value>
                <value>
                    <fullName>T - TIN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTR_1_Tax_ID_number__c</fullName>
        <description>Save the Tax ID Number  for the Guarantor</description>
        <inlineHelpText>Source doc (1 of the following): IRS TIN Verification, Credit Authorization/Application (for individuals only). The IRS TIN Verification can be requested from C&amp;I Operations. If a foreign national, refer to BSA.</inlineHelpText>
        <label>Tax ID Number *</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Guarantor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GuaratorIsReady_test.cls
@IsTest
public class GuaratorIsReady_test {
    @testSetup
    static void setup() {
        Map<String, RecordType> mapOpportunityRecordTypes = UtilsSFDC2.getRecordTypesMap('Opportunity', 'DeveloperName');
        Map<String, RecordType> mapAccountRecordTypes = UtilsSFDC2.getRecordTypesMap('Account', 'DeveloperName');
        Map<String, RecordType> mapBFRecordTypes = UtilsSFDC2.getRecordTypesMap('Boarding_Form__c', 'DeveloperName');

        Account acc = new Account(
            RecordTypeId = mapAccountRecordTypes.get('Business_Account_SFDC2').Id,
            Is_Converted__c = true,
            Name = 'TEST ACCOUNT'
        );

        insert acc;

        Opportunity opp = new Opportunity(
            RecordTypeId = mapOpportunityRecordTypes.get('CRESL_SFDC2').Id,
            Name = 'TEST OPP',
            StageName = '1 - New',
            CloseDate = System.today().addDays(10),
            AccountId = acc.Id,
            Loan_Amount__c = 100.55,
            Estimated_Rate_at_Close__c = 5.0,
            C_I_Sub_Stage__c = 'Gathering Information',
            CI_Projected_Initial_Funding__c = 100.55
        );
        insert opp;
        
        
        Boarding_Form__c  bf = new Boarding_Form__c(
       			RecordTypeId = mapBFRecordTypes.get('Post_LOQ_Approval').Id, 
        		Opportunity__c = opp.Id);
        
        insert bf;
        
    }    
    
    @isTest
    static void garatorReady() {
        Boarding_Form__c bf = [Select id from Boarding_Form__c limit 1];

        Guarantor__c g = new Guarantor__c( Boarding_Form__c = bf.Id,
            Name = 'New Guarantor 30/03',
            GTR_1_Contingent__c = 'Yes',
            GTR_1_Class_Code__c = 'A – Personal',
            GTR_1_Mailing_City__c = 'GDL',       
            GTR_1_Mailing_Country__c = 'test',
            GTR_1_Mailing_Postal_Code_Zip__c = '97420',
            GTR_1_Mailing_State__c = 'JA',
            GTR_1_Mailing_Street__c = '150 Jacarandas' , 
            GTR_1_Tax_ID_number__c = '99-7890630',
            GTR_1_Tax_ID_Number_Type__c = 'I - Individual' ,                           
                                          
            
            GTR_1_Class_Code_Source_Page__c = 'test',
            GTR_1_Contingent_Source_Page__c = 'test',
            GTR_1_Mailing_City_Source_Page__c = 'test',       
            GTR_1_Mailing_Country_Source_Page__c = 'test',
            GTR_1_Mailing_State_Source_Page__c = 'test',
            GTR_1_Mailing_Street_Source_Page__c = 'test',
            GTR_1_Name_Source_Page__c = 'test' ,  
            GTR_1_Postal_Code_Zip_Source_Page__c = 'test',
            GTR_1_Tax_ID_Number_Source_Page__c = 'test',
            GTR_1_Tax_ID_Number_Type_Source_Page__c = 'test'  
            
        );
        insert g;
        
        List<Guarantor__c> idG  = new List<Guarantor__c>();
        idG.add(g);
        
        GuaratorIsReady.getGuaratorIds(idG);
       
    }
    
}