objects/C_I_Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Certification__c</fullName>
        <label>Certification</label>
        <referenceTo>CI_Certification__c</referenceTo>
        <relationshipLabel>C&amp;I Checklist Items</relationshipLabel>
        <relationshipName>C_I_Checklist_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Checklist Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/C_I_Checklist_Item_Admin__c.object
<CustomObject>
    <description>Used by C&amp;I to define checklist items required for certifications</description>
    <fields>
        <fullName>Certification_Type__c</fullName>
        <label>Certification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Certification</fullName>
                </value>
                <value>
                    <fullName>Quarterly Certification</fullName>
                </value>
                <value>
                    <fullName>Monthly Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Checklist_Item_Name__c</fullName>
        <label>Checklist Item Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Certification_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Audited Financial Statements</fullName>
                </value>
                <value>
                    <fullName>Background Check</fullName>
                </value>
                <value>
                    <fullName>Borrowing Base</fullName>
                </value>
                <value>
                    <fullName>Cash Audit</fullName>
                </value>
                <value>
                    <fullName>Co. Prep. Financial Statements</fullName>
                </value>
                <value>
                    <fullName>Collateral Audit</fullName>
                </value>
                <value>
                    <fullName>Collateral Validation</fullName>
                </value>
                <value>
                    <fullName>Compliance Audit</fullName>
                </value>
                <value>
                    <fullName>Corporate Federal &amp; State Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Covenant Check</fullName>
                </value>
                <value>
                    <fullName>Credit Bureau Report (CBR)</fullName>
                </value>
                <value>
                    <fullName>Custodial Report</fullName>
                </value>
                <value>
                    <fullName>Development Budget</fullName>
                </value>
                <value>
                    <fullName>Financial Projections</fullName>
                </value>
                <value>
                    <fullName>Loan Review</fullName>
                </value>
                <value>
                    <fullName>Personal Federal &amp; State Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Personal Financial Statement (PFS)</fullName>
                </value>
                <value>
                    <fullName>Procedural Audit</fullName>
                </value>
                <value>
                    <fullName>Proof of Insurance</fullName>
                </value>
                <value>
                    <fullName>Rent Roll/Lease Receivable Aging</fullName>
                </value>
                <value>
                    <fullName>Reporting Package</fullName>
                </value>
                <value>
                    <fullName>Risk Rating</fullName>
                </value>
                <value>
                    <fullName>Schedule of Security Deposits</fullName>
                </value>
                <value>
                    <fullName>Servicing Report</fullName>
                </value>
                <value>
                    <fullName>Site Inspections/Draw Request Packages</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Status Updates</fullName>
                </value>
                <value>
                    <fullName>Technology Audit</fullName>
                </value>
                <value>
                    <fullName>Title Bring Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Checklist Item Admin records can only be associated with C&amp;I Opportunities</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>C&amp;I - AB Participation, C&amp;I - Bridge, C&amp;I - General, C&amp;I - Lender Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>C&amp;I Checklist Item Admins</relationshipLabel>
        <relationshipName>C_I_Checklist_Item_Admins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>C&amp;I Checklist Item Admin</label>
    <nameField>
        <label>Checklist Item Admin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Checklist Item Admins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CI_Certification__c.object
<CustomObject>
    <description>Used by C&amp;I</description>
    <fields>
        <fullName>Certification_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Owner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only C&amp;I users may be Certification Owners</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>C_I_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certification Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChecklistLinkId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used in the auto-creation of Certification records with their required checklist items</description>
        <externalId>true</externalId>
        <label>ChecklistLinkId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_of_Certification__c</fullName>
        <label>Month of Certification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>C&amp;I Certifications may only be associated with C&amp;I Opportunity records.</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>C&amp;I - AB Participation, C&amp;I - Bridge, C&amp;I - General, C&amp;I - Lender Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Certifications1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Credit Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_of_Certification__c</fullName>
        <label>Year of Certification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CICertificationCreationHandler.cls
/**
* @description <p>Handler class for automated creation of CI Certification functionality</p>
* @author Mike Crosby, BofI Federal 
*/
global class CICertificationCreationHandler {
    private Map<String, Id> certRecordTypeIdMap = new Map<String, Id>();
    
    /** Constructor */
    global CICertificationCreationHandler() {
        certRecordTypeIdMap = getCertificationRecordTypes();
    }
    
    private Map<String, Id> getCertificationRecordTypes() {
        Map<String, Id> returnMap = new Map<String, Id>();
        for(RecordType rt : [SELECT Name FROM RecordType WHERE SObjectType = 'CI_Certification__c' AND IsActive=true]) {
            returnMap.put(rt.Name, rt.Id);
        }
        return returnMap;
    }
    
    /** Handles the logic for the C&I Certification creation */
    global void run(Date timePeriod) {
        //retrieve list of Certifications that exist for the current period to ensure duplications aren't created
        Date startDate = timePeriod.toStartOfMonth();
        Date dueDate = timePeriod.toStartOfMonth().addDays(75);
        String certYear = String.valueOf(startDate.year());
        String certMonth = ((startDate.month() < 10) ? '0' : '') + String.valueOf(startDate.month());
        List<CI_Certification__c> existingCerts = [SELECT
                                                        Opportunity__c,
                                                        Certification_Type__c
                                                    FROM CI_Certification__c
                                                    WHERE
                                                        Year_of_Certification__c = :certYear AND
                                                        Month_of_Certification__c = :certMonth
                                                    ];
        
        //retrieve all required checklist items for C&I opportunities
        Map<Id,Map<String,CertificationWrapper>> oppCertMap = new Map<Id,Map<String,CertificationWrapper>>();
        for(C_I_Checklist_Item_Admin__c citem : [SELECT
                                                    Opportunity__c,
                                                    Certification_Type__c,
                                                    Checklist_Item_Name__c,
                                                    Grace_Period__c,
                                                    Opportunity__r.OwnerId
                                                FROM C_I_Checklist_Item_Admin__c
                                                WHERE
                                                    Opportunity__r.StageName = 'Closed Won' AND
                                                    (
                                                        (Opportunity__r.CI_Annual_Certification_Required__c = true AND 
                                                            Certification_Type__c = 'Annual Certification') OR
                                                        (Opportunity__r.CI_Quarterly_Certification_Required__c = true AND
                                                            Certification_Type__c = 'Quarterly Certification') OR
                                                        (Opportunity__r.CI_Monthly_Certification_Required__c = true AND
                                                            Certification_Type__c = 'Monthly Certification')
                                                    )]) {
            //check to make sure certification doesn't already exist for the current period
            Boolean certExists = false;
            for(CI_Certification__c cert : existingCerts) {
                if(cert.Opportunity__c == citem.Opportunity__c &&
                    cert.Certification_Type__c == citem.Certification_Type__c) {
                    certExists = true;  
                }
            }
            //certification already exists for this period--do not duplicate
            if(certExists)
            {
                continue;
            }
            
            //handle opportunity not already defined
            if(!oppCertMap.containsKey(citem.Opportunity__c)) {
                oppCertMap.put(citem.Opportunity__c, new Map<String, CertificationWrapper>());
            }
            
            //handle certification type not already defined
            if(!oppCertMap.get(citem.Opportunity__c).containsKey(citem.Certification_Type__c)) {
                CertificationWrapper cwrap = new CertificationWrapper();
                cwrap.OpportunityId = citem.Opportunity__c;
                cwrap.CertificationType = citem.Certification_Type__c;
                cwrap.RecordTypeId = certRecordTypeIdMap.get(citem.Certification_Type__c);
                cwrap.StartDate = startDate;
                cwrap.DueDate = dueDate;
                cwrap.CertificationYear = certYear;
                cwrap.CertificationMonth = certMonth;
                cwrap.Owner = citem.Opportunity__r.OwnerId;
                cwrap.ItemList = new List<C_I_Checklist_Item__c>();
                oppCertMap.get(citem.Opportunity__c).put(citem.Certification_Type__c, cwrap);
            }
            
            //add checklist item to be created
            CertificationWrapper cwrap = oppCertMap.get(citem.Opportunity__c).get(citem.Certification_Type__c);
            String certKey = cwrap.getChecklistLinkId();
            CI_Certification__c cert = new CI_Certification__c(ChecklistLinkId__c=certKey);
            C_I_Checklist_Item__c item = new C_I_Checklist_Item__c();
            item.Name = citem.Checklist_Item_Name__c;
            item.Status__c = 'Requested';
            item.Grace_Period__c = citem.Grace_Period__c;
            item.Certification__r = cert;
            oppCertMap.get(citem.Opportunity__c).get(citem.Certification_Type__c).ItemList.add(item);
        }
        
        //once the certs/checklist items are set up, insert the records
        //included logic here to only insert based on time period matching certification type
        //List<Sobject> objList = new List<Sobject>();
        List<CI_Certification__c> insertCertList = new List<CI_Certification__c>();
        List<C_I_Checklist_Item__c> insertCItemList = new List<C_I_Checklist_Item__c>();
        for(Map<String,CertificationWrapper> wrapperMap : oppCertMap.values()) {
            for(CertificationWrapper certWrap : wrapperMap.values()) {
                if(certWrap.CertificationType == 'Monthly Certification' ||
                    (certWrap.CertificationType == 'Quarterly Certification' && 
                        (
                            certWrap.CertificationMonth == '03' ||
                            certWrap.CertificationMonth == '06' ||
                            certWrap.CertificationMonth == '09' ||
                            certWrap.CertificationMonth == '12' 
                        )) ||
                    (certWrap.CertificationType == 'Annual Certification' && certWrap.CertificationMonth == '12')) {
                    //objList.add(certWrap.getCertificationObject());
                    insertCertList.add(certWrap.getCertificationObject());
                    for(C_I_Checklist_Item__c citem : certWrap.ItemList) {
                        //objList.add(citem);
                        insertCItemList.add(citem);
                    }
                }
            }
        }
        
        //if(objList.size() > 0) {
        if(insertCertList.size() > 0) {
            //insert objList;
            insert insertCertList;
            insert insertCItemList;
        }
    }
    
    /** Private wrapper class for Certifications */
    private class CertificationWrapper {
        public Id OpportunityId {get; set;}
        public String CertificationType {get; set;}
        public String RecordTypeId {get; set;}
        public String CertificationYear {get; set;}
        public String CertificationMonth {get; set;}
        public Date DueDate {get; set;}
        public Id Owner {get; set;}
        public Date StartDate {get; set;}
        public List<C_I_Checklist_Item__c> ItemList {get; set;}
        
        /** Constructor */
        public CertificationWrapper() {}
        
        public String getChecklistLinkId() {
            return OpportunityId + '|' + CertificationType + '|' + CertificationYear + '|' + CertificationMonth;
        }
        
        public CI_Certification__c getCertificationObject() {
            CI_Certification__c cert = new CI_Certification__c();
            cert.Opportunity__c = OpportunityId;
            cert.RecordTypeId = RecordTypeId;
            cert.Status__c = 'In Progress';
            cert.Month_of_Certification__c = CertificationMonth;
            cert.Year_of_Certification__c = CertificationYear;
            cert.Start_Date__c = StartDate;
            cert.Due_Date__c = DueDate;
            cert.Certification_Owner__c = Owner;
            cert.ChecklistLinkId__c = getChecklistLinkId();
            return cert;
        }
    }
}