objects/C_I_Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Certification__c</fullName>
        <label>Certification</label>
        <referenceTo>CI_Certification__c</referenceTo>
        <relationshipLabel>C&amp;I Checklist Items</relationshipLabel>
        <relationshipName>C_I_Checklist_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Checklist Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CI_Certification__c.object
<CustomObject>
    <description>Used by C&amp;I</description>
    <fields>
        <fullName>Ready_for_Approval__c</fullName>
        <formula>IF( AllItemsReceived__c, 
  IMAGE(&quot;/resource/bullet_green&quot;,&quot;Ready&quot;,16,16),
  IMAGE(&quot;/resource/bullet_RED&quot;,&quot;Not Ready&quot;,16,16)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ready for Approval</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Credit Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CICertChecklistDisplayExt.cls
public with sharing class CICertChecklistDisplayExt {
	/** Current Certification record */
	private CI_Certification__c cert;

	public Boolean isEditor {
		get
		{
			return Schema.Sobjecttype.C_I_Checklist_Item__c.isUpdateable();
		}
	}

	/** Constructor */
	public CICertChecklistDisplayExt(ApexPages.StandardController ctr) {
		cert = (CI_Certification__c)ctr.getRecord();
		cert = getCertificationDetails(cert.Id);
		resetEditVariables();
	}
	
	/**
	* Retrieves list of checklist items associated with the certification
	* @return list of CI Checklist Item records
	*/
	public List<C_I_Checklist_Item__c> getChecklistItems() {
		return cert.C_I_Checklist_Items__r;
	}
	
	/**
	* Retrieves image for whether or not the cert is ready for approval submission
	* @return html image string
	*/
	public String getReadyForApprovalImage() {
		return cert.Ready_for_Approval__c;
	}
	
	/**
	* Retrieves certification and checklist item data
	*/
	private CI_Certification__c getCertificationDetails(Id certId) {
		return [
				SELECT Name, Ready_for_Approval__c,
					(SELECT Name, Status__c, Grace_Period__c
						FROM C_I_Checklist_Items__r ORDER BY Name) 
				FROM CI_Certification__c 
				WHERE Id = :certId
				];
	}
	
	/** Checklist item id selected for editing */
	public String selectedItemId {get; set;}
	/** Existing status for checklist item selected */
	public String selectedItemStatus {get; set;}
	
	/** Checklist Item placeholder for modification */
	public C_I_Checklist_Item__c modifyItem {get; set;}
	
	/** Indicates whether a checklist item has been selected for editing */
	public Boolean isEdit {get; set;}
	
	/** Sets up interface for editing item status */
	public PageReference editItem() {
		if(selectedItemId == null) {
			return null;
		}
		modifyItem = new C_I_Checklist_Item__c();
		modifyItem.Id = selectedItemId;
		modifyItem.Status__c = selectedItemStatus;
		isEdit = true;
		return null;
	}
	
	/** Saves changes to item */
	public PageReference saveItem() {
		update modifyItem;
		resetEditVariables();
		cert = getCertificationDetails(cert.Id);
		return null;
	}
	
	/** Cancels editing of item */
	public PageReference cancelItem() {
		resetEditVariables();
		return null;
	}
	
	/** Clears out item edit variables */
	private void resetEditVariables() {
		isEdit = false;
		modifyItem = null;
		selectedItemId = null;
		selectedItemStatus = null;
	}
}