objects/C_I_Checklist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Certification__c</fullName>
        <label>Certification</label>
        <referenceTo>CI_Certification__c</referenceTo>
        <relationshipLabel>C&amp;I Checklist Items</relationshipLabel>
        <relationshipName>C_I_Checklist_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Checklist Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CI_Certification__c.object
<CustomObject>
    <description>Used by C&amp;I</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Credit Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CICertChecklistDisplayExt_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CICertChecklistDisplayExt_Test {

	@isTest
    static void testCICertChecklistDisplayExt() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
    	//Test using C&I - General Opportunity type
        Opportunity opp = new Opportunity(AccountId=acct.Id, 
        									Name='Test', 
        									RecordTypeId='012i0000001AcDB',
                                            CI_Rate_Type__c = 'Fixed',
                                            CI_Rate__c = 1,
        									StageName='Closed Won',
        									CloseDate=Date.today());
       insert opp;
       RecordType rt = [SELECT Id, Name FROM RecordType WHERE SObjectType='CI_Certification__c' LIMIT 1];       
       CI_Certification__c cert = TestDataFactory.createTestCICertification(opp);
       cert.RecordTypeId = rt.Id;
       insert cert;
       
       C_I_Checklist_Item__c citem = new C_I_Checklist_Item__c(Name='Test', Certification__c=cert.Id,Status__c='Requested', Grace_Period__c=1);
       insert citem;
       
       PageReference ref = Page.CICertChecklistDisplay;
       ref.getParameters().put('id', cert.Id);
       Test.setCurrentPageReference(ref);
       CICertChecklistDisplayExt ext = new CICertChecklistDisplayExt(new Apexpages.StandardController(cert));
       System.assertEquals(1, ext.getChecklistItems().size());
       
       System.assertEquals(true, ext.isEditor);
       
       ext.editItem();
       System.assertEquals(null, ext.modifyItem);
       
       ext.selectedItemId = citem.id;
       ext.selectedItemStatus = 'Requested';
       ext.editItem();
       System.assertEquals(citem.Id, ext.modifyItem.Id);
       System.assertEquals('Requested', ext.modifyItem.Status__c);
       System.assertEquals(true, ext.isEdit);
       ext.cancelItem();
       System.assertEquals(null, ext.modifyItem);
       System.assertEquals(false, ext.isEdit);
       
       ext.selectedItemId = citem.id;
       ext.selectedItemStatus = 'Requested';
       ext.editItem();
       ext.modifyItem.Status__c = 'Received';
       ext.saveItem();
       citem = [SELECT Status__c FROM C_I_Checklist_Item__c WHERE Id = :citem.Id];
       System.assertEquals('Received', citem.Status__c);
       ext.getReadyForApprovalImage();
    }
}