objects/C_I_Checklist_Item_Admin__c.object
<CustomObject>
    <description>Used by C&amp;I to define checklist items required for certifications</description>
    <fields>
        <fullName>Certification_Type__c</fullName>
        <label>Certification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Certification</fullName>
                </value>
                <value>
                    <fullName>Quarterly Certification</fullName>
                </value>
                <value>
                    <fullName>Monthly Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Checklist_Item_Name__c</fullName>
        <label>Checklist Item Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Certification_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Audited Financial Statements</fullName>
                </value>
                <value>
                    <fullName>Background Check</fullName>
                </value>
                <value>
                    <fullName>Borrowing Base</fullName>
                </value>
                <value>
                    <fullName>Cash Audit</fullName>
                </value>
                <value>
                    <fullName>Co. Prep. Financial Statements</fullName>
                </value>
                <value>
                    <fullName>Collateral Audit</fullName>
                </value>
                <value>
                    <fullName>Collateral Validation</fullName>
                </value>
                <value>
                    <fullName>Compliance Audit</fullName>
                </value>
                <value>
                    <fullName>Corporate Federal &amp; State Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Covenant Check</fullName>
                </value>
                <value>
                    <fullName>Credit Bureau Report (CBR)</fullName>
                </value>
                <value>
                    <fullName>Custodial Report</fullName>
                </value>
                <value>
                    <fullName>Development Budget</fullName>
                </value>
                <value>
                    <fullName>Financial Projections</fullName>
                </value>
                <value>
                    <fullName>Loan Review</fullName>
                </value>
                <value>
                    <fullName>Personal Federal &amp; State Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Personal Financial Statement (PFS)</fullName>
                </value>
                <value>
                    <fullName>Procedural Audit</fullName>
                </value>
                <value>
                    <fullName>Proof of Insurance</fullName>
                </value>
                <value>
                    <fullName>Rent Roll/Lease Receivable Aging</fullName>
                </value>
                <value>
                    <fullName>Reporting Package</fullName>
                </value>
                <value>
                    <fullName>Risk Rating</fullName>
                </value>
                <value>
                    <fullName>Schedule of Security Deposits</fullName>
                </value>
                <value>
                    <fullName>Servicing Report</fullName>
                </value>
                <value>
                    <fullName>Site Inspections/Draw Request Packages</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Status Updates</fullName>
                </value>
                <value>
                    <fullName>Technology Audit</fullName>
                </value>
                <value>
                    <fullName>Title Bring Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Checklist Item Admin records can only be associated with C&amp;I Opportunities</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>C&amp;I - AB Participation, C&amp;I - Bridge, C&amp;I - General, C&amp;I - Lender Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>C&amp;I Checklist Item Admins</relationshipLabel>
        <relationshipName>C_I_Checklist_Item_Admins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>C&amp;I Checklist Item Admin</label>
    <nameField>
        <label>Checklist Item Admin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Checklist Item Admins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CICertAdmin_Extension.cls
public with sharing class CICertAdmin_Extension {
    /** Current opportunity record */
    public Opportunity opp {get; set;}
    
    /** User's ability to edit */
    public Boolean isEditor {get; set;}
    
    /** Required checklist items for each certification type */
    private Map<String,List<String>> RequiredChecklistItemMap;
    
    /** Enumeration of page mode values: READ, EDIT */
    public enum PageMode {READ, EDIT}
    
    /** The mode of the cert admin section:  expected values of 'read' or 'edit' */
    public PageMode mode {get; set;}

    /** 
    * Returns the current mode value
    * @returns mode name
    */
    public String getModeName() {
        if(mode == null) {
            mode = PageMode.READ;
        }
        return mode.name();
    }

    /**
    * Determines if current user can edit the settings
    * @returns true if user can edit; false if not
    */
    public Boolean getCanEdit(Id profileId) {
        Set<String> editorProfileSet = new Set<String>{'System Administrator',
                                                        'C&I - Credit'};
        Profile p = [SELECT Name FROM Profile WHERE Id = :profileId];
        return editorProfileSet.contains(p.Name);
    }

    /** Constructor */
    public CICertAdmin_Extension(ApexPages.StandardController stdController) {
        this.mode = PageMode.READ;
        this.isEditor = false;
        this.opp = getOpportunityDetails(stdController.getRecord().Id);
        this.isEditor = getCanEdit(UserInfo.getProfileId());
        this.RequiredChecklistItemMap = createChecklistItemMap();
    }
    
    //place holder--will need to define manage functions for checklist items
    public String certTypeName {get; set;}
    public PageReference manage() {
        if(certTypeName == null)
            return null;
        PageReference ref = Page.CICertChecklistAdmin;
        ref.getParameters().put('id',opp.Id);
        ref.getParameters().put('ctype', certTypeName);
        ref.setRedirect(false);
        return ref;
    }
    
    private Opportunity getOpportunityDetails(Id oppId) {
        return [
                SELECT
                    Id,
                    CI_Annual_Certification_Required__c,
                    CI_Quarterly_Certification_Required__c,
                    CI_Monthly_Certification_Required__c
                FROM Opportunity
                WHERE Id = :oppId];
    }
    
    public Opportunity editOpp {get; set;}
    
    public PageReference editCertMgmt() {
        editOpp = opp.clone(true, true);
        this.mode = PageMode.EDIT;
        return null;
    }
    
    public PageReference cancelCertMgmt() {
        editOpp = null;
        this.mode = PageMode.READ;
        return null;
    }
    
    public PageReference saveCertMgmt() {
        this.mode = PageMode.READ;
        update editOpp;
        opp = getOpportunityDetails(editOpp.Id);
        editOpp = null;
        return null;
    }
    
    /**
    * Retrieves list of required checklist items
    */
    private Map<String,List<String>> createChecklistItemMap() {
        Map<String,List<String>> returnMap = new Map<String,List<String>>();
        for(C_I_Checklist_Item_Admin__c citem : [
                SELECT Checklist_Item_Name__c, Certification_Type__c
                FROM C_I_Checklist_Item_Admin__c
                WHERE Opportunity__c = :opp.Id
                ORDER BY Checklist_Item_Name__c]) {
            if(!returnMap.containsKey(citem.Certification_Type__c)) {
                returnMap.put(citem.Certification_Type__c, new List<String>());
            }
            returnMap.get(citem.Certification_Type__c).add(citem.Checklist_Item_Name__c);
        }
        return returnMap;
    }
    
    public List<String> getAnnualChecklistItems() {
        return RequiredChecklistItemMap.get('Annual Certification');
    }
    
    public List<String> getQuarterlyChecklistItems() {
        return RequiredChecklistItemMap.get('Quarterly Certification');
    }
    
    public List<String> getMonthlyChecklistItems() {
        return RequiredChecklistItemMap.get('Monthly Certification');
    }
}