objects/CD_Proxy_Account_Campaign_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration settings for the Consumer Deposits Proxy Account Campaign Creation functionality</description>
    <fields>
        <fullName>Campaign_Owner_Id__c</fullName>
        <description>Default owner id for campaigns created</description>
        <inlineHelpText>Enter the User Id of the default campaign owner. If left blank, the user triggering the process will become the owner.</inlineHelpText>
        <label>Campaign Owner Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Record_Type_Id__c</fullName>
        <description>The campaign record type for records created with this process</description>
        <inlineHelpText>Enter the record type id to be used for Campaigns created with this process.</inlineHelpText>
        <label>Campaign Record Type Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_List__c</fullName>
        <description>Comma-delimited list of report ids to be used as the source for campaign creation</description>
        <inlineHelpText>Enter the report id(s) to be used to generate the campaigns/campaign members. Separate each report id with a comma.</inlineHelpText>
        <label>Report Id List</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CD - Proxy Account Campaign Config</label>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <fields>
        <fullName>JHA_RECORD_ID__c</fullName>
        <description>Captures the Record ID from JHA</description>
        <externalId>true</externalId>
        <label>JHA RECORD ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <label>Promo Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Person_Financial_Account_Junction__c.object
<CustomObject>
    <description>Creates a junction between Person Account and Financial Account to create a many-to-many relationship for Consume Deposits</description>
    <fields>
        <fullName>CIF_JHA_LINK__c</fullName>
        <description>Combination of CIF and JHA Unique Id for upserting links</description>
        <externalId>true</externalId>
        <label>CIF JHA LINK</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Person Accounts</relationshipLabel>
        <relationshipName>Person_Financial_Account_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JHA_Record_ID__c</fullName>
        <formula>RIGHT( CIF_JHA_LINK__c , LEN(CIF_JHA_LINK__c) - FIND(&quot;|&quot;, CIF_JHA_LINK__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JHA Record ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Consumer Deposits Person Accounts may be selected</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consumer Deposits Person Accounts</value>
            </filterItems>
            <infoMessage>Only Consumer Deposits Person Accounts may be selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Person_Financial_Account_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Financial Account Link</label>
    <nameField>
        <displayFormat>PFAL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Person Financial Account Link #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Financial Account Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProxyAccountCampaignCreationCtr_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ProxyAccountCampaignCreationCtr_Test {

    @isTest(SeeAllData='true')
    static void testProxyAccountCampaignCreationController() {
        if(CD_Proxy_Account_Campaign_Config__c.getAll().values().size() > 0) {
            //delete current custom setting so that we can perform all necessary testing
            delete CD_Proxy_Account_Campaign_Config__c.getAll().values();
            
            ProxyAccountCampaignCreationController ctr = new ProxyAccountCampaignCreationController();
            System.assertEquals(null, ctr.config);          
        }
        
        //set up sample custom setting
        //Consumer Deposits campaign record type id: 012i0000001APtz
        //Consumer Deposits report with proper first column: 00Oi0000005p46d
        //Sample report with improper first column: 00Oi0000006G5rN
        CD_Proxy_Account_Campaign_Config__c config = new CD_Proxy_Account_Campaign_Config__c();
        config.Name='Test';
        config.Campaign_Owner_Id__c=Userinfo.getUserId();
        config.Campaign_Record_Type_Id__c='012i0000001APtz';
        config.Report_Id_List__c='00Oi0000005p46d,00Oi0000006G5rN';
        insert config;
        
        Account acct = TestDataFactory.createTestPersonAccount();
        //Consumer Deposits Person Account
        acct.RecordTypeId = '012i0000001AblM';
        acct.CIF_Person__c = 'TEST';
        insert acct;
        
        Financial_Account__c fin = new Financial_Account__c();
        fin.JHA_RECORD_ID__c = 'TEST';
        fin.Name = 'Test';
        fin.Open_Date__c = Date.today().addDays(-1);
        fin.Promo_Code__c = 'proxy';
        insert fin;
        
        Person_Financial_Account_Junction__c perfin = new Person_Financial_Account_Junction__c();
        perfin.Person_Account__c = acct.id;
        perfin.Financial_Account__c = fin.id;
        perfin.CIF_JHA_LINK__c = 'TEST|TEST';
        insert perfin;
        
        ProxyAccountCampaignCreationController ctr = new ProxyAccountCampaignCreationController();
        ctr.isTest = true;
        System.assertNotEquals(null, ctr.config);
        System.assertNotEquals(0, ctr.reportStateList.size());
        ctr.createCampaigns();
        
        List<ProxyAccountCampaignCreationController.CampaignReportState> crs = ctr.reportStateList;
        System.assert(true, crs.get(0).IsValidReport);
    }
}