objects/ChatInquiryType__mdt.object
<CustomObject>
    <fields>
        <fullName>AuthenticatedUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authenticated User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BrandName__c</fullName>
        <label>Brand Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Axos</fullName>
                </value>
                <value>
                    <fullName>BankX</fullName>
                </value>
                <value>
                    <fullName>BofiFed</fullName>
                </value>
                <value>
                    <fullName>BofiUSA</fullName>
                </value>
                <value>
                    <fullName>ConsumerDirect</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>Netbank</fullName>
                </value>
                <value>
                    <fullName>UFB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BuisinessUnit__c</fullName>
        <label>Buisiness Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>UDB</fullName>
                </value>
                <value>
                    <fullName>SFR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ButtonToRoute__c</fullName>
        <label>Button to Route</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor_Button</fullName>
                </value>
                <value>
                    <fullName>Advisor_Consumer_Deposits_Button</fullName>
                </value>
                <value>
                    <fullName>Axos_Button</fullName>
                </value>
                <value>
                    <fullName>Axos_Button_Enrollment</fullName>
                </value>
                <value>
                    <fullName>Axos_Button_Enrollment_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Axos_Button_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Axos_Button_LS</fullName>
                </value>
                <value>
                    <fullName>Axos_Button_UDB</fullName>
                </value>
                <value>
                    <fullName>Bank_X_Button</fullName>
                </value>
                <value>
                    <fullName>Bank_X_Button_Enrollment</fullName>
                </value>
                <value>
                    <fullName>Bank_X_Button_Enrollment_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Bank_X_Button_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Bank_X_Button_LS</fullName>
                </value>
                <value>
                    <fullName>Bofi_Fed_Button</fullName>
                </value>
                <value>
                    <fullName>Bofi_USA_Button</fullName>
                </value>
                <value>
                    <fullName>Bofi_USA_Button_LS</fullName>
                </value>
                <value>
                    <fullName>Bofi_USA_Button_UDB</fullName>
                </value>
                <value>
                    <fullName>BofiUSA_Button_Enrollment</fullName>
                </value>
                <value>
                    <fullName>BofiUSA_Button_Enrollment_Logged_In</fullName>
                </value>
                <value>
                    <fullName>BofiUSA_Button_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Consumer_Direct_Button</fullName>
                </value>
                <value>
                    <fullName>Nationwide_Button</fullName>
                </value>
                <value>
                    <fullName>Nationwide_Button_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Nationwide_Button_LS</fullName>
                </value>
                <value>
                    <fullName>Nationwide_Button_UDB</fullName>
                </value>
                <value>
                    <fullName>Netbank_Button</fullName>
                </value>
                <value>
                    <fullName>Netbank_Button_Enrollment</fullName>
                </value>
                <value>
                    <fullName>Netbank_Button_Enrollment_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Netbank_Button_Logged_In</fullName>
                </value>
                <value>
                    <fullName>Netbank_Button_LS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InquiryTypeLabel__c</fullName>
        <label>Inquiry Type Label</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Other New Account Inquiries</fullName>
                </value>
                <value>
                    <fullName>Checking, Savings, or other deposit accounts</fullName>
                </value>
                <value>
                    <fullName>Existing Mortgage, Auto or other loans</fullName>
                </value>
                <value>
                    <fullName>New Online Banking Help</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Chat Inquiry Type</label>
    <pluralLabel>Chat Inquiry Types</pluralLabel>
</CustomObject>

classes/LiveAgent_PreChatDefaultController.cls
public class LiveAgent_PreChatDefaultController {

	public ChatInquiryType__mdt[] chatInquiryTypes { get; private set; }
	public Map<String, LiveChatButton> mapChatButtons { get; private set; }

	public LiveAgent_PreChatDefaultController() {
		chatInquiryTypes = [
			SELECT 
				Id, DeveloperName, AuthenticatedUser__c, BrandName__c, 
				BuisinessUnit__c, ButtonToRoute__c, InquiryTypeLabel__c, DisplayOrder__c
			FROM ChatInquiryType__mdt
			WHERE IsActive__c = true
			ORDER BY DisplayOrder__c ASC
		];

		// Get Chat Button Developer Names
		Set<String> setButtonDevNames = new Set<String>();
		for (ChatInquiryType__mdt inquiryType : chatInquiryTypes) {
			setButtonDevNames.add(inquiryType.ButtonToRoute__c);
		}

		// Get Chat Buttons IDs and map by Developer Name
		LiveChatButton[] chatButtons = [
			SELECT Id, DeveloperName, Queue.Name 
			FROM LiveChatButton 
			WHERE DeveloperName IN :setButtonDevNames 
				AND IsActive = true
		];

		mapChatButtons = new Map<String, LiveChatButton>();
		for (LiveChatButton button : chatButtons) {
			mapChatButtons.put(button.DeveloperName, button);
		}
	}
}