objects/CI_Certification__c.object
<CustomObject>
    <description>Used by C&amp;I</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>C&amp;I Certifications may only be associated with C&amp;I Opportunity records.</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>C&amp;I - AB Participation, C&amp;I - Bridge, C&amp;I - General, C&amp;I - Lender Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Certifications1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Credit Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CICertificationDisplayController.cls
public with sharing class CICertificationDisplayController {
    /** Opportunity record id */
    public String oppId {get; set;}
    
    /** CI Certification record type id */
    public String certRTId {get; set;}
    
    /** CI Certification record type name */
    public String certRecordTypeName {
        get {
            if(certRecordTypeName == null) {
                if(certRTId != null) {
                    RecordType rt = [SELECT Name from RecordType WHERE Id = :certRTId];
                    certRecordTypeName = rt.Name;
                } else {
                    certRecordTypeName = '';
                }
            }
            return certRecordTypeName;
        }
        set;
    }
    
    /** Constructor */
    public CICertificationDisplayController() {
        
    }
    
    /** 
    * Returns formatted block title based on CI Certification record type name
    * @return formatted section block title 
    */
    public String getBlockTitle() {
        return (certRecordTypeName == '') ? '[Undefined Certification Record Type]' : certRecordTypeName + 's';
    }
    
    /**
    * Retrieves CI Certification records for the opportunity based on they're record type
    */
    public List<CI_Certification__c> CertificationList {
        get {
            if(CertificationList == null) {
                CertificationList = [
                                        SELECT Id, Name, Status__c
                                        FROM CI_Certification__c
                                        WHERE Opportunity__c = : oppid AND
                                                RecordTypeId = :certRTId
                                        ORDER BY Name
                                    ];
            }
            return CertificationList;
        }
        set;
    }
}