objects/CI_Certification__c.object
<CustomObject>
    <description>Used by C&amp;I</description>
    <fields>
        <fullName>Certification_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Owner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only C&amp;I users may be Certification Owners</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>startsWith</operation>
                <value>C&amp;I</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>C_I_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>C&amp;I Certifications may only be associated with C&amp;I Opportunity records.</errorMessage>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>C&amp;I - AB Participation, C&amp;I - Bridge, C&amp;I - General, C&amp;I - Lender Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Certifications1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Credit Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C&amp;I Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C&amp;I Certifications</pluralLabel>
    <recordTypes>
        <fullName>Quarterly_Certification</fullName>
        <active>true</active>
        <label>Quarterly Certification</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Phone_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phone_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>Fast Busy</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Ring No Answer</fullName>
                </value>
                <value>
                    <fullName>Spoke to Customer</fullName>
                </value>
                <value>
                    <fullName>VM Confirmed</fullName>
                </value>
                <value>
                    <fullName>VM Full</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>PH-{00}</displayFormat>
        <label>Phone Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Trained_SFDC2__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All new users should receive training and sign-off from their management that they were properly trained in the new business processes established for Salesforce and they have the proper training to use the system.</inlineHelpText>
        <label>Trained?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QLR_Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QTR1</fullName>
                </value>
                <value>
                    <fullName>QTR2</fullName>
                </value>
                <value>
                    <fullName>QTR3</fullName>
                </value>
                <value>
                    <fullName>QTR4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QLR_Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - (AC/ARC/QLR) Creation</fullName>
                    <default>true</default>
                    <label>1 - (AC/ARC/QLR) Creation</label>
                </value>
                <value>
                    <fullName>2 - Documents Received and Complete</fullName>
                </value>
                <value>
                    <fullName>3 - Moody&apos;s Entry</fullName>
                </value>
                <value>
                    <fullName>4 - Analysis (AC/ARC/QLR) Complete</fullName>
                </value>
                <value>
                    <fullName>5 - Analysis (AC/ARC/QLR) Internally Audited</fullName>
                </value>
                <value>
                    <fullName>6 - Signature Submitted (Approved)</fullName>
                </value>
                <value>
                    <fullName>7 - Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <recordTypes>
        <fullName>Account_Certification</fullName>
        <active>true</active>
        <description>Used during the initial certification process</description>
        <label>Account Certification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Recertification</fullName>
        <active>true</active>
        <description>Used annually for recertification</description>
        <label>Account Recertification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quarterly_Certification</fullName>
        <active>true</active>
        <description>Used quarterly</description>
        <label>Quarterly Certification</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WLD_Credit_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Certification__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification</label>
        <referenceTo>WLD_Certification__c</referenceTo>
        <relationshipLabel>Credit Reviews</relationshipLabel>
        <relationshipName>Credit_Reviews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Document Approval</fullName>
                    <default>true</default>
                    <label>Pending Document Approval</label>
                </value>
                <value>
                    <fullName>Complete Package Received</fullName>
                </value>
                <value>
                    <fullName>Moody&apos;s Spreading</fullName>
                </value>
                <value>
                    <fullName>QLR Prep</fullName>
                </value>
                <value>
                    <fullName>Management Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Review</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
/**
 * @description Utility class for creating records to use in unit test classes 
 * @author Mike Crosby, BofI Federal
 */
@isTest
public class TestDataFactory {

  /**
  * Creates basic test Business Account
  * @return test business account record
  */
  public static Account createTestBusinessAccount() {
  	return new Account(Name='Test Account');
  }

  public static Task createTestTaskUDB() {
    Case caseTest = new Case(
      Origin = 'UDB',
      Priority = 'Standard',
      Status = 'New',
      Description = 'Running Test',
      IsVisibleSelfService__c = false,
      recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('UDB Inquiry').getRecordTypeId());

    insert caseTest;
    Task taskTest = new Task(
      WhatId = caseTest.Id,
      Subject = 'This is a test',
      ActivityDate = System.Today(),
      recordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('UDB Comment').getRecordTypeId());

    return taskTest;
  }

  /**
  * Create and insert basic test Business Account record
  * @return test business acount record (Id only)
  */
  public static Account createAndInsertTestBusinessAccount() {
  	Account a = createTestBusinessAccount();
  	insert a;
  	return a;
  }

  /**
  * Creates basic C&I Certification
  * @param opp Opportunity record that Certification is associated with
  * @return test C&I Certification record
  */
  public static CI_Certification__c createTestCICertification(Opportunity opp) {
  	//identify a C&I user to be assigned as Certification Owner
  	User u = [SELECT Id FROM User WHERE Profile.Name LIKE 'C&I%' AND IsActive = true LIMIT 1];
  	CI_Certification__c cert = new CI_Certification__c(Name='Test',
        													Certification_Owner__c=u.Id,
        													Opportunity__c=opp.Id,
        													Status__c='In Credit Review');
    return cert;
  }
  
  /**
  * Create and insert basic C&I Certification
  * @param opp Opportunity record that Certification is associated with
  * @return test C&I Certification record (Id only)
  */
  public static CI_Certification__c createAndInsertTestCICertification(Opportunity opp) {
    CI_Certification__c c = createTestCICertification(opp);
    insert c;
    return c;
  }

  /**
  * Create basic test Contact for the Account specified
  * @param acct Account object containing at least the Account Id
  * @return test Contact record
  */
  public static Contact createTestContact(Account acct) {
  	Contact c = new Contact(AccountId=acct.Id,
  							FirstName='Test',
  							LastName='Contact',
  							Email='testcontact@test.com');
  	return c;
  }
  
  /**
  * Create basic test Lead using record type specified
  * @param recordTypeId record type id for the Lead
  * @param companyName sample company name; supply null value if creating 
  * a Lead to be converted to a Person Account
  * @return test Lead record
  */
  public static Lead createTestLead(String recordTypeId, String companyName) {
  	Lead l = new Lead(RecordTypeId=recordTypeId,
  							FirstName='Test',
  							LastName='Contact',
  							Email='testcontact@test.com');
  	if(companyName != null) {
  		l.Company = companyName;
  	}
  	return l;
  }
  
  /**
  * Create and insert basic test Lead using record type specified
  * @param recordTypeId record type id for the Lead
  * @param companyName sample company name; supply null value if creating 
  * a Lead to be converted to a Person Account
  * @return test Lead record (id only)
  */
  public static Lead createAndInsertTestLead(String recordTypeId, String companyName) {
  	Lead l = TestDataFactory.createTestLead(recordTypeId, companyName);
  	
  	insert l;
  	return l;
  }
  
  /**
  * Creates basic test Person Account record
  * @return test person account record
  */
  public static Account createTestPersonAccount() {
  	return new Account(FirstName='Test', LastName='Person');
  }
  
  /**
  * Create and insert basic test Person Account record
  * @return test person acount record (Id only)
  */
  public static Account createAndInsertTestPersonAccount() {
  	Account a = createTestPersonAccount();
  	insert a;
  	return a;
  }

  /**
  * Creates test Phone Number for specified Account
  * @param acct master account record for phone number
  * @return test phone number record
  */
  public static Phone_Number__c createTestPhoneNumber(Account acct) {
  	Phone_Number__c pn = new Phone_Number__c(Account_Name__c = acct.Id, Phone_Number__c = '(858) 649-2000');
  	return pn;
  }

  /**
  * Creates and insert test Phone Number for specified Account
  * @param acct master account record for phone number
  * @return test phone number record (Id only)
  */
  public static Phone_Number__c createAndInsertTestPhoneNumber(Account acct) {
  	Phone_Number__c pn = createTestPhoneNumber(acct);
  	insert pn;
  	return pn;
  }

  /**
  * Creates test Task for specified record
  * @param what master record for task
  * @return new task
  */
  public static Task createTestTask(sObject what) {
  	return createTestTask(what, 1, false).get(0);
  }
  
  /**
  * Creates test Task for specified record
  * @param what master record for task
  * @param cnt number of tasks to create
  * @return new task
  */
  public static Task createTestTask(sObject what, Integer cnt) {
  	return createTestTask(what, cnt, false).get(0);
  }

  /**
  * Creates test Tasks for specified record
  * @param what master record for tasks
  * @param cnt number of tasks to create
  * @param isWho if true, uses what param to populate as Who; otherwise, populates as What
  * @return list of new tasks
  */
  public static List<Task> createTestTask(sObject what, Integer cnt, Boolean isWho) {
  	List<Task> returnList = new List<Task>();
  	for(Integer i=0; i <= cnt; i++) {
  	  Task t = new Task(Subject='Test Task ' + i, Priority='Low', Status='New', Type='Call', CallType='Outbound', ActivityDate=Date.today());
  	  if(isWho) {
  	  	t.WhoId = what.Id;
  	  } else {
  	  	t.WhatId = what.Id;
  	  }
  	  returnList.add(t);
  	}
  	return returnList;
  }
  
  /**
  * Creates and inserts test users for each profile name provided
  * @param profileNameSet set of profile names to use for the test users
  * @return list of new User ids that were created based on the supplied profile names
  */
  public static List<User> createTestUsers(Set<String> profileNameSet) {
  	List<User> toInsert = new List<User>();
  	
  	//retrieve profiles for the list of profile names provided
  	Map<String,Profile> profileNameMap = new Map<String,Profile>();
  	for(Profile p : [Select Id, Name From Profile Where Name IN :profileNameSet OR Name = 'System Administrator']) {
  		profileNameMap.put(p.Name, p);
  	}
  	Profile adminProfile = profileNameMap.get('System Administrator');
  	User adminU = new User(
                        FirstName='Test',
                        LastName='UserAdmin',
                        Alias='tuseradm',
                        Email='tuseradm@test.org',
                        Username='tuseradm@test.org',
                        CommunityNickname='tuseradm',
                        ProfileId=adminProfile.Id,
                        TimeZoneSidKey='America/Los_Angeles',
                        LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US',
                        EmailEncodingKey='ISO-8859-1',
                        Department='Test',
                        Division='Test',
                        Trained_SFDC2__c=true);
    insert adminU;
  	Integer index = 0;
  	
    for(String profileName : profileNameSet) {
      index++;
      Profile p = profileNameMap.get(profileName);
      
      if(p == null) {
      	throw new TestDataFactoryException('Unknown profile name: ' + profileName);
      }
      
      User u = new User(
                        FirstName='Test',
                        LastName='User' + profileName,
                        Alias='tuser' + index,
                        Email='tuser' + index+ '@test.org',
                        Username='tuser' + index + '@test.org.' + index,
                        CommunityNickname='tuser' + index,
                        ProfileId=p.Id,
                        TimeZoneSidKey='America/Los_Angeles',
                        LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US',
                        EmailEncodingKey='ISO-8859-1',
                        Department='Test',
                        Division='Test',
                        Trained_SFDC2__c=true);
      if(profileName == 'Enterprise User') {
      	u.ManagerId = adminU.Id;
      }
      toInsert.add(u);
    }
    
    try {
    	insert toInsert;
    	return toInsert;
    }
    catch(Exception e) {
    	throw new TestDataFactoryException('Error inserting test users: ' + e.getMessage());
    }
  }
  
  public enum CertificationType {ACCOUNT, RECERTIFICATION, QUARTERLY}
  
  /**
  * Creates Certification record for specified Account and type
  * @param acct Account to associate certification with
  * @param cType CertificationType
  * @return test Certification record
  */
  public static WLD_Certification__c createTestCertification(Account acct, CertificationType cType) {
    Map<CertificationType, RecordType> certRTMap = new Map<CertificationType, RecordType>();
    for(RecordType rt : [
                SELECT DeveloperName
                FROM RecordType
                WHERE SobjectType = 'WLD_Certification__c'
                ]) {
      if(rt.DeveloperName == 'Account_Certification') {
        certRTMap.put(CertificationType.ACCOUNT, rt);
      } else if (rt.DeveloperName == 'Account_Recertification') {
        certRTMap.put(CertificationType.RECERTIFICATION, rt);
      } else if (rt.DeveloperName == 'Quarterly_Certification') {
        certRTMap.put(CertificationType.QUARTERLY, rt);
      }
    }
    
    WLD_Certification__c cert = new WLD_Certification__c(Name='Test',Account__c=acct.Id,RecordTypeId=certRTMap.get(cType).Id, QLR_Year__c=String.valueOf(Date.today().year()));
    
    if(cType == CertificationType.QUARTERLY) {
      cert.QLR_Quarter__c = 'QTR 1';
    }
    
    return cert;
  }

  /**
  * Creates and inserts Certification record for specified Account and type
  * @param acct Account to associate certification with
  * @param cType CertificationType
  * @return test Certification record (id only)
  */
  public static WLD_Certification__c createAndInsertTestCertification(Account acct, CertificationType cType) {
    WLD_Certification__c c = createTestCertification(acct, cType);
    insert c;
    return c;
  }
  
  /**
  * Create basic test Credit Review for the Certification specified
  * @param cert Certification object containing at least the Certification Id
  * @return test Credit Review record
  */
  public static WLD_Credit_Review__c createTestCreditReview(WLD_Certification__c cert) {
    WLD_Credit_Review__c c = new WLD_Credit_Review__c(Certification__c=cert.Id,
                Name='Test',
                Credit_Status__c='Pending Approval');
    return c;
  }
  
  public class SingleRequestMock implements HttpCalloutMock {
		protected Integer code;
		protected String status;
		protected String bodyAsString;
		protected Blob bodyAsBlob;
		protected Map<String, String> responseHeaders;

		public SingleRequestMock(Integer code, String status, String body,
                                         Map<String, String> responseHeaders) {
			this.code = code;
			this.status = status;
			this.bodyAsString = body;
			this.bodyAsBlob = null;
			this.responseHeaders = responseHeaders;
		}

		public SingleRequestMock(Integer code, String status, Blob body,
                                         Map<String, String> responseHeaders) {
			this.code = code;
			this.status = status;
			this.bodyAsBlob = body;
			this.bodyAsString = null;
			this.responseHeaders = responseHeaders;
		}

	    public HTTPResponse respond(HTTPRequest req) {
	        HttpResponse resp = new HttpResponse();
			resp.setStatusCode(code);
			resp.setStatus(status);
			if (bodyAsBlob != null) {
				resp.setBodyAsBlob(bodyAsBlob);
			} else {
				resp.setBody(bodyAsString);
			}

			if (responseHeaders != null) {
			     for (String key : responseHeaders.keySet()) {
				resp.setHeader(key, responseHeaders.get(key));
			     }
			}
			return resp;
	    }
	}
  
  public class TestDataFactoryException extends Exception {}
}