objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CIF_SFDC2__c</fullName>
        <description>New field for SFDC 2.0 project as defined by the &quot;SFDC 2.0 Fields&quot; document.</description>
        <externalId>true</externalId>
        <label>CIF</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business_SFDC2</fullName>
        <active>true</active>
        <label>Business SFDC2</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CaseTriggerHandler_test.cls
@isTest
public class CaseTriggerHandler_test {
  
    @isTest    
    static void testUpdateFutureDateOrStartDate() {
        Test.startTest();

          Financial_Account__c  f_acc = new Financial_Account__c ();
          f_acc.Name = 'financial Acc Test';
          insert f_acc;
        
      Datetime dtF  = System.now();
      Case caseTest = new Case();
      caseTest.Subject = 'Test Case';
      caseTest.Priority = 'VIP';
      caseTest.Status = 'New';
      caseTest.Origin = 'Web';
      caseTest.Future_Action_Date__c = dtF+5;
      insert caseTest;
         
      Case caseTest2 = new Case();
      caseTest2.Subject = 'Test Case';
      caseTest2.Priority = 'VIP';
      caseTest2.Status = 'New';
      caseTest2.Origin = 'Web';
      insert caseTest2;
        

      Test.stopTest();
        
  }    
    
    
    @isTest    
    static void testCIFUpDate() {
        Test.startTest();

        
        Id accid = [Select id from RecordType where DeveloperName = 'Business_Account_SFDC2' limit 1].Id;
        Id conid = [Select id from RecordType where DeveloperName = 'Business_SFDC2' limit 1].Id;
        Id caseid = [Select id from RecordType where DeveloperName = 'UDB_Inquiry' limit 1].Id;  
        
        Account acc = new Account ();
        acc.Name = 'TestCase';
        acc.CIF_SFDC2__c = '123XYZ';
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont';
        cont.CIF_SFDC2__c = '123XYZ';
        cont.AccountId = acc.Id;
        insert cont;

      Datetime dtF  = System.now();
      Case caseTest = new Case();
      caseTest.RecordTypeId = caseId;  
      caseTest.Subject = 'Test Case';
      caseTest.Priority = 'Standard';
      caseTest.Status = 'New';
      caseTest.Origin = 'UDB';
      caseTest.UDB_CIF__c = '123XYZ';
      insert caseTest;
         

        

      Test.stopTest();
        
  }

}