objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MarketoAuthCreds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Creds to get the Marketo&apos;s access token</description>
    <label>Marketo Login</label>
</CustomObject>

objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advance</fullName>
                </value>
                <value>
                    <fullName>Advance Review</fullName>
                </value>
                <value>
                    <fullName>Annuity Schedule</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy/Lien</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Case Search</fullName>
                </value>
                <value>
                    <fullName>Certified Court Orders</fullName>
                </value>
                <value>
                    <fullName>Claim Findings Review</fullName>
                </value>
                <value>
                    <fullName>Confirm FVR</fullName>
                </value>
                <value>
                    <fullName>Contact Info Request</fullName>
                </value>
                <value>
                    <fullName>Create New Account</fullName>
                </value>
                <value>
                    <fullName>Credit Report</fullName>
                </value>
                <value>
                    <fullName>Divorce Decree</fullName>
                </value>
                <value>
                    <fullName>Doc Request</fullName>
                </value>
                <value>
                    <fullName>Doc Request Review</fullName>
                </value>
                <value>
                    <fullName>Draft Order Review</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>FOIA Request</fullName>
                </value>
                <value>
                    <fullName>FVR Request</fullName>
                </value>
                <value>
                    <fullName>Gift Card</fullName>
                </value>
                <value>
                    <fullName>Identity Report</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing Note</fullName>
                </value>
                <value>
                    <fullName>Mail Processing</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Misc. Doc Review</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pleadings Review</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Processing Notes</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDB_SecureMessagingMarketoMethods_tst.cls
/***

    Author: René Ayala Medina
    Description: Test class to validate the integration SFDC - Marketo to send alerts when a secure message is created.
    
    Version Developer             Date          Description
    0.1     René Ayala Medina RAM 05/02/2018    Class created
    0.2     René Ayala Medina RAM 05/02/2018    Building the class
    1.0     René Ayala Medina RAM 06/07/2018    Documentation and testing
    1.1     René Ayala Medina RAM 06/11/2018    New test methods and testing (update lead brand)

***/

@isTest
private class UDB_SecureMessagingMarketoMethods_tst {

    /*
        Method to initialized the test data
    */
    
    @testSetup static void initData(){
        List<Contact> lstContactsToInsert = new List<Contact>{
            new Contact(
                FirstName = 'Test',
                LastName = 'Contact 1',
                Email = 'test@emil1.com'
            ),
            new Contact(
                FirstName = 'Test',
                LastName = 'Contact 2',
                Email = 'test@emil2.com'
            )
        };
        Database.insert(lstContactsToInsert);
        List<Case> lstCasesToInsert = new List<Case>{
            new Case(
                Subject = 'Test case 1',
                Status = 'New',
                ContactId = lstContactsToInsert.get(0).Id,
                UDB_CIF__c = 'XXX215',
                Brand__c = 'Bank x'
            ),
            new Case(
                Subject = 'Test case 1',
                Status = 'New',
                ContactId = lstContactsToInsert.get(1).Id,
                UDB_CIF__c = 'XXX213',
                Brand__c = 'Bank x'
            )
        };
        Database.insert(lstCasesToInsert);
    }

    /*
        The scenario where the message is -successfully- sent is validated #0.
    */
    
    @isTest static void shouldSendMessage0() {
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        The scenario where the message is -successfully- sent is validated #1.
    */
    
    @isTest static void shouldSendMessage1() {
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 5;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = false;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        The scenario where the message is -successfully- sent is validated #2.
    */
    
    @isTest static void shouldSendMessage2() {
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 5;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    } 

    /*
        Method that validates when the access token fails getting retrieved #0
    */

    @isTest static void shouldNotRetrieveAccToken0() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 0;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the access token fails getting retrieved #1
    */

    @isTest static void shouldNotRetrieveAccToken1() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead ID fails getting retrieved #0
    */

    @isTest static void shouldNotRetrieveLeadID0() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 0;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead ID fails getting retrieved #1
    */

    @isTest static void shouldNotRetrieveLeadID1() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 2;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead ID fails getting retrieved #2
    */

    @isTest static void shouldNotRetrieveLeadID2() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 3;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead ID fails getting retrieved #3
    */

    @isTest static void shouldNotRetrieveLeadID3() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 4;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead brand update fails #0
    */

    @isTest static void shouldNotUpdateLeadBrandID0() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 0;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead brand update fails #1
    */

    @isTest static void shouldNotUpdateLeadBrandID1() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 2;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead brand update fails #2
    */

    @isTest static void shouldNotUpdateLeadBrandID2() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 3;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the lead brand update fails #3
    */

    @isTest static void shouldNotUpdateLeadBrandID3() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 4;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaing ID fails getting retrieved #0
    */

    @isTest static void shouldNotRetrieveCampaignID0() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 0;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaing ID fails getting retrieved #1
    */

    @isTest static void shouldNotRetrieveCampaignID1() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 2;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaing ID fails getting retrieved #2
    */

    @isTest static void shouldNotRetrieveCampaignID2() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 3;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaing ID fails getting retrieved #3
    */

    @isTest static void shouldNotRetrieveCampaignID3() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 4;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaign isn't retrieved #0
    */

    @isTest static void shouldNotTriggerCampaign0() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 0;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaign isn't retrieved #1
    */

    @isTest static void shouldNotTriggerCampaign1() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 2;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaign isn't retrieved #2
    */

    @isTest static void shouldNotTriggerCampaign2() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 3;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        Method that validates when the campaign isn't retrieved #3
    */

    @isTest static void shouldNotTriggerCampaign3() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        UDB_SecureMessagingMarketoMethods_cls.testModeWS0 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS1 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS2 = 1;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS3 = 4;
        UDB_SecureMessagingMarketoMethods_cls.testModeWS4 = 1;
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
            ActivityDate__c = Date.today(),
            Assigned_To__c = UserInfo.getUserId(),
            Description__c = 'Test',
            Priority__c = 'Normal',
            Status__c = 'In Progress',
            Type__c = 'Call',
            Related_To__c = lstCases.get(0).Id,
            Name__c = lstContacts.get(0).Id
        );
        Test.startTest();
            Database.insert(secureMessageInstance);
            UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
        Test.stopTest();
    }

    /*
        The scenario where the message is not send due to the user (UDB integration) is validated.
    */

    @isTest static void shouldNotTriggerMessageSending() {
        UDB_SecureMessagingMarketoMethods_cls.blnIsProductiveOrgSetTest = true;
        Test.loadData(MarketoAuthCreds__c.SObjectType, 'MarketoAuthCSV');
        List<Case> lstCases = [SELECT Id FROM Case];
        List<Contact> lstContacts = [SELECT Id FROM Contact];
        User udbIntegrationUserInstance = new User();
        try{udbIntegrationUserInstance = [SELECT Id, Name FROM User WHERE FirstName =: 'UDB' AND LastName =: 'Integration'];}catch(QueryException qE){}catch(UnexpectedException uE){}catch(Exception gE){}
        if(udbIntegrationUserInstance.Id != null){
            List<SObject> lstSOs = new List<SObject>();
            for(Case iterator:lstCases){
                iterator.OwnerId = udbIntegrationUserInstance.Id;
                lstSOs.add(iterator);
            }
            for(Contact iterator:lstContacts){
                iterator.OwnerId = udbIntegrationUserInstance.Id;
                lstSOs.add(iterator);
            }
            Database.update(lstSOs);
            System.runAs(udbIntegrationUserInstance){
                UDB_Secure_Messaging__c secureMessageInstance = new UDB_Secure_Messaging__c(
                    ActivityDate__c = Date.today(),
                    Assigned_To__c = UserInfo.getUserId(),
                    Description__c = 'Test',
                    Priority__c = 'Normal',
                    Status__c = 'In Progress',
                    Type__c = 'Call',
                    Related_To__c = lstCases.get(0).Id,
                    Name__c = lstContacts.get(0).Id
                );
                Test.startTest();
                    Database.insert(secureMessageInstance);
                    UDB_SecureMessagingMarketoMethods_cls.sendMarketoEmail(new List<Id>{secureMessageInstance.Id});
                Test.stopTest();
            }
        }
    }

    /*
        Sub-wrappers are covered since there is no way to cover them in an ordinary flow
    */

    @isTest static void instantiateRemainingWrappers() {
        UDB_SecureMessagingMarketoMethods_cls.CampaignQueryResult campaignQueryResultInstance = new UDB_SecureMessagingMarketoMethods_cls.CampaignQueryResult();
        UDB_SecureMessagingMarketoMethods_cls.LeadIdResult leadIdResultInstance = new UDB_SecureMessagingMarketoMethods_cls.LeadIdResult();
        UDB_SecureMessagingMarketoMethods_cls.TriggerCampaignResult triggerCampaignResultInstance = new UDB_SecureMessagingMarketoMethods_cls.TriggerCampaignResult();
        UDB_SecureMessagingMarketoMethods_cls.WSError wSErrorInstance = new UDB_SecureMessagingMarketoMethods_cls.WSError();
        UDB_SecureMessagingMarketoMethods_cls.UpdtLeadReslt updtLeadResltInstance = new UDB_SecureMessagingMarketoMethods_cls.UpdtLeadReslt();
    }
    
}