objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Read__c</fullName>
        <label>Customer Read</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDBCaseHistory.cls
@RestResource(urlMapping='/UDBCaseHistory/*')
global with sharing class UDBCaseHistory {
    @HttpGet
    global static Case getUDBCaseDetail(){
        RestRequest request = RestContext.request;
        RestResponse res = RestContext.response;
        String cid =  request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);

        List<Case> caseHistory;

        if(cid != null && cid != '') {
            caseHistory = [SELECT casenumber, subject, contact.name, contact.email,LastReferencedDate,UDB_Case_Description__c,Status,CreatedDate, UDB_Subject__c, IsVisibleSelfService__c,                       
                       (SELECT CreatedBy.Name, CreatedDate, Field, NewValue, OldValue                     FROM Histories    ORDER BY CreatedDate      ASC),
                       (SELECT CreatedBy.Name, CreatedDate, Name                                          FROM Attachments  ORDER BY CreatedDate      ASC),
                       (SELECT Owner.Name, ActivityDateTime, Subject, IsVisibleInSelfService              FROM Events       WHERE ActivityDateTime <=:System.Now()   ORDER BY ActivityDateTime ASC),
                      (select Owner.Name, LastModifiedDate, Name, Description__c, Customer_Read__c       from Case.UDB_Secure_Messagings__r where ActivityDate__c <=:System.Today() order by LastModifiedDate) 
                FROM Case 
                WHERE id =:cid];

        }
        if(caseHistory.size() > 0) {
            return caseHistory[0];
        }
        else {
            res.statusCode = 404;
            return null;
        }
    }
}