objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email_SFDC2__c.object
<CustomObject>
    <description>SFDC2 Email  objects are used to allow storing an unlimited number of current and historical email addresses for Leads and Personal Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Email_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <description>Type of email. Will not necessarily match Parent Record Type, e.g. an employee contact with a Person Account could have an Email with Parent Record Type = &apos;Personal&apos; and Email Type = &apos;Primary Business&apos;</description>
        <label>Email Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Personal</fullName>
                </value>
                <value>
                    <fullName>Primary Business</fullName>
                </value>
                <value>
                    <fullName>Other Personal</fullName>
                    <default>true</default>
                    <label>Other Personal</label>
                </value>
                <value>
                    <fullName>Other Business</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>JH Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to associated Lead record</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Email_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>EML-{0000}</displayFormat>
        <label>Email Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailSfdc2TriggerHandler.cls
/**
 * @description <P>Handler class for Email_SFDC2__c object functionality
 * @author Matt Dawson, BofI Federal
 */
public class EmailSfdc2TriggerHandler extends TriggerHandler {
    
    /** Map of new/updated Email_SFDC2__c objects with changes */
    private Map<Id, Email_SFDC2__c> newEmailMap;
    
    /** Map of updated/deleted Email_SFDC2__c objects without changes */
    private Map<Id, Email_SFDC2__c> oldEmailMap;

	/** List of new/update Email_SFDC2__c objects with changes */
	private List<Email_SFDC2__c> newEmailList;
    
    /** Profile Id for System Admins **/
    private static Id adminProfileId = '00ei0000000qJ9OAAU';

    /** Constructor */
    public EmailSfdc2TriggerHandler() {
    	this.newEmailMap = (Map<Id, Email_SFDC2__c>) Trigger.newMap;
		this.oldEmailMap = (Map<Id, Email_SFDC2__c>) Trigger.oldMap;
		this.newEmailList = (List<Email_SFDC2__c>) Trigger.new;
    }
    
    /** Process the after insert logic */
    public override void afterInsert() {
    	updatePrimaryEmailAddresses(this.newEmailMap);
    }
    
    /** Process the after update logic */
    public override void afterUpdate() {
    	updatePrimaryEmailAddresses(this.newEmailMap);    	
    }

    /** Process before insert logic */
    public override void beforeInsert() {
    	blockJhEmailInserts();
    }

	/** Process before update logic */
	public override void beforeUpdate() {
		blockJhEmailChanges();
    	blockJhEmailInserts();
	}

	/** Process before delete logic */
	public override void beforeDelete() {
		blockJhEmailChanges();
	}
    
    /**
     * Block changes to a JH Email record
     */
    private void blockJhEmailChanges() {
    	for (Email_SFDC2__c email : this.oldEmailMap.values()) {
    		if (email.Email_Type__c == null) continue;
    		if (email.Email_Type__c.equals('JH Email') && UserInfo.getProfileId() != adminProfileId) {
    			if (Trigger.isDelete) {
   					email.addError('JH Email objects cannot be changed or deleted.');
    			} else {
   					this.newEmailMap.get(email.Id).addError('JH Email objects cannot be changed or deleted.');
    			}
    		}
    	}
    }
    
    /**
     * Block inserts of JH Email records
     */
    private void blockJhEmailInserts() {
    	for (Email_SFDC2__c email : this.newEmailList) {
    		if (email.Email_Type__c == null) continue;
    		if (email.Email_Type__c.equals('JH Email') && UserInfo.getProfileId() != adminProfileId) {
    			email.addError('JH Email objects cannot created manually.');
    		}
    	}
    }
    
    /**
     * Check Email_SFDC2__c objects for 'Primary' type and update master record
     * primary email fields.
     * @param newEmailMap map of new/updated email objects
     */
    private void updatePrimaryEmailAddresses(Map<Id, Email_SFDC2__c> newEmailMap) {
    	
		// List of Emails with Account and Lead ids
        List<Email_SFDC2__c> emails = [select Account__r.Id, Lead__r.Id from Email_SFDC2__c where id IN :newEmailMap.keySet()];

        // List of Account Ids associated with email addresses
		List<Id> accountIds = new List<Id>();
		for (Email_SFDC2__c email: emails) accountIds.add(email.Account__r.Id);
        
        // List of Accounts to update
    	List<Account> accountsToUpdate = new List<Account>();
   	
     	// Set appropriate Account primary email field values
    	for (Account account : [select id, PersonEmail, Business_Email_SFDC2__pc, isPersonAccount,
							    	(select id, Email__c, Email_Type__c from Email_Addresses__r where id IN :newEmailMap.keySet())
  									 from Account where id IN :accountIds and SFDC2__c = true ]) {
			boolean updateAccount = false;
			for (Email_SFDC2__c email : account.Email_Addresses__r) {
				if (email.Email_Type__c.equals('Primary Personal')) {
					account.PersonEmail = email.Email__c;
					updateAccount = true;
				} else if (email.Email_Type__c.equals('Primary Business')) {
					if (account.isPersonAccount) {
						account.Business_Email_SFDC2__pc = email.Email__c;
						updateAccount = true;
					} else {
						account.Email__c = email.Email__c;
						updateAccount = true;
					}
				}
			}
			if (updateAccount) accountsToUpdate.add(account);
    	}
    	
    	update accountsToUpdate;

        // List of Lead Ids associated with email addresses
		List<Id> leadIds = new List<Id>();
		for (Email_SFDC2__c email: emails) leadIds.add(email.Lead__r.Id);
        
        // List of Leads to update
    	List<Lead> leadsToUpdate = new List<Lead>();

     	// Set appropriate Lead primary email field values
    	for (Lead lead : [select id, Email,
							(select id, Email__c, Email_Type__c from Email_Addresses__r where id IN :newEmailMap.keySet())
  							from Lead where SFDC2__c = true and IsConverted = false and id IN :leadIds ]) {
			Boolean updateLead = false;
			for (Email_SFDC2__c email : lead.Email_Addresses__r) {
				if (email.Email_Type__c.equals('Primary Personal')) {
					lead.Email = email.Email__c;
					updateLead = true;
				} else if (email.Email_Type__c.equals('Primary Business')) {
					lead.Email = email.Email__c;
					updateLead = true;
				}
			}
			if (updateLead) leadsToUpdate.add(lead);
    	}
    	
    	update leadsToUpdate;

    }  

    
}