objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <fields>
        <fullName>JHA_RECORD_ID__c</fullName>
        <description>Captures the Record ID from JHA</description>
        <externalId>true</externalId>
        <label>JHA RECORD ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Person_Financial_Account_Junction__c.object
<CustomObject>
    <description>Creates a junction between Person Account and Financial Account to create a many-to-many relationship for Consume Deposits</description>
    <fields>
        <fullName>CIF_JHA_LINK__c</fullName>
        <description>Combination of CIF and JHA Unique Id for upserting links</description>
        <externalId>true</externalId>
        <label>CIF JHA LINK</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Person Accounts</relationshipLabel>
        <relationshipName>Person_Financial_Account_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JHA_Record_ID__c</fullName>
        <formula>RIGHT( CIF_JHA_LINK__c , LEN(CIF_JHA_LINK__c) - FIND(&quot;|&quot;, CIF_JHA_LINK__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JHA Record ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Consumer Deposits Person Accounts may be selected</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consumer Deposits Person Accounts</value>
            </filterItems>
            <infoMessage>Only Consumer Deposits Person Accounts may be selected</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Person_Financial_Account_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Financial Account Link</label>
    <nameField>
        <displayFormat>PFAL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Person Financial Account Link #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Financial Account Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountFinancialJunctionBatch.cls
global class AccountFinancialJunctionBatch implements Database.Batchable<sObject> {
	Map<Id, Person_Financial_Account_Junction__c> juncMap;

	global AccountFinancialJunctionBatch(Map<Id, Person_Financial_Account_Junction__c> juncMap) {
		this.juncMap = juncMap;
	}
	
	//Query method.
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Id, CIF_JHA_LINK__c, Person_Account__c, Financial_Account__c FROM Person_Financial_Account_Junction__c WHERE Id IN : juncMap.keySet()]);
	}
	
	//Execute Method.
	global void execute(Database.BatchableContext BC, List<Person_Financial_Account_Junction__c> juncList) {
		List<String> acctCifList = new List<String>();
		List<String> finJhaList = new List<String>();
		for(Person_Financial_Account_Junction__c junc : juncList) {
			String[] idArray = junc.CIF_JHA_LINK__c.split('\\|');
			acctCifList.add(idArray[0]);
			finJhaList.add(idArray[1]);
		}
		Map<String, Id> acctCifSfMap = new Map<String, Id>();
		for(Account acct : [SELECT Id, CIF_Person__c FROM Account WHERE RecordTypeId = '012i0000001AblM' AND CIF_Person__c IN :acctCifList]) {
			acctCifSfMap.put(acct.CIF_Person__c, acct.Id);
		}
		Map<String, Id> finJhaSfMap = new Map<String, Id>();
		for(Financial_Account__c fin : [SELECT Id, JHA_RECORD_ID__c FROM Financial_Account__c WHERE JHA_RECORD_ID__c IN :finJhaList]) {
			finJhaSfMap.put(fin.JHA_RECORD_ID__c, fin.Id);
		}
		List<Person_Financial_Account_Junction__c> toUpdate = new List<Person_Financial_Account_Junction__c>();
		for(Person_Financial_Account_Junction__c junc : juncList) {
			String[] idArray = junc.CIF_JHA_LINK__c.split('\\|');
			String acctId = acctCifSfMap.get(idArray[0]);
			String finId = finJhaSfMap.get(idArray[1]);
			if(acctId != null && finId != null) {
				junc.Person_Account__c = acctId;
				junc.Financial_Account__c = finId;
				toUpdate.add(junc);
			}
		}
		if(toUpdate.size() > 0) {
			update toUpdate;
		}
	}
	
	//Finish method to execute at last.
	global void finish(Database.BatchableContext BC) {
		//Send an email to the User after your batch completes
		/*Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] toAddresses = new String[] {'salesforcesupport@bofi.com'};
		mail.setToAddresses(toAddresses);
		mail.setSubject('Salesforce: Consumer Deposits Data Load Completed');
		mail.setPlainTextBody('The batch Apex Job Processed Successfully');
		try {
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		} catch (Exception e) {}*/
	}
}