objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Escheat</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>New Today</fullName>
                </value>
                <value>
                    <fullName>Pending Close</fullName>
                </value>
                <value>
                    <fullName>Restricted</fullName>
                </value>
                <value>
                    <fullName>No Post</fullName>
                </value>
                <value>
                    <fullName>Charged Off</fullName>
                </value>
                <value>
                    <fullName>No Credits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account_Contact_Link_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Creates a many-to-many junction between Contacts or Person Accounts and Financial Accounts</description>
    <fields>
        <fullName>CIF_JHA_LINK__c</fullName>
        <description>Combination of CIF and JHA Unique Id for upserting links</description>
        <externalId>true</externalId>
        <label>CIF JHA LINK</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact or Person Account related to this link</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account_SFDC2__c</referenceTo>
        <relationshipLabel>Business/Consumer Contacts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <formula>Financial_Account__r.Maturity_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Financial_Account__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Contact Link</label>
    <nameField>
        <displayFormat>FACL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Contact Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contact Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_SFDC2__c.object
<CustomObject>
    <description>Used to capture customer financial account information for SFDC 2.0 integration</description>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <label>Product Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>CD</fullName>
        <active>true</active>
        <label>CD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FinAcctContactLinkTriggerHandler_test.cls
@isTest
private class FinAcctContactLinkTriggerHandler_test {
	@isTest
    static void testHandleCampaignAutomation() {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer Person Account SFDC2').getRecordTypeId();
        Id finRTId = Schema.SObjectType.Financial_Account_SFDC2__c.getRecordTypeInfosByName().get('CD').getRecordTypeId();
		
		Account acct = new Account();
		acct.LastName = 'Test';
		acct.RecordTypeId = acctRTId;
		acct.Occupation_SFDC2__pc = 'Tester';
		acct.PersonDoNotCall = false;
		insert acct;
		acct = [SELECT Person_Contact_Id__c FROM Account WHERE Id = :acct.Id];
		
		Financial_Account_SFDC2__c fa = new Financial_Account_SFDC2__c();
		fa.Name = 'TEST 0000';
		fa.Status__c = 'Active';
		fa.Product_Class__c = 'CD';
		fa.RecordTypeId = finRTId;
		fa.Maturity_Date__c = Date.today().addDays(30);
		insert fa;
		
		Financial_Account_Contact_Link_SFDC2__c link = new Financial_Account_Contact_Link_SFDC2__c();
		link.Financial_Account__c = fa.Id;
		link.Contact__c = acct.Person_Contact_Id__c;
		link.CIF_JHA_LINK__c = '30DayCDTEST1111';
		
		Test.startTest();
		insert link;
		Test.stopTest();
    }
}