objects/Financial_Account_Contact_Link_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Creates a many-to-many junction between Contacts or Person Accounts and Financial Accounts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact or Person Account related to this link</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account_SFDC2__c</referenceTo>
        <relationshipLabel>Business/Consumer Contacts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Relationship of business contact to financial account</description>
        <label>Relationship</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Financial Account Contact Link</label>
    <nameField>
        <displayFormat>FACL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Contact Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contact Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_Link_SFDC2__c.object
<CustomObject>
    <description>Creates a junction between Account and Financial Account to create a many-to-many relationship, SFDC2</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account_SFDC2__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Relationship of individual or business to financial account</description>
        <label>Relationship</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Financial Account Link</label>
    <nameField>
        <displayFormat>FAL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_SFDC2__c.object
<CustomObject>
    <description>Used to capture customer financial account information for SFDC 2.0 integration</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>JH_Master_Table__c</fullName>
        <label>JH Master Table</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>CD</fullName>
        <active>true</active>
        <label>CD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountSFDC2RollupSummaryExtension.cls
/**
 * Controller Extension for SFDC2 Financial Account Rollup Summary
 * for Business and Person Accounts. Includes all JH financial accounts
 */
public with sharing class AccountSFDC2RollupSummaryExtension {

    // Current Account
    private Account account;
    
    // Total open deposit accounts
    public Integer numDepositAccounts{get; set;}

    // Total open CD accounts
    public Integer numCDAccounts{get; set;}
    
	// Total open loan accounts
    public Integer numLoanAccounts{get; set;}
    
    // Balance of deposit accounts
    public Decimal balanceDepositAccounts{get; set;}
    
    // Balance of CD accounts
    public Decimal balanceCDAccounts{get; set;}

    // Balance of loan accounts
    public Decimal balanceLoanAccounts{get; set;}
    
    // Number of all-time Opportunities
    public Integer numLTDOpportunities{get; set;}
    
    // Number of Opportunities created during this quarter
    public Integer numQTDOpportunities{get; set;}
    
    // Number of completed tasks of type 'call' all-time
    public Integer numLTDCalls{get; set;}
    
    // Number of completed tasks of type 'call' this quarter
    public Integer numQTDCalls{get; set;}
    
    // Constructor
    public AccountSFDC2RollupSummaryExtension(ApexPages.StandardController ctr) {
        account = [SELECT Id, IsPersonAccount, PersonContactId FROM Account WHERE Id = :((Account)ctr.getRecord()).Id];
     
     	List<Financial_Account_Link_SFDC2__c> links = null;
     	List<Financial_Account_Contact_Link_SFDC2__c> contact_links = null;
     	
    	if (!account.IsPersonAccount) {
	         links = [SELECT Account__r.Id, 
							 Id, 
							 Financial_Account__r.Balance__c,
							 Financial_Account__r.JH_Master_Table__c,
                             Financial_Account__r.RecordTypeId
   					  FROM Financial_Account_Link_SFDC2__c
   					  WHERE Account__r.Id = :account.Id];
    	} else {
	         contact_links = [SELECT Contact__r.Id, 
									 Id, 
									 Financial_Account__r.Balance__c,
									 Financial_Account__r.JH_Master_Table__c,
                                     Financial_Account__r.RecordTypeId
                   			  FROM Financial_Account_Contact_Link_SFDC2__c
                   			  WHERE Contact__r.Id = :account.PersonContactId
                   			  AND (Relationship__c = 'Primary' OR Relationship__c = 'Joint' OR Relationship__c = 'Dealer')];
    	}
    	
        List<Opportunity> opportunities = [SELECT Id,
                                           		  CreatedDate
                                           FROM Opportunity
                                           WHERE AccountId = :account.Id];

        List<Task> tasks = [SELECT ID,
                            	   ActivityDate 
                            FROM Task 
                            WHERE Type = 'Call' 
                            	AND Status = 'Completed' 
                            	AND (WhatId in :opportunities OR WhatId = :account.Id 
                            		OR (WhoId = :account.PersonContactId AND WhoId != null))];

        numDepositAccounts = 0;
        numCDAccounts = 0;
        numLoanAccounts = 0;
		balanceDepositAccounts = 0.0;
		balanceCDAccounts = 0.0;
		balanceLoanAccounts = 0.0;
        numLTDOpportunities = opportunities.size();
        numQTDOpportunities = calculateQuarterlyCount(opportunities, 'CreatedDate');
        numLTDCalls = tasks.size();
        numQTDCalls = calculateQuarterlyCount(tasks, 'ActivityDate');
         
        String query = 'Select id from RecordType where SobjectType = \'Financial_Account_SFDC2__c\'  and Name like \'%Employee%\'';
        List<SObject> results = Database.query(query);
        Set<Id> resultIds = (new Map<Id,SObject>(results)).keySet();
        if (!account.IsPersonAccount) {
	        for (Financial_Account_Link_SFDC2__c link : links) {
	            if (link.Financial_Account__r.JH_Master_Table__c == 'DD' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId) ) {
					numDepositAccounts++;
	                balanceDepositAccounts += link.Financial_Account__r.Balance__c;
	            }
	            if (link.Financial_Account__r.JH_Master_Table__c == 'CD' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId)) {
					numCDAccounts++;
	                balanceCDAccounts += link.Financial_Account__r.Balance__c;
	            }
	            if (link.Financial_Account__r.JH_Master_Table__c == 'LN' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId)) {
					numLoanAccounts++;
	                balanceLoanAccounts += link.Financial_Account__r.Balance__c;
	            }
	        }
        } else {
	        for (Financial_Account_Contact_Link_SFDC2__c link : contact_links) {
	            if (link.Financial_Account__r.JH_Master_Table__c == 'DD' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId)) {
					numDepositAccounts++;
	                balanceDepositAccounts += link.Financial_Account__r.Balance__c;
	            }
	            if (link.Financial_Account__r.JH_Master_Table__c == 'CD' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId)) {
					numCDAccounts++;
	                balanceCDAccounts += link.Financial_Account__r.Balance__c;
	            }
	            if (link.Financial_Account__r.JH_Master_Table__c == 'LN' &&  !resultIds.contains(link.Financial_Account__r.RecordTypeId)) {
					numLoanAccounts++;
	                balanceLoanAccounts += link.Financial_Account__r.Balance__c;
	            }
	        }
		}
    }
    
    /**
    * Computes the number of records created during the current quarter
    * @param objArray array of records to analyze
    * @param dateFieldName name of Date field to be used in comparison
    * @return count of records during current quarter
    */
    private Integer calculateQuarterlyCount(Sobject[] objArray, String dateFieldName) {
        Integer counter = 0;
        //determine the start/end dates for the current fiscal quarter
        Period qtr = [SELECT StartDate, EndDate 
                        FROM Period 
                        WHERE Type = 'Quarter' AND 
                        StartDate = THIS_FISCAL_QUARTER];
                        
        //loop through the record array and increment the counter if the date field falls within the quarter date range
        for(Sobject o : objArray) {
            Object value = o.get(dateFieldName);
            Date compareDate;
            if (value instanceof Date){
                compareDate = (Date)value;
            } else if(value instanceof DateTime) {
                compareDate = ((DateTime)value).date();
            } else {
                //if the data type if not a Date, break out
                break;
            }
            
            if(compareDate >= qtr.StartDate && compareDate <= qtr.EndDate) {
                counter++;
            }
        }
        return counter;
    }
    
}