objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Escheat</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>New Today</fullName>
                </value>
                <value>
                    <fullName>Pending Close</fullName>
                </value>
                <value>
                    <fullName>Restricted</fullName>
                </value>
                <value>
                    <fullName>No Post</fullName>
                </value>
                <value>
                    <fullName>Charged Off</fullName>
                </value>
                <value>
                    <fullName>No Credits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zero_Balance_Date__c</fullName>
        <label>Zero Balance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zero_Balance_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zero Balance Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account_Contact_Link_SFDC2__c.object
<CustomObject>
    <description>SFDC2: Creates a many-to-many junction between Contacts or Person Accounts and Financial Accounts</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account_SFDC2__c</referenceTo>
        <relationshipLabel>Business/Consumer Contacts</relationshipLabel>
        <relationshipName>Financial_Account_Contact_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <formula>Financial_Account__r.Maturity_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <formula>Financial_Account__r.Open_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Financial_Account__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Contact Link</label>
    <nameField>
        <displayFormat>FACL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Contact Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contact Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_SFDC2__c.object
<CustomObject>
    <description>Used to capture customer financial account information for SFDC 2.0 integration</description>
    <fields>
        <fullName>CampaignAutomationTriggerSFDC2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC2: Used in time-based workflows for campaign automations that rely on triggers based on dates associated with Financial Account</description>
        <label>CampaignAutomationTriggerSFDC2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Auto-Lending</fullName>
                </value>
                <value>
                    <fullName>Business Banking</fullName>
                </value>
                <value>
                    <fullName>Consumer Deposits</fullName>
                </value>
                <value>
                    <fullName>Mortgage Lending</fullName>
                </value>
                <value>
                    <fullName>Specialty Deposits</fullName>
                </value>
                <value>
                    <fullName>Virtus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Date__c</fullName>
        <label>Funding Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <label>Product Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature_Card_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signature Card Received?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zero_Balance_Date__c</fullName>
        <label>Zero Balance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zero_Balance_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zero Balance Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FinancialAccountSFDC2TriggerHandler.cls
public class FinancialAccountSFDC2TriggerHandler extends TriggerHandler {
	/** Map of records before changes */
	private Map<Id, Financial_Account_SFDC2__c> oldMap;
	/** Map of records with changes */
	private Map<Id, Financial_Account_SFDC2__c> newMap;
	/**List of records with changes; typically used for beforeInsert */
	private List<Financial_Account_SFDC2__c> newList;
	
	/** Constructor */
	public FinancialAccountSFDC2TriggerHandler() {
		this.oldMap = (Map<Id, Financial_Account_SFDC2__c>) Trigger.oldMap;
		this.newMap = (Map<Id, Financial_Account_SFDC2__c>) Trigger.newMap;
		this.newList = (List<Financial_Account_SFDC2__c>) Trigger.new;
	}

	/**
	* Process beforeInsert logic
	*/
	public override void beforeInsert() {  }
	
	/**
	* Process beforeUpdate logic
	*/
	public override void beforeUpdate() {
		handleCampaignWorkflowTrigger();
	}
	
	/**
	* Process afterInsert logic
	*/
	public override void afterInsert() {  }
	
	/**
	* Process afterUpdate logic
	*/
	public override void afterUpdate() {
		handleCampaignAutomation(newMap.values());
	}
	
	private void handleCampaignWorkflowTrigger(){
		List<Financial_Account_SFDC2__c> faToHandle = new List<Financial_Account_SFDC2__c>();
		for(Financial_Account_SFDC2__c fa : newMap.values()) {
			if(fa.CampaignAutomationTriggerSFDC2__c) {
				faToHandle.add(fa);
				fa.CampaignAutomationTriggerSFDC2__c = false;
			}
		}
		
		if(faToHandle.size() > 0) {
			handleCampaignAutomation(faToHandle);
		}
	}
	
	private void handleCampaignAutomation(List<Financial_Account_SFDC2__c> records) {
		List<Id> finAcctUpdates = new List<Id>();
		List<String> fieldsToCheck = new List<String>{
													   'Status__c',
													   'Product_Class__c',
													   'Maturity_Date__c',
													   'Open_Date__c',
													   'Signature_Card_Received__c',
													   'Department__c',
													   'Funding_Date__c',
													   'Zero_Balance_Flag__c',
													   'Zero_Balance_Date__c'
														};
		for(Financial_Account_SFDC2__c fa : records) {
			Financial_Account_SFDC2__c oldFa = oldMap.get(fa.Id);
			for(String fieldName : fieldsToCheck) {
				if(fa.get(fieldName) != oldFa.get(fieldName)) {
					finAcctUpdates.add(fa.Id);
					break;
				}
			}
		}
		
		if(finAcctUpdates.size() > 0) {
			//retrieve link records and submit for further scrutiny
			List<String> linkIds = new List<String>();
			for(Financial_Account_Contact_Link_SFDC2__c link : [SELECT Id FROM Financial_Account_Contact_Link_SFDC2__c WHERE Financial_Account__c in :finAcctUpdates]) {
				linkIds.add(link.Id);	
			}
			if(linkIds.size() > 0) {
				CampaignMemberAutomationHandler.handleCampaignMemberAutomation(linkIds);
			}
		}
	}
}