objects/Financial_Account__c.object
<CustomObject>
    <description>Used by Consumer Deposits to capture account details for a person</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account_Link_SFDC2__c.object
<CustomObject>
    <description>Creates a junction between Account and Financial Account to create a many-to-many relationship, SFDC2</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CIF_JHA_LINK__c</fullName>
        <description>Combination of CIF and JHA Unique Id for upserting links</description>
        <externalId>true</externalId>
        <label>CIF JHA LINK</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account_SFDC2__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Link</label>
    <nameField>
        <displayFormat>FAL-{YYYYMMDD}-{0000}</displayFormat>
        <label>Financial Account Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_SFDC2__c.object
<CustomObject>
    <description>Used to capture customer financial account information for SFDC 2.0 integration</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Deposits</fullName>
        <active>true</active>
        <label>Deposits</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustomFinancialAccountLookup_test.cls
@isTest
public class CustomFinancialAccountLookup_test {
    
    /*

https://bofi--uat--c.cs77.visual.force.com/apex/CustomFinancialAccountLookup?relatedACc=0010H00002J7b4H&lkfield=00N0H00000Ivp3W&lknm=pg:myForm:newAccount:j_id31:j_id33:6:j_id34&frm=pg%3AmyForm&lksearch=&lksrch=
*/
    @isTest
    static void testCustomFinancialAccountLookupController(){
        
        Id accBA = [Select id from RecordType where Name = 'Business Account SFDC2' ].Id;
        Account acc = new Account ();
        acc.RecordTypeId = accBA;
        acc.Name = 'TestCase';
        acc.CIF_SFDC2__c = '123XYZ';
        insert acc;
        
        Id facRTId = [Select id from RecordType where Name = 'Deposits' and  SobjectType = 'Financial_Account_SFDC2__c' ].Id;
        

          Financial_Account_SFDC2__c  facc = new Financial_Account_SFDC2__c ();
          facc.Name = 'Basic Business Checking 5700';
          
          facc.RecordTypeId  = facRTId;
     
          insert facc;
        
        

        
        Financial_Account_Link_SFDC2__c fa = new Financial_Account_Link_SFDC2__c();
        fa.Account__c = acc.Id; 
        fa.CIF_JHA_LINK__c = 'AAA345178^200100155700^D';
        fa.Financial_Account__c  = facc.id;
        
        insert fa;
        
        Test.setCurrentPageReference(new PageReference('Page.CustomFinancialAccountLookup')); 
        System.currentPageReference().getParameters().put('relatedACc', acc.Id);
        System.currentPageReference().getParameters().put('lkfield', '00N0H00000Ivp3W');
        System.currentPageReference().getParameters().put('lknm', 'pg:myForm:newAccount:j_id31:j_id33:6:j_id34');
        System.currentPageReference().getParameters().put('frm', 'pg%3AmyForm');
        
        CustomFinancialAccountLookupController cfa = new CustomFinancialAccountLookupController();
        
            cfa.getItems();
        cfa.getFilters() ;
        cfa.dateSelected();
        cfa.getLkUpId() ;
        cfa.getLknm() ;
        cfa.getNxt() ;
        cfa.Firstbtn() ; 
        cfa.Nxtbtn() ;
        cfa.lstbtn() ;
        cfa.getPrv() ;
        cfa.dateSelected();
        cfa.getFormTag();  
 
            
     }
    
}