objects/HRB_Refund_Advance__c.object
<CustomObject>
    <fields>
        <fullName>CreatedAt__c</fullName>
        <label>CreatedAt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Year_Tax_Refund_Amount__c</fullName>
        <label>Current Year Tax Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DecisionBy__c</fullName>
        <label>DecisionBy</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HRBDecision__c</fullName>
        <label>HRBDecision</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IRS_Phone_Number__c</fullName>
        <label>IRS Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ManualDecision__c</fullName>
        <label>ManualDecision</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLAMinutes__c</fullName>
        <formula>if(isCompleted__c,
60*24*(NULLVALUE(LastModDT__c, Now())-CreatedAt__c),
60*24*( Now()-CreatedAt__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLAMinutes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SSN_TIN__c</fullName>
        <label>SSN/TIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>HRB Refund Advance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Refund Advance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HRBRefundStatus__c.object
<CustomObject>
    <fields>
        <fullName>CreatedAt__c</fullName>
        <label>CreatedAt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HRB_Refund_Advance__c</fullName>
        <label>HRB Refund Advance</label>
        <referenceTo>HRB_Refund_Advance__c</referenceTo>
        <relationshipLabel>HRBRefundStatuses</relationshipLabel>
        <relationshipName>HRBRefundStatuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLAMinutes__c</fullName>
        <formula>60*24*(NULLVALUE(CompletedAt__c, Now())-CreatedAt__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLAMinutes</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>HRBRefundStatus</label>
    <nameField>
        <label>HRBRefundStatus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRBRefundStatuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BOFI_IFL_Controller.cls
public class BOFI_IFL_Controller {
    HRBRefundStatus__c RId;
    String currUser;
    public Id RecId {get; set;}
    public String usr{get;set;}
    public ApexPages.StandardSetController controller {
        get {
            if(controller == null) {
                controller = new ApexPages.StandardSetController(Database.getQueryLocator([Select HRB_Refund_Advance__c, SLAMinutes__c, HRB_Refund_Advance__r.IRS_Phone_Number__c, HRB_Refund_Advance__r.ManualDecision__c,HRB_Refund_Advance__r.SSN_TIN__c,HRB_Refund_Advance__r.First_Name__c, HRB_Refund_Advance__r.Current_Year_Tax_Refund_Amount__c, CreatedAt__c FROM HRBRefundStatus__c Where HRB_Refund_Advance__r.HRBDecision__c=Null AND HRB_Refund_Advance__r.DecisionBy__c='manual' AND HRB_Refund_Advance__r.ManualDecision__c = Null and (HRB_Refund_Advance__r.Owner.Name = 'HRB-API1' or HRB_Refund_Advance__r.Owner.Name = 'HRB Queue' or HRB_Refund_Advance__r.Owner.Name =: currUser) order by CreatedDate desc]));
            }
            return controller;
        }
        set;
    }

    public String usr() {
        String currUser = UserInfo.getName();
        return currUser;
    }

    public List<HRBRefundStatus__c> getRecords(){
        List<HRBRefundStatus__c> Records=(List<HRBRefundStatus__c>) controller.getRecords();
        return Records;
    }
    public BOFI_IFL_Controller (){
        List<HRBRefundStatus__c> Records=[select HRB_Refund_Advance__c, CreatedAt__c, SLAMinutes__c, HRB_Refund_Advance__r.IRS_Phone_Number__c, HRB_Refund_Advance__r.ManualDecision__c,HRB_Refund_Advance__r.SSN_TIN__c,HRB_Refund_Advance__r.First_Name__c, HRB_Refund_Advance__r.OwnerId, HRB_Refund_Advance__r.Owner.Name, HRB_Refund_Advance__r.Current_Year_Tax_Refund_Amount__c from  HRBRefundStatus__c Where HRB_Refund_Advance__r.HRBDecision__c=Null AND HRB_Refund_Advance__r.DecisionBy__c='manual' AND HRB_Refund_Advance__r.ManualDecision__c = Null and (HRB_Refund_Advance__r.Owner.Name = 'HRB-API1' or HRB_Refund_Advance__r.Owner.Name ='HRB Queue' or HRB_Refund_Advance__r.Owner.Name =: currUser) order by CreatedDate desc];
        controller=new Apexpages.StandardSetController(Records);
        controller.setPageSize(1);
        RId = (HRBRefundStatus__c)controller.getRecord();
    }
    public PageReference UpdStatusToAccept(){
        String master  = [Select HRB_Refund_Advance__c from  HRBRefundStatus__c where id  =:RecId].HRB_Refund_Advance__c;
        HRB_Refund_Advance__c  HRBUp = new HRB_Refund_Advance__c (id = master, ManualDecision__c = 'APD', HRBDecision__c = 'APD') ;
        Update HRBUp;  
        PageReference retURL = new PageReference('/apex/BOFI_IFL_Page');
        retURL.setRedirect(true);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info,'Manual APD'));
        return retURL;
    }
    public PageReference UpdStatusToReject(){
        String master  = [Select HRB_Refund_Advance__c from  HRBRefundStatus__c where id  =:RecId].HRB_Refund_Advance__c;
        HRB_Refund_Advance__c  HRBUp = new HRB_Refund_Advance__c (id = master, ManualDecision__c = 'DCL', HRBDecision__c = 'DCL') ;
        Update HRBUp;        
        PageReference retURL = new PageReference('/apex/BOFI_IFL_Page');
        retURL.setRedirect(true);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.info,'Manual DCL'));
        return retURL;            
    } 
    public PageReference quit() {
        String hrbApi = [select Id from User where Name = 'HRB-API1'].Id;
        String master  = [Select HRB_Refund_Advance__c from  HRBRefundStatus__c where id  =:RecId].HRB_Refund_Advance__c;
        HRB_Refund_Advance__c  HRBUp = new HRB_Refund_Advance__c (id = master, OwnerId = hrbApi);
        Update HRBUp;
        PageReference retURL = new PageReference('/apex/BOFI_IFL');
        retURL.setRedirect(true);
        return retURL;
    } 
}