objects/HRB_Refund_Advance__c.object
<CustomObject>
    <fields>
        <fullName>AutoDecision__c</fullName>
        <label>AutoDecision</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DecisionBy__c</fullName>
        <label>DecisionBy</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_Advance_Application_ID__c</fullName>
        <label>Refund Advance Application ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transcript__c</fullName>
        <label>Transcript</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>HRB Refund Advance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Refund Advance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Bofi_HRB_DecisionController.cls
@RestResource(urlMapping='/Bofi_HRB_Decision/*')
global with sharing class Bofi_HRB_DecisionController {
          
   @HttpPost
    global static void createCase(String RequestID, String Decision, String Score, String Transcript, String Decision_By) {
    System.debug('RequestID Decision ' + RequestID + ', ' + Decision);
    HRB_Refund_Advance__c HRB_UPD_Rec = [SELECT Id, Refund_Advance_Application_ID__c, AutoDecision__c, Score__c,Transcript__c, DecisionBy__c FROM HRB_Refund_Advance__c where Refund_Advance_Application_ID__c =:RequestID limit 1];
    System.debug(Decision);
    System.debug(Score);
    System.debug(Transcript);
    System.debug(Decision_By);
    HRB_UPD_Rec.AutoDecision__c = Decision;      
    HRB_UPD_Rec.Score__c       = Score;
    HRB_UPD_Rec.Transcript__c  = Transcript;
    HRB_UPD_Rec.DecisionBy__c  = Decision_By;
    
   Update HRB_UPD_Rec; 

   }  
   //string token = '/d';
   // string a='asdf';
}