objects/HRB_Refund_Advance__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Preferred_Phone__c</fullName>
        <label>Client Preferred Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CreatedAt__c</fullName>
        <label>CreatedAt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Year_Tax_Refund_Amount__c</fullName>
        <label>Current Year Tax Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_And_Timestamp_Received__c</fullName>
        <label>Date And Timestamp Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Processed__c</fullName>
        <description>Date_Processed__c</description>
        <label>Date_Processed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_Advance_Application_ID__c</fullName>
        <label>Refund Advance Application ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN_TIN__c</fullName>
        <label>SSN/TIN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>HRB Refund Advance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Refund Advance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Bofi_HRB_RefundController.cls
@RestResource(urlMapping='/Bofi_HRB_Refund/*')
global with sharing class Bofi_HRB_RefundController {    
    
    @HttpPost
    global static ID createHRB_Refund(String Application_Status, String City, String Client_Preferred_Phone, Integer Current_Year_Tax_Refund_Amount, Datetime Date_And_Timestamp_Received, Date Date_Of_Birth, Date Date_Processed, String Filing_Status, String First_Name, String Last_Name, String Middle_Name, String Refund_Advance_Application_ID, String SSN_TIN, String State, String Street, String Zip_Code) {
        HRB_Refund_Advance__c thisHRB_Refund = new HRB_Refund_Advance__c(
                    //Application_Status__c = Application_Status,
                    City__c = City,
                    Client_Preferred_Phone__c = Client_Preferred_Phone,
                    Current_Year_Tax_Refund_Amount__c = Current_Year_Tax_Refund_Amount,
                    CreatedAt__c = Date_And_Timestamp_Received,
                    Date_And_Timestamp_Received__c = Date_And_Timestamp_Received,
                    Date_Of_Birth__c = Date_Of_Birth,
                    Date_Processed__c = Date_Processed,
                    Filing_Status__c = Filing_Status,
                    First_Name__c = First_Name,
                    Last_Name__c = Last_Name,
                    Middle_Name__c = Middle_Name,
                    Refund_Advance_Application_ID__c = Refund_Advance_Application_ID,
                    SSN_TIN__c = SSN_TIN,
                    State__c = State,
                    Street__c = Street,
                    Zip_Code__c = Zip_Code);
                    
            insert thisHRB_Refund; 

       return thisHRB_Refund.Id; 
     
    }  
}