objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>ChatEmail__c</fullName>
        <label>ChatEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChatFirstName__c</fullName>
        <label>ChatFirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChatLastName__c</fullName>
        <label>ChatLastName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChatPhone__c</fullName>
        <label>ChatPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Chat_Inquiry_Type__c</fullName>
        <label>Chat Inquiry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checking, Savings, or other deposit accounts</fullName>
                </value>
                <value>
                    <fullName>Existing Mortgage, Auto or other loans</fullName>
                </value>
                <value>
                    <fullName>All Other New Account Inquiries</fullName>
                </value>
                <value>
                    <fullName>New Online Banking Help</fullName>
                </value>
                <value>
                    <fullName>Advisor Account Opening</fullName>
                    <isActive>false</isActive>
                    <label>Advisor Account Opening</label>
                </value>
                <value>
                    <fullName>Advisor Dashboard Help</fullName>
                    <isActive>false</isActive>
                    <label>Advisor Dashboard Help</label>
                </value>
                <value>
                    <fullName>Apply for a loan</fullName>
                    <isActive>false</isActive>
                    <label>Apply for a loan</label>
                </value>
                <value>
                    <fullName>Bank account features and benefits</fullName>
                    <isActive>false</isActive>
                    <label>Bank account features and benefits</label>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                    <isActive>false</isActive>
                    <label>Bill Pay</label>
                </value>
                <value>
                    <fullName>Business Account</fullName>
                    <isActive>false</isActive>
                    <label>Business Account</label>
                </value>
                <value>
                    <fullName>Customer Information Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Customer Information Inquiry</label>
                </value>
                <value>
                    <fullName>Debit card</fullName>
                    <isActive>false</isActive>
                    <label>Debit card</label>
                </value>
                <value>
                    <fullName>Deposit Account</fullName>
                    <isActive>false</isActive>
                    <label>Deposit Account</label>
                </value>
                <value>
                    <fullName>Deposit inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Deposit inquiry</label>
                </value>
                <value>
                    <fullName>Dispute a transaction</fullName>
                    <isActive>false</isActive>
                    <label>Dispute a transaction</label>
                </value>
                <value>
                    <fullName>Forgot Advisor Password</fullName>
                    <isActive>false</isActive>
                    <label>Forgot Advisor Password</label>
                </value>
                <value>
                    <fullName>Forgot Advisor UserName</fullName>
                    <isActive>false</isActive>
                    <label>Forgot Advisor UserName</label>
                </value>
                <value>
                    <fullName>I am an HRB Customer</fullName>
                    <isActive>false</isActive>
                    <label>I am an HRB Customer</label>
                </value>
                <value>
                    <fullName>IRA</fullName>
                    <isActive>false</isActive>
                    <label>IRA</label>
                </value>
                <value>
                    <fullName>Mortgage Loan</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Loan</label>
                </value>
                <value>
                    <fullName>Open a business bank account</fullName>
                    <isActive>false</isActive>
                    <label>Open a business bank account</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Personal Loan</fullName>
                    <isActive>false</isActive>
                    <label>Personal Loan</label>
                </value>
                <value>
                    <fullName>Question about your business bank account</fullName>
                    <isActive>false</isActive>
                    <label>Question about your business bank account</label>
                </value>
                <value>
                    <fullName>Question about your loan</fullName>
                    <isActive>false</isActive>
                    <label>Question about your loan</label>
                </value>
                <value>
                    <fullName>Speak with Relationship Manager</fullName>
                    <isActive>false</isActive>
                    <label>Speak with Relationship Manager</label>
                </value>
                <value>
                    <fullName>Types of loans</fullName>
                    <isActive>false</isActive>
                    <label>Types of loans</label>
                </value>
                <value>
                    <fullName>Wire</fullName>
                    <isActive>false</isActive>
                    <label>Wire</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LiveAgent_LeadFromChatController_Test.cls
@isTest
private class LiveAgent_LeadFromChatController_Test {

	@testSetup
	static void setup() {
		LiveChatVisitor chatVisitor = new LiveChatVisitor();
		insert chatVisitor;

		LiveChatTranscript chatTranscript = new LiveChatTranscript(
			ChatFirstName__c = 'John',
			ChatLastName__c = 'Doe',
			ChatEmail__c = 'john@doe.com',
			ChatPhone__c = '7896584568',
			Chat_Inquiry_Type__c = 'Checking, Savings, or other deposit accounts',
			LiveChatVisitorId = chatVisitor.Id
		);
		insert chatTranscript;
	}

	@isTest static void should_generate_lead_from_chat() {
		LiveChatTranscript chatTranscript = [SELECT Id FROM LiveChatTranscript LIMIT 1];
		ApexPages.StandardController stdController = new ApexPages.StandardController(chatTranscript);


		Test.startTest();
			LiveAgent_LeadFromChatController chatController = new LiveAgent_LeadFromChatController(stdController);
			chatController.saveLead();
		Test.stopTest();

		System.assert(chatController.newLead != null);
		System.assert(String.isNotBlank(chatController.newLead.Id));
	}

}