objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>ChatEmail__c</fullName>
        <label>ChatEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChatFirstName__c</fullName>
        <label>ChatFirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChatLastName__c</fullName>
        <label>ChatLastName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChatPhone__c</fullName>
        <label>ChatPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Chat_Inquiry_Type__c</fullName>
        <label>Chat Inquiry Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checking, Savings, or other deposit accounts</fullName>
                </value>
                <value>
                    <fullName>Existing Mortgage, Auto or other loans</fullName>
                </value>
                <value>
                    <fullName>All Other New Account Inquiries</fullName>
                </value>
                <value>
                    <fullName>New Online Banking Help</fullName>
                </value>
                <value>
                    <fullName>Advisor Account Opening</fullName>
                    <isActive>false</isActive>
                    <label>Advisor Account Opening</label>
                </value>
                <value>
                    <fullName>Advisor Dashboard Help</fullName>
                    <isActive>false</isActive>
                    <label>Advisor Dashboard Help</label>
                </value>
                <value>
                    <fullName>Apply for a loan</fullName>
                    <isActive>false</isActive>
                    <label>Apply for a loan</label>
                </value>
                <value>
                    <fullName>Bank account features and benefits</fullName>
                    <isActive>false</isActive>
                    <label>Bank account features and benefits</label>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                    <isActive>false</isActive>
                    <label>Bill Pay</label>
                </value>
                <value>
                    <fullName>Business Account</fullName>
                    <isActive>false</isActive>
                    <label>Business Account</label>
                </value>
                <value>
                    <fullName>Customer Information Inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Customer Information Inquiry</label>
                </value>
                <value>
                    <fullName>Debit card</fullName>
                    <isActive>false</isActive>
                    <label>Debit card</label>
                </value>
                <value>
                    <fullName>Deposit Account</fullName>
                    <isActive>false</isActive>
                    <label>Deposit Account</label>
                </value>
                <value>
                    <fullName>Deposit inquiry</fullName>
                    <isActive>false</isActive>
                    <label>Deposit inquiry</label>
                </value>
                <value>
                    <fullName>Dispute a transaction</fullName>
                    <isActive>false</isActive>
                    <label>Dispute a transaction</label>
                </value>
                <value>
                    <fullName>Forgot Advisor Password</fullName>
                    <isActive>false</isActive>
                    <label>Forgot Advisor Password</label>
                </value>
                <value>
                    <fullName>Forgot Advisor UserName</fullName>
                    <isActive>false</isActive>
                    <label>Forgot Advisor UserName</label>
                </value>
                <value>
                    <fullName>I am an HRB Customer</fullName>
                    <isActive>false</isActive>
                    <label>I am an HRB Customer</label>
                </value>
                <value>
                    <fullName>IRA</fullName>
                    <isActive>false</isActive>
                    <label>IRA</label>
                </value>
                <value>
                    <fullName>Mortgage Loan</fullName>
                    <isActive>false</isActive>
                    <label>Mortgage Loan</label>
                </value>
                <value>
                    <fullName>Open a business bank account</fullName>
                    <isActive>false</isActive>
                    <label>Open a business bank account</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Personal Loan</fullName>
                    <isActive>false</isActive>
                    <label>Personal Loan</label>
                </value>
                <value>
                    <fullName>Question about your business bank account</fullName>
                    <isActive>false</isActive>
                    <label>Question about your business bank account</label>
                </value>
                <value>
                    <fullName>Question about your loan</fullName>
                    <isActive>false</isActive>
                    <label>Question about your loan</label>
                </value>
                <value>
                    <fullName>Speak with Relationship Manager</fullName>
                    <isActive>false</isActive>
                    <label>Speak with Relationship Manager</label>
                </value>
                <value>
                    <fullName>Types of loans</fullName>
                    <isActive>false</isActive>
                    <label>Types of loans</label>
                </value>
                <value>
                    <fullName>Wire</fullName>
                    <isActive>false</isActive>
                    <label>Wire</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Manager_SFDC2__mdt.object
<CustomObject>
    <description>This custom metadate will be used to add all the Roles (Manager and Non-manager) for all SFDC2 BU</description>
    <fields>
        <fullName>Live_Agent_Queue__c</fullName>
        <description>This field should be used to map the Chat Queue to the corresponding Lead record type.</description>
        <label>Live Agent Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <description>SAve the recordtype name for the BU.</description>
        <label>RecordType Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Manager SFDC2</label>
    <pluralLabel>Managers SFDC2</pluralLabel>
</CustomObject>

classes/LiveAgent_LeadFromChatController.cls
public with sharing class LiveAgent_LeadFromChatController {

	public Lead newLead                      { get; set; }
	public LiveChatTranscript chatTranscript { get; set; }
	public String leadRecordTypeId           { get; set; }
	public Boolean leadWasCreated            { get; set; }
	public Boolean itHasErrors               { get; set; }

	/**
	 * Constructor
	 * @param  stdController Live Chat Transcript Standard Controller
	 */
	public LiveAgent_LeadFromChatController(ApexPages.StandardController stdController) {

		chatTranscript = [
			SELECT ChatFirstName__c, ChatLastName__c, ChatEmail__c, ChatPhone__c, Chat_Inquiry_Type__c, LiveChatButton.Queue.DeveloperName
			FROM LiveChatTranscript
			WHERE Id = :stdController.getId()
		];

		setNewLeadRecordType();

		newLead = new Lead(
			FirstName             = chatTranscript.ChatFirstName__c,
			LastName              = chatTranscript.ChatLastName__c,
			Email                 = chatTranscript.ChatEmail__c,
			Phone                 = chatTranscript.ChatPhone__c,
			PrimaryInquiryType__c = chatTranscript.Chat_Inquiry_Type__c,
			LeadSource            = 'Web Chat',
			Status                = 'New',
			Company               = 'Not provided',
			RecordTypeId          = leadRecordTypeId
		);

		// Set additional fields
		String advisorRecordType = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Advisor Firm SFDC2').getRecordTypeId();
		if(advisorRecordType == leadRecordTypeId) {
			newLead.Financial_Advisor_Type__c = 'Other';
			newLead.Financial_Advisor_Type_Other__c = 'Other';
		}

		leadWasCreated = false;
		itHasErrors = false;
	}

	/**
	 * Create Lead and associate it to Chat Transcript
	 */
	public PageReference saveLead() {
		try {
			insert newLead;
			chatTranscript.LeadId = newLead.Id;
			chatTranscript.ChatEmail__c = newLead.Email;
			update chatTranscript;
			leadWasCreated = true;
		} catch(Exception ex) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, ex.getMessage()));
			leadWasCreated = false;
			itHasErrors = true;
		}

		return null;
	}

	/**
	 * Set record type for new lead based on chat routing
	 */
	private void setNewLeadRecordType() {
		String queueName = Test.isRunningTest() ? 'Consumer_Deposits_Chat_Queue' : chatTranscript.LiveChatButton.Queue.DeveloperName;
        Map<String, Schema.RecordTypeInfo> mapLeadRecordTypes = Schema.SObjectType.Lead.getRecordTypeInfosByName();
        String liveChatQueue = [SELECT RecordType_Name__c FROM Manager_SFDC2__mdt WHERE Live_Agent_Queue__c LIKE :('%'+queueName+'%')].RecordType_Name__c;
        this.leadRecordTypeId = mapLeadRecordTypes.get(liveChatQueue).getRecordTypeId();
	}

}