objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>ApprovalSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with trigger/approval to verify fields required for approval are not null.</description>
        <label>ApprovalSubmitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C_I_Loan_Type__c</fullName>
        <label>C&amp;I Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1A</fullName>
                </value>
                <value>
                    <fullName>1B</fullName>
                </value>
                <value>
                    <fullName>1C</fullName>
                </value>
                <value>
                    <fullName>1D</fullName>
                </value>
                <value>
                    <fullName>1E</fullName>
                </value>
                <value>
                    <fullName>1F</fullName>
                </value>
                <value>
                    <fullName>5A</fullName>
                </value>
                <value>
                    <fullName>5B</fullName>
                </value>
                <value>
                    <fullName>5C</fullName>
                </value>
                <value>
                    <fullName>5D</fullName>
                </value>
                <value>
                    <fullName>5E</fullName>
                </value>
                <value>
                    <fullName>5F</fullName>
                </value>
                <value>
                    <fullName>5G</fullName>
                </value>
                <value>
                    <fullName>5J</fullName>
                </value>
                <value>
                    <fullName>5L</fullName>
                </value>
                <value>
                    <fullName>5M</fullName>
                </value>
                <value>
                    <fullName>5N</fullName>
                </value>
                <value>
                    <fullName>5P</fullName>
                </value>
                <value>
                    <fullName>5R</fullName>
                </value>
                <value>
                    <fullName>5S</fullName>
                </value>
                <value>
                    <fullName>5T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Report_Code__c</fullName>
        <label>Call Report Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1C2A</fullName>
                </value>
                <value>
                    <fullName>1A1</fullName>
                </value>
                <value>
                    <fullName>1D</fullName>
                </value>
                <value>
                    <fullName>1A2</fullName>
                </value>
                <value>
                    <fullName>1E2</fullName>
                </value>
                <value>
                    <fullName>4A</fullName>
                </value>
                <value>
                    <fullName>6D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Code_Description__c</fullName>
        <label>Collateral Code/Description</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>110 - SFR Construction</fullName>
                </value>
                <value>
                    <fullName>120 - MF Construction</fullName>
                </value>
                <value>
                    <fullName>130 - CRE Construction</fullName>
                </value>
                <value>
                    <fullName>160 - Real Estate - Raw Lots and Land</fullName>
                </value>
                <value>
                    <fullName>400 - Business-Unsecured</fullName>
                </value>
                <value>
                    <fullName>441 - Business Secured by Non-Real Estate Collateral</fullName>
                </value>
                <value>
                    <fullName>501 - SFR Notes</fullName>
                </value>
                <value>
                    <fullName>502 - SFR NPL</fullName>
                </value>
                <value>
                    <fullName>503 - SFR Tax Liens</fullName>
                </value>
                <value>
                    <fullName>504 - MF Notes</fullName>
                </value>
                <value>
                    <fullName>505 - MF NPL</fullName>
                </value>
                <value>
                    <fullName>506 - MF Tax Liens</fullName>
                </value>
                <value>
                    <fullName>507 - CRE Notes</fullName>
                </value>
                <value>
                    <fullName>508 - CRE NPL</fullName>
                </value>
                <value>
                    <fullName>509 - CRE Tax Liens</fullName>
                </value>
                <value>
                    <fullName>510 - Health Care</fullName>
                </value>
                <value>
                    <fullName>511 - SFR Direct</fullName>
                </value>
                <value>
                    <fullName>512 - MF Direct</fullName>
                </value>
                <value>
                    <fullName>513 - CRE Direct</fullName>
                </value>
                <value>
                    <fullName>620 - Consumer Note, Unsecured</fullName>
                </value>
                <value>
                    <fullName>621 - Consumer, New Cars</fullName>
                </value>
                <value>
                    <fullName>622 - Consumer, Used Cars</fullName>
                </value>
                <value>
                    <fullName>640 - Consumer, Secured by Other Collateral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose_Code__c</fullName>
        <label>Purpose Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 - Lender Finance</fullName>
                </value>
                <value>
                    <fullName>31 - Bridge/A and D</fullName>
                </value>
                <value>
                    <fullName>34 - Farmland</fullName>
                </value>
                <value>
                    <fullName>35 - Participation</fullName>
                </value>
                <value>
                    <fullName>36 - Lender Finance Participation</fullName>
                </value>
                <value>
                    <fullName>37 - Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoanOpsQstnrTriggerHandler.cls
/**
* @description <p>Handler class for LoanOpsQstnrTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public class LoanOpsQstnrTriggerHandler extends TriggerHandler {

  /** Map of records before changes */
  private Map<Id, Loan_Ops_Questionnaire__c> oldObjMap;
  /** Map of records with changes */
  private Map<Id, Loan_Ops_Questionnaire__c> newObjMap;
  
  /** Constructor */
  public LoanOpsQstnrTriggerHandler() {
    this.oldObjMap = (Map<Id, Loan_Ops_Questionnaire__c>) Trigger.oldMap;
    this.newObjMap = (Map<Id, Loan_Ops_Questionnaire__c>) Trigger.newMap;
  }
    
  /**
  * Process beforeUpdate logic
  */
  public override void beforeUpdate() {
    validateLOQApproval();
  }
  
  /**
   * Ensures that required fields of LOQ are completed before Approval is allowed 
   * 
   */
  private void validateLOQApproval() {
      for(Loan_Ops_Questionnaire__c loq : newObjMap.values()) {
          Loan_Ops_Questionnaire__c oldLOQ = oldObjMap.get(loq.Id);
          if(loq.ApprovalSubmitted__c && !oldLOQ.ApprovalSubmitted__c) {
              System.debug('**** ApprovalSubmitted=true');
              //approval submitted, validate required fields
              String errMsg = 'This Loan Ops Questionnaire cannot yet be approved because the following required field(s) must contains a value ';
              List<String> reqFieldList = new List<String>();
              System.debug('**** C&I Loan Type=' + loq.C_I_Loan_Type__c);
              Schema.DescribeSObjectResult loqObj = Schema.SObjectType.Loan_Ops_Questionnaire__c;
              if(loq.C_I_Loan_Type__c == null) {
                  reqFieldList.add(Schema.SObjectType.Loan_Ops_Questionnaire__c.fields.C_I_Loan_Type__c.getLabel());
              }
              System.debug('**** Call Report Code=' + loq.Call_Report_Code__c);
              if(loq.Call_Report_Code__c == null) {
                  reqFieldList.add(Schema.SObjectType.Loan_Ops_Questionnaire__c.fields.Call_Report_Code__c.getLabel());
              }
              System.debug('**** Collateral Code/Description=' + loq.Collateral_Code_Description__c);
              if(loq.Collateral_Code_Description__c == null) {
                  reqFieldList.add(Schema.SObjectType.Loan_Ops_Questionnaire__c.fields.Collateral_Code_Description__c.getLabel());
              }
              System.debug('**** Purpose Code=' + loq.Purpose_Code__c);
              if(loq.Purpose_Code__c == null) {
                  reqFieldList.add(Schema.SObjectType.Loan_Ops_Questionnaire__c.fields.Purpose_Code__c.getLabel());
              }
              
              if(reqFieldList.size() > 0) {
                  loq.addError(errMsg + reqFieldList + '. Please return to the original LOQ and complete the required fields <a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + loq.Id + '">' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + loq.Id +'</a>');
                  loq.ApprovalSubmitted__c = false;
              }
          }
      }
  }
}