objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>Addl_LOQ_Options__c</fullName>
        <label>8. Select all that apply:</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Agent</fullName>
                </value>
                <value>
                    <fullName>Bridge A&amp;D</fullName>
                </value>
                <value>
                    <fullName>Bridge IR Requirement</fullName>
                </value>
                <value>
                    <fullName>Committed loan</fullName>
                </value>
                <value>
                    <fullName>Construction financing</fullName>
                </value>
                <value>
                    <fullName>Fund Control</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Bridge Interest Reverse Requirement</fullName>
                    <isActive>false</isActive>
                    <label>Bridge Interest Reverse Requirement</label>
                </value>
                <value>
                    <fullName>Participation</fullName>
                    <isActive>false</isActive>
                    <label>Participation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ApprovalSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with trigger/approval to verify fields required for approval are not null.</description>
        <label>ApprovalSubmitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Borrower_Relationship__c</fullName>
        <label>4. Borrower to collateral relationship:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Participation</fullName>
                </value>
                <value>
                    <fullName>Lender Participation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>RE Acquisition</fullName>
                    <isActive>false</isActive>
                    <label>RE Acquisition</label>
                </value>
                <value>
                    <fullName>RE Construction</fullName>
                    <isActive>false</isActive>
                    <label>RE Construction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_I_Loan_Type__c</fullName>
        <label>C&amp;I Loan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1A</fullName>
                </value>
                <value>
                    <fullName>1B</fullName>
                </value>
                <value>
                    <fullName>1C</fullName>
                </value>
                <value>
                    <fullName>1D</fullName>
                </value>
                <value>
                    <fullName>1E</fullName>
                </value>
                <value>
                    <fullName>1F</fullName>
                </value>
                <value>
                    <fullName>5A</fullName>
                </value>
                <value>
                    <fullName>5B</fullName>
                </value>
                <value>
                    <fullName>5C</fullName>
                </value>
                <value>
                    <fullName>5D</fullName>
                </value>
                <value>
                    <fullName>5E</fullName>
                </value>
                <value>
                    <fullName>5F</fullName>
                </value>
                <value>
                    <fullName>5G</fullName>
                </value>
                <value>
                    <fullName>5J</fullName>
                </value>
                <value>
                    <fullName>5L</fullName>
                </value>
                <value>
                    <fullName>5M</fullName>
                </value>
                <value>
                    <fullName>5N</fullName>
                </value>
                <value>
                    <fullName>5P</fullName>
                </value>
                <value>
                    <fullName>5R</fullName>
                </value>
                <value>
                    <fullName>5S</fullName>
                </value>
                <value>
                    <fullName>5T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Report_Code__c</fullName>
        <label>Call Report Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1C2A</fullName>
                </value>
                <value>
                    <fullName>1A1</fullName>
                </value>
                <value>
                    <fullName>1D</fullName>
                </value>
                <value>
                    <fullName>1A2</fullName>
                </value>
                <value>
                    <fullName>1E2</fullName>
                </value>
                <value>
                    <fullName>4A</fullName>
                </value>
                <value>
                    <fullName>6D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Secured__c</fullName>
        <label>5. Is collateral?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type_RE__c</fullName>
        <label>7. If RE, collateral type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notes</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                </value>
                <value>
                    <fullName>Recorded Mortgage</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type__c</fullName>
        <label>1. Collateral Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Business Loans</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Account/Lease Receivable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <label>3. Interest Rate Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adjustable</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOQ_Status__c</fullName>
        <description>Change in field values is controlled by approval process</description>
        <label>LOQ Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LOQ In Progress</fullName>
                    <default>true</default>
                    <label>LOQ In Progress</label>
                </value>
                <value>
                    <fullName>LOQ Submitted for approval</fullName>
                </value>
                <value>
                    <fullName>LOQ Approved</fullName>
                </value>
                <value>
                    <fullName>LOQ Rejected</fullName>
                </value>
                <value>
                    <fullName>LOQ Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>contains</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF, IPL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Ops Questionnaires</relationshipLabel>
        <relationshipName>Loan_Ops_Questionnaires</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>6. If RE, property type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFR</fullName>
                </value>
                <value>
                    <fullName>MF</fullName>
                </value>
                <value>
                    <fullName>CRE</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                    <isActive>false</isActive>
                    <label>NPL</label>
                </value>
                <value>
                    <fullName>Notes</fullName>
                    <isActive>false</isActive>
                    <label>Notes</label>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                    <isActive>false</isActive>
                    <label>Tax Lines</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose_Code__c</fullName>
        <label>Purpose Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 - Lender Finance</fullName>
                </value>
                <value>
                    <fullName>31 - Bridge/A and D</fullName>
                </value>
                <value>
                    <fullName>34 - Farmland</fullName>
                </value>
                <value>
                    <fullName>35 - Participation</fullName>
                </value>
                <value>
                    <fullName>36 - Lender Finance Participation</fullName>
                </value>
                <value>
                    <fullName>37 - Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Type__c</fullName>
        <label>2. Term Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Revolving LOC</fullName>
                </value>
                <value>
                    <fullName>Straight LOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoanOpsQstnrTriggerHandler_Test.cls
@isTest
private class LoanOpsQstnrTriggerHandler_Test {
	@testSetup
    static void setup() {
        //set up test records
        Account a = TestDataFactory.createAndInsertTestBusinessAccount();
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        o.RecordTypeId='012i0000001AcDB';
        o.Name = a.Id + ' Opportunity';
        o.StageName = 'On-Hold';
        o.SubStage__c = 'Sponsorship';
        o.CloseDate = System.Date.today();
        o.CI_Projected_Close_Date__c = System.Date.today();
        o.CI_Rate_Type__c = 'Fixed';
        o.CI_Rate__c = 1;
        insert o;
        Loan_Ops_Questionnaire__c loq = new Loan_Ops_Questionnaire__c();
        loq.Opportunity__c = o.Id;
        loq.LOQ_Status__c = 'LOQ In Progress';
        insert loq;
    }
    
    @isTest
    static void testValidateLOQApproval() {
        Loan_Ops_Questionnaire__c loq = [SELECT Id FROM Loan_Ops_Questionnaire__c LIMIT 1][0];
        loq.Collateral_Type__c = 'Real Estate';
        loq.Term_Type__c = 'Term';
        loq.Interest_Rate_Type__c = 'Fixed';
        loq.Borrower_Relationship__c = 'Direct';
        loq.Collateral_Secured__c = 'Secured';
        loq.Property_Type__c = 'SFR';
        loq.Collateral_Type_RE__c = 'Notes';
        loq.Addl_LOQ_Options__c = '3rd Party Agent';
        loq.LOQ_Status__c = 'LOQ Submitted for approval';
        update loq;
        
        loq.ApprovalSubmitted__c = true;
        try {
            update loq;
            System.assert(false, 'LOQ should now allow ApprovalSubmitted field to be set to TRUE if required fields are blank');
        } catch (Exception e) {}
        
        loq.C_I_Loan_Type__c = '1A';
        loq.Call_Report_Code__c = '4';
        loq.Purpose_Code__c = '37 - Direct';
        loq.Collateral_Code_Description__c = '110 - SFR Construction';
        
        update loq;
    }
}