objects/Loan_Ops_Questionnaire__c.object
<CustomObject>
    <description>Loan Ops Questionnaire used by C&amp;I.</description>
    <fields>
        <fullName>Addl_LOQ_Options__c</fullName>
        <label>8. Select all that apply:</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Agent</fullName>
                </value>
                <value>
                    <fullName>Bridge A&amp;D</fullName>
                </value>
                <value>
                    <fullName>Bridge IR Requirement</fullName>
                </value>
                <value>
                    <fullName>Committed loan</fullName>
                </value>
                <value>
                    <fullName>Construction financing</fullName>
                </value>
                <value>
                    <fullName>Fund Control</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Bridge Interest Reverse Requirement</fullName>
                    <isActive>false</isActive>
                    <label>Bridge Interest Reverse Requirement</label>
                </value>
                <value>
                    <fullName>Participation</fullName>
                    <isActive>false</isActive>
                    <label>Participation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Borrower_Relationship__c</fullName>
        <label>4. Borrower to collateral relationship:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Participation</fullName>
                </value>
                <value>
                    <fullName>Lender Participation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>RE Acquisition</fullName>
                    <isActive>false</isActive>
                    <label>RE Acquisition</label>
                </value>
                <value>
                    <fullName>RE Construction</fullName>
                    <isActive>false</isActive>
                    <label>RE Construction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Secured__c</fullName>
        <label>5. Is collateral?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secured</fullName>
                </value>
                <value>
                    <fullName>Unsecured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type_RE__c</fullName>
        <label>7. If RE, collateral type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notes</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                </value>
                <value>
                    <fullName>Recorded Mortgage</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Type__c</fullName>
        <label>1. Collateral Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Business Loans</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Account/Lease Receivable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <label>3. Interest Rate Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adjustable</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOQ_Status__c</fullName>
        <description>Change in field values is controlled by approval process</description>
        <label>LOQ Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LOQ In Progress</fullName>
                    <default>true</default>
                    <label>LOQ In Progress</label>
                </value>
                <value>
                    <fullName>LOQ Submitted for approval</fullName>
                </value>
                <value>
                    <fullName>LOQ Approved</fullName>
                </value>
                <value>
                    <fullName>LOQ Rejected</fullName>
                </value>
                <value>
                    <fullName>LOQ Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>contains</operation>
                <value>C&amp;I, EQF, CRESL, Factoring, NRELF, RELF, IPL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Ops Questionnaires</relationshipLabel>
        <relationshipName>Loan_Ops_Questionnaires</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>6. If RE, property type?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFR</fullName>
                </value>
                <value>
                    <fullName>MF</fullName>
                </value>
                <value>
                    <fullName>CRE</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NPL</fullName>
                    <isActive>false</isActive>
                    <label>NPL</label>
                </value>
                <value>
                    <fullName>Notes</fullName>
                    <isActive>false</isActive>
                    <label>Notes</label>
                </value>
                <value>
                    <fullName>Tax Lines</fullName>
                    <isActive>false</isActive>
                    <label>Tax Lines</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2_24hReminderDate__c</fullName>
        <label>SFDC2 24h Reminder Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Term_Type__c</fullName>
        <label>2. Term Type:</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Revolving LOC</fullName>
                </value>
                <value>
                    <fullName>Straight LOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Ops Questionnaire</label>
    <nameField>
        <displayFormat>LOQ{000000}</displayFormat>
        <label>LOQ ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ops Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>LOQ</fullName>
        <active>true</active>
        <label>LOQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LOQSLA24hRemindersSFDC2_Test.cls
/*******************************************************************************
Developed by: Unosquare
Author: Daniel Peñaloza
Project: BOFI - C&I
Description: Apex Test class for LOQSLARemindersSFDC2

--------- ---------- -------------------------- -----------------------------------
Version   Date       Author                     Change Description
--------- ---------- -------------------------- -----------------------------------
   1.0    29/01/2018 Daniel Peñaloza            Class created
   1.1    06/03/2018 Erik Ramirez               Add the required values for Submitted for approval 
*******************************************************************************/

@isTest
private class LOQSLA24hRemindersSFDC2_Test {

    @testSetup
    static void setup() {
        Map<String, RecordType> mapOpportunityRecordTypes = UtilsSFDC2.getRecordTypesMap('Opportunity', 'DeveloperName');
        Map<String, RecordType> mapAccountRecordTypes = UtilsSFDC2.getRecordTypesMap('Account', 'DeveloperName');
        
        Account acc = new Account(
            RecordTypeId = mapAccountRecordTypes.get('Business_Account_SFDC2').Id,
            Is_Converted__c = true,
            Name = 'TEST ACCOUNT'
        );

        insert acc;

        Opportunity opp = new Opportunity(
            RecordTypeId = mapOpportunityRecordTypes.get('CRESL_SFDC2').Id,
            Name = 'TEST OPP',
            StageName = '1 - New',
            CloseDate = System.today().addDays(10),
            AccountId = acc.Id,
            Loan_Amount__c = 100.55,
            Estimated_Rate_at_Close__c = 5.0,
            C_I_Sub_Stage__c = 'Gathering Information',
            CI_Projected_Initial_Funding__c = 100.55
        );
        insert opp;
        Loan_Ops_Questionnaire__c loq = new Loan_Ops_Questionnaire__c();
        loq.Opportunity__c = opp.id;
        insert loq;
        
                
    }

    @isTest
    static void should_set_loq_reminder_dates() {
        Loan_Ops_Questionnaire__c[] lstLOQs = [
            SELECT Id, SFDC2_24hReminderDate__c
            FROM Loan_Ops_Questionnaire__c limit 1
        ];

        System.assert(!lstLOQs.isEmpty());
        LOQSLA24hRemindersSFDC2.setLOQ24hReminderDate(lstLOQs);
        
/*
        for (Loan_Ops_Questionnaire__c loq: lstLOQs) {
            loq.Collateral_Type__c       = 'Real Estate' ;
            loq.Term_Type__c             = 'Term';
            loq.Interest_Rate_Type__c    = 'Adjustable' ;
            loq.Borrower_Relationship__c = 'Direct' ;
            loq.Property_Type__c         = 'SFR' ;
            loq.Collateral_Secured__c    = 'Secured';
            loq.Addl_LOQ_Options__c      = 'Committed loan';
            loq.Collateral_Type_RE__c    = 'Notes' ;
            loq.LOQ_Status__c            = 'LOQ Submitted for approval';
        }

        // Execute test
        Test.startTest();
            update lstLOQs;
        Test.stopTest();

        // Verify test results
        lstLOQs = [
            SELECT Id, SFDC2_24hReminderDate__c
            FROM Loan_Ops_Questionnaire__c
        ];

        Boolean allValid = true;
        for (Loan_Ops_Questionnaire__c loq: lstLOQs) {
            allValid = (allValid && loq.SFDC2_24hReminderDate__c != null);
        }

        System.assertEquals(true, allValid);
*/   
}


}