objects/MarketoAuthCreds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Creds to get the Marketo&apos;s access token</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <description>Indicates the client ID</description>
        <label>Client Id</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <description>Indicates the client secret</description>
        <label>Client Secret</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrantType__c</fullName>
        <defaultValue>&apos;client_credentials&apos;</defaultValue>
        <description>Indicates the grant type</description>
        <label>Grant Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Marketo Login</label>
</CustomObject>

objects/SimpleWSSetttings__mdt.object
<CustomObject>
    <fields>
        <fullName>EndpointURI__c</fullName>
        <label>Endpoint URI</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>HttpMethod__c</fullName>
        <label>Http Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                    <default>true</default>
                    <label>GET</label>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>PATCH</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeoutInMiliseconds__c</fullName>
        <defaultValue>120000</defaultValue>
        <label>Timeout (miliseconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Simple WS Settting</label>
    <pluralLabel>Simple WS Setttings</pluralLabel>
</CustomObject>

classes/MKTO_AccessTokenRequest_cls.cls
/***

    Author: René Ayala Medina
    Description: Class to request the Marketo access token
    
    Version Developer             Date          Description
    0.1     René Ayala Medina RAM 06/08/2018    Class created
    0.2     René Ayala Medina RAM 06/08/2018    Building the class
    1.0     René Ayala Medina RAM 06/08/2018    Documentation and testing

***/
public class MKTO_AccessTokenRequest_cls {
	
	/*
		Takes custom metadata type instance and custom setting one. After that, perform the callout through other methods.
	*/

	public static AccessTokenRequestProcessedResponse getAccessToken(){
		Boolean blnMetadataAndCSProvided = false;
		AccessTokenRequestProcessedResponse responseWrappInstance = new AccessTokenRequestProcessedResponse();
		SimpleWSSetttings__mdt autWSSettingsIntance = new SimpleWSSetttings__mdt();
		String strQueryOverWSSettingsCMetaSttmnt = 'SELECT '+String.join(new List<String>(SObjectType.SimpleWSSetttings__mdt.Fields.getMap().keySet()),', ')+' FROM SimpleWSSetttings__mdt WHERE DeveloperName = \'MarketoAuthAccessToken\' limit 1';
		autWSSettingsIntance = Database.query(strQueryOverWSSettingsCMetaSttmnt);
		if(autWSSettingsIntance.Id != null){
			MarketoAuthCreds__c mketoKeysCSInstance = MarketoAuthCreds__c.getInstance();
			if(mketoKeysCSInstance.Name != null && String.isNotBlank(mketoKeysCSInstance.Name)){
				blnMetadataAndCSProvided = true;
				HttpResponse httpResponseInstance = performAuthCallout(autWSSettingsIntance,mketoKeysCSInstance);
				if(httpResponseInstance.getStatusCode() == 200 || httpResponseInstance.getStatusCode() == 201 || httpResponseInstance.getStatusCode() == 202){
					AccessTokenResponse accessTokenWrapperInstance = new AccessTokenResponse();
					try{accessTokenWrapperInstance = (AccessTokenResponse) JSON.deserialize(httpResponseInstance.getBody(), AccessTokenResponse.class);}catch(SerializationException serE){}catch(UnexpectedException uE){}catch(Exception gE){}
					Boolean blnAccessTokenWasProvided = false;
					if(accessTokenWrapperInstance.access_token != null){
						if(String.isNotBlank(accessTokenWrapperInstance.access_token)){
							blnAccessTokenWasProvided = true;
							responseWrappInstance.blnSuccessfulResponse = true;
							responseWrappInstance.strAccessToken = accessTokenWrapperInstance.access_token;
						}
					}
				}else{
					responseWrappInstance.strErrorMsg = 'Status code : '+httpResponseInstance.getStatusCode()+' - '+httpResponseInstance.getBody();
				}
			}
		}
		if(!blnMetadataAndCSProvided){
			responseWrappInstance.strErrorMsg = 'Authentication custom metadata type not found';
		}
		return responseWrappInstance;
	}

	/*
		Perform the callout itself
	*/

	public static HttpResponse performAuthCallout(SimpleWSSetttings__mdt wsConsumptionSettingsInstance, MarketoAuthCreds__c mketoKeysCSInstance){
		HttpResponse httpResponseInstance = new HttpResponse();
		Http httpInstance = new Http();
		HttpRequest httpRequestInstance = new HttpRequest();
		String strEndpointProcessedURI = wsConsumptionSettingsInstance.EndpointURI__c+'?grant_type='+mketoKeysCSInstance.GrantType__c+'&client_id='+mketoKeysCSInstance.ClientId__c+'&client_secret='+mketoKeysCSInstance.ClientSecret__c;
		httpRequestInstance.setEndpoint(strEndpointProcessedURI);
		httpRequestInstance.setMethod(wsConsumptionSettingsInstance.HttpMethod__c);
		if(wsConsumptionSettingsInstance.TimeoutInMiliseconds__c != null){
			httpRequestInstance.setTimeout((Integer)wsConsumptionSettingsInstance.TimeoutInMiliseconds__c);
		}
		try{httpResponseInstance = httpInstance.send(httpRequestInstance);}catch(CalloutException cOExc){}catch(UnexpectedException uE){}catch(Exception gE){}
		return httpResponseInstance;
	}

	/*
		Class to wrapper the processed response
	*/	

	public class AccessTokenRequestProcessedResponse{
		public Boolean blnSuccessfulResponse;
		public String strAccessToken;
		public String strErrorMsg;
		public AccessTokenRequestProcessedResponse(){
			blnSuccessfulResponse = false;
			strAccessToken = '';
			strErrorMsg = '';
		}
	}

	/*
		Class to wrapper the raw response
	*/

	public class AccessTokenResponse{
		public String access_token;
		public String token_type;
		public Integer expires_in;
		public String scope;
		public AccessTokenResponse(){
			access_token = '';
			token_type = '';
			expires_in = null;
			scope = '';
		}
	}

}