objects/Opportunity_Queue__c.object
<CustomObject>
    <description>SFDC2: Used by enterprise in conjunction with opportunities to set up a queuing system for Opportunities</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity originally assigned to queue</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Queues</relationshipLabel>
        <relationshipName>Opportunity_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Queue</label>
    <nameField>
        <displayFormat>OQ-{000000000}</displayFormat>
        <label>Opportunity Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulableRecordCleanup.cls
global class SchedulableRecordCleanup implements Schedulable{
    global void execute(SchedulableContext sc){
        String queryOppQueue = 'select id from Opportunity_Queue__c where Opportunity__c = null and LastModifiedDate != LAST_N_DAYS:15';
        if(Test.isRunningTest()) {
        	queryOppQueue = 'select id from Opportunity_Queue__c where Opportunity__c = null';
        }
        BatchableRecordDelete delOppQueue = new BatchableRecordDelete(queryOppQueue);
        Id BatchProcessId = Database.ExecuteBatch(delOppQueue);
    }
}