objects/Opportunity_Queue__c.object
<CustomObject>
    <description>SFDC2: Used by enterprise in conjunction with opportunities to set up a queuing system for Opportunities</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity originally assigned to queue</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Queues</relationshipLabel>
        <relationshipName>Opportunity_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Queue</label>
    <nameField>
        <displayFormat>OQ-{000000000}</displayFormat>
        <label>Opportunity Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TakeOwnership_LGTN_SFDC2_test.cls
@isTest
public class TakeOwnership_LGTN_SFDC2_test {
    static testmethod void changeOwner(){
        
        Account account = TestDataFactory.createAndInsertTestPersonAccount();
        RecordType referToType = [select id from RecordType where SObjectType='Opportunity' and Name='Dealership Recruiting SFDC2'];
        Opportunity opp = new Opportunity(
            Name = 'test',
            StageName = '1-New',
            CloseDate=Date.today(),
            AccountId = account.Id,
            RecordTypeId = referToType.Id);
        insert opp;
        
        Opportunity_Queue__c oppQue = new Opportunity_Queue__c(Opportunity__c = opp.Id);
        insert oppQue;
        TakeOwnership_LGTN_SFDC2.changeOwner(String.valueOf(oppQue.Id));
    }
}