objects/Phone_Number__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phone_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Neustar_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by onclick javascript button which signals to the Phone Number trigger that a manual Phone Attr callout to Neustar has been submitted</description>
        <label>Neustar Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Busy</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
                <value>
                    <fullName>Do Not Call</fullName>
                </value>
                <value>
                    <fullName>Fast Busy</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Ring No Answer</fullName>
                </value>
                <value>
                    <fullName>Spoke to Customer</fullName>
                </value>
                <value>
                    <fullName>VM Confirmed</fullName>
                </value>
                <value>
                    <fullName>VM Full</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>PH-{00}</displayFormat>
        <label>Phone Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Webservice_Callout__c.object
<CustomObject>
    <description>Used to log webservice callouts for custom functionality. Included:
- LexisNexis Account updates for Specialty Finance</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <label>Job ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to capture Phone Number record that triggered Neustar Phone Attr callout</description>
        <label>Phone Number</label>
        <referenceTo>Phone_Number__c</referenceTo>
        <relationshipLabel>Webservice Callouts</relationshipLabel>
        <relationshipName>Webservice_Callouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>KO</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Webservice Callout</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Callout Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PhoneNumberTriggerHandler.cls
/**
* @description <p>Handler class for PhoneNumberTrigger functionality</p>
* @author Mike Crosby, BofI Federal 
*/
public with sharing class PhoneNumberTriggerHandler extends TriggerHandler{
  /** Map of Phone Numbers before changes */
  private Map<Id, Phone_Number__c> oldMap;
  /** Map of Phone Numbers with changes */
  private Map<Id, Phone_Number__c> newMap;
  
  /** Constructor */
  public PhoneNumberTriggerHandler() {
    this.oldMap = (Map<Id, Phone_Number__c>) Trigger.oldMap;
    this.newMap = (Map<Id, Phone_Number__c>) Trigger.newMap;
  }
  
  /**
  * Process beforeUpdate logic
  */
  public override void beforeUpdate() {
    handleManualNeustarTrigger(oldMap, newMap);
  }
    public override void afterInsert() {
        handlesfdc2personaccount(newMap);
    }
  /**
  * Trigger a callout to Neustar to retrieve phone attribute data if Neustar Trigger field is set to true
  */
  private void handleManualNeustarTrigger(Map<Id, Phone_Number__c> oldPhoneMap, Map<Id, Phone_Number__c> newPhoneMap) {
  	for(Phone_Number__c ph : newPhoneMap.values()) {
		if(ph.Neustar_Trigger__c) {
			addSFNeustarJob(ph);
			ph.Neustar_Trigger__c = false;
		}
	}
  }
  
    /* Handle neustar for 2.0 person accounts */
    private void handlesfdc2personaccount (Map<Id, Phone_Number__c> newPhoneMap) {
    Id paRTId = Schema.SObjectType.Phone_Number__c.getRecordTypeInfosByName().get('Person Account SFDC2').getRecordTypeId();
  	for(Phone_Number__c ph : newPhoneMap.values()) {
		if(ph.Neustar_Trigger__c && ph.RecordTypeId == paRTId) {
			addSFNeustarJob(ph);
			ph.Neustar_Trigger__c = false;
		}
	}
  }
    
  /**
  * Creates queueable Neustar job for the phone number
  * @param ph Phone Number record to submit to Neustar API
  */
  private void addSFNeustarJob(Phone_Number__c ph) {
  	ID jobID = System.enqueueJob(new NeustarQueueableJob(ph));
    toInsert.add(new Webservice_Callout__c(Job_ID__c = jobID, 
    										Job_Name__c = 'NeustarQueueableJob',
                                            Account__c = ph.Account_Name__c,
                                            Phone_Number__c = ph.Id,
											Status__c = 'Queued'));
  } 
}