objects/SFDC2AccountResearchRecordType__mdt.object
<CustomObject>
    <description>Record type mappings for Account Research functionality</description>
    <fields>
        <fullName>CurrentRecordType__c</fullName>
        <label>Current Record Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto_Lending_Person_Accounts</fullName>
                    <default>true</default>
                    <label>Auto_Lending_Person_Accounts</label>
                </value>
                <value>
                    <fullName>Business_Account</fullName>
                </value>
                <value>
                    <fullName>Business_Account_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Business_Banking</fullName>
                </value>
                <value>
                    <fullName>Business_Consumer_Person_Account</fullName>
                </value>
                <value>
                    <fullName>Capital_Markets</fullName>
                </value>
                <value>
                    <fullName>CI_Account</fullName>
                </value>
                <value>
                    <fullName>Consumer_Deposits_Person_Accounts</fullName>
                </value>
                <value>
                    <fullName>Consumer_Person_Account_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Consumer_Wholesale</fullName>
                </value>
                <value>
                    <fullName>Dealer_Services</fullName>
                </value>
                <value>
                    <fullName>Dealer_Services_Person_Accounts_Record_Type</fullName>
                </value>
                <value>
                    <fullName>Equipment_Finance_Group</fullName>
                </value>
                <value>
                    <fullName>Factoring_Partner</fullName>
                </value>
                <value>
                    <fullName>Factoring_Prospect</fullName>
                </value>
                <value>
                    <fullName>Financial_Advisor</fullName>
                </value>
                <value>
                    <fullName>Income_Property_Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance_Companies</fullName>
                </value>
                <value>
                    <fullName>IPL_Account</fullName>
                </value>
                <value>
                    <fullName>PersonAccount</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Business_Consumer_PA_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Business_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Consumer_PA_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Assignee</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Courts</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_IGT_Winners</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Law_Firms</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Lottery</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Originator</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_State_Lotteries</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NewRecordType__c</fullName>
        <label>New Record Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto_Lending_Person_Accounts</fullName>
                    <default>true</default>
                    <label>Auto_Lending_Person_Accounts</label>
                </value>
                <value>
                    <fullName>Business_Account</fullName>
                </value>
                <value>
                    <fullName>Business_Account_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Business_Banking</fullName>
                </value>
                <value>
                    <fullName>Business_Consumer_Person_Account</fullName>
                </value>
                <value>
                    <fullName>Capital_Markets</fullName>
                </value>
                <value>
                    <fullName>CI_Account</fullName>
                </value>
                <value>
                    <fullName>Consumer_Deposits_Person_Accounts</fullName>
                </value>
                <value>
                    <fullName>Consumer_Person_Account_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Consumer_Wholesale</fullName>
                </value>
                <value>
                    <fullName>Dealer_Services</fullName>
                </value>
                <value>
                    <fullName>Dealer_Services_Person_Accounts_Record_Type</fullName>
                </value>
                <value>
                    <fullName>Equipment_Finance_Group</fullName>
                </value>
                <value>
                    <fullName>Factoring_Partner</fullName>
                </value>
                <value>
                    <fullName>Factoring_Prospect</fullName>
                </value>
                <value>
                    <fullName>Financial_Advisor</fullName>
                </value>
                <value>
                    <fullName>Income_Property_Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance_Companies</fullName>
                </value>
                <value>
                    <fullName>IPL_Account</fullName>
                </value>
                <value>
                    <fullName>PersonAccount</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Business_Consumer_PA_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Business_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Prospecting_Consumer_PA_SFDC2</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Assignee</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Courts</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_IGT_Winners</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Law_Firms</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Lottery</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_Originator</fullName>
                </value>
                <value>
                    <fullName>Specialty_Finance_State_Lotteries</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>Specify the operation for Account Research</description>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Request/Cancel</fullName>
                    <default>true</default>
                    <label>Request/Cancel</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                    <isActive>false</isActive>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>Request</fullName>
                    <isActive>false</isActive>
                    <label>Request</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelatedObject__c</fullName>
        <label>Related Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>Research Record Type Mappings</relationshipLabel>
        <relationshipName>ResearchRecordTypeMappings_del</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>SFDC2 Account Research Record Type</label>
    <pluralLabel>SFDC2 Account Research Record Types</pluralLabel>
</CustomObject>

objects/SFDC2SLAReminderSettings__mdt.object
<CustomObject>
    <description>Custom metadata to set SLA Reminder times for diferrent Salesforce Objects</description>
    <fields>
        <fullName>BF_Approval_Reminder_Time__c</fullName>
        <description>Boarding Form Reminder Time in Hours (After it is Submited for Approval)</description>
        <inlineHelpText>Boarding Form Reminder Time in Hours (After it is Submited for Approval)</inlineHelpText>
        <label>BF Approval Reminder Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LOQ_Approval_Reminder_Time__c</fullName>
        <description>LOQ Reminder Time in Hours (After it is Submited for Approval)</description>
        <inlineHelpText>LOQ Reminder Time in Hours (After it is Submited for Approval)</inlineHelpText>
        <label>LOQ Approval Reminder Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opp_Proj_Close_Date_Reminder_Time__c</fullName>
        <description>Opportunity Reminder Time in Hours (Before its Projected Close Date)</description>
        <inlineHelpText>Opportunity Reminder Time in Hours (Before its Projected Close Date)</inlineHelpText>
        <label>Opp. Proj. Close Date Reminder Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SFDC2 SLA Reminder Settings</label>
    <pluralLabel>SFDC2 SLA Reminder Settings</pluralLabel>
</CustomObject>

classes/UtilsSFDC2.cls
public class UtilsSFDC2 {

	/**
	 * @param sObjectName Name of the object to get Record type mappings
	 * @return            List of record type mappings
	 */
	public static SFDC2AccountResearchRecordType__mdt[] getResearchRecordTypeMappings(String objectName, String operation) {
		SFDC2AccountResearchRecordType__mdt[] lstRecordTypeMappings = [
			SELECT Id, CurrentRecordType__c, NewRecordType__c
			FROM SFDC2AccountResearchRecordType__mdt
			WHERE Operation__c = :operation
				AND RelatedObject__c = :objectName
				AND IsActive__c = true
		];

		return lstRecordTypeMappings;
	}

	/**
	 * @param sObjectName SObject to get record types
	 * @param keyField    Field to use as key for map
	 * @return            Map of Record types by Key field
	 */
	public static Map<String, RecordType> getRecordTypesMap(String sObjectName, String keyField) {
		Map<String, RecordType> mapRecordTypes = new Map<String, RecordType>();

		RecordType[] lstRecordTypes = [
			SELECT Id, DeveloperName, Name, IsPersonType
			FROM RecordType
			WHERE SObjectType = :sObjectName
		];

		for(RecordType recType: lstRecordTypes) {
			String key = String.valueOf(recType.get(keyField));
			mapRecordTypes.put(key, recType);
		}

		return mapRecordTypes;
	}

	/**
	 * Get SLA Reminder Times for Email notifications
	 */
	public static SFDC2SLAReminderSettings__mdt getSLAReminderTimes() {
		SFDC2SLAReminderSettings__mdt defaultReminderTimes = [
			SELECT Id, BF_Approval_Reminder_Time__c, LOQ_Approval_Reminder_Time__c, Opp_Proj_Close_Date_Reminder_Time__c
			FROM SFDC2SLAReminderSettings__mdt
			WHERE IsActive__c = true
			LIMIT 1
		];

		return defaultReminderTimes;
	}
}