objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Read__c</fullName>
        <label>Customer Read</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDBSecureMessagingTriggerHandler.cls
public class UDBSecureMessagingTriggerHandler extends TriggerHandler {
	private List<UDB_Secure_Messaging__c> newList;

	public UDBSecureMessagingTriggerHandler() {
		this.newList =(List<UDB_Secure_Messaging__c>) Trigger.new;
	}

	public override void afterInsert() {
		handleIsVisibleSelfService();
	}

	private void handleIsVisibleSelfService() {
    List<UDB_Secure_Messaging__c> messageList =  new List<UDB_Secure_Messaging__c>();
    String caseId;
    Case c;
    for(UDB_Secure_Messaging__c setIsVisble : [select Customer_Read__c, Related_To__c from UDB_Secure_Messaging__c where Id =:newList and Customer_Read__c = null]) {
     	caseId = setIsVisble.Related_To__c;
     	System.debug('Case Id is: ' + caseId);
    	 	messageList.add(setIsVisble);
    }
    if(messageList.size() > 0 ) {
     		c = [select Id, IsVisibleSelfService__c from case where Id =: caseId];
     		c.IsVisibleSelfService__c = true;
     		update c;
    }
  }
}