objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Read__c</fullName>
        <label>Customer Read</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDBSecureMessagingTrigerHandler_Test.cls
@isTest
private class UDBSecureMessagingTrigerHandler_Test {
	
	public static UDB_Secure_Messaging__c createTestData() {
    	Case caseTest = new Case(
        Origin = 'UDB',
        Priority = 'Standard',
        Status = 'New',
        UDB_CIF__c = 'xxx111',
        Description = 'Running Test',
        recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('UDB Inquiry').getRecordTypeId());

        insert caseTest;


		UDB_Secure_Messaging__c  sm = new UDB_Secure_Messaging__c(
			Related_To__c = caseTest.Id,
			Assigned_To__c = UserInfo.getUserId(),
			Description__c = 'This is a test',
			Customer_Read__c = null
			);

        return sm;
	}


	@isTest
	static void testHandleIsVisible() {
		UDB_Secure_Messaging__c sm = createTestData();
		System.Test.startTest();
		insert sm;
		System.Test.stopTest();
	}
}