objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Read__c</fullName>
        <label>Customer Read</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDB_User_Update.cls
@RestResource(urlMapping='/UDB_User_Update/*')
global with sharing class UDB_User_Update {
	
	@HttpPost 
	global static string updateData(String caseId) {
		RestRequest req = RestContext.request;
		String msg;

		if(caseId != null || caseId != '') {
			Case c = [select Id, IsVisibleSelfService__c from Case where Id =: caseId];
			List<UDB_Secure_Messaging__c> sm = [select Customer_Read__c from UDB_Secure_Messaging__c where Related_To__r.Id =: caseId and Customer_Read__c = null];
			for(UDB_Secure_Messaging__c msgs : sm) {
				msgs.Customer_Read__c = System.now();
				update msgs;
			}
			c.IsVisibleSelfService__c = false;
			update c;
			
			msg = 'Updated Case Data';
		}
		else {
			msg = 'Invalid Case Id.';
		}
		return msg;
	}
}