objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Read__c</fullName>
        <label>Customer Read</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDB_Add_Task_To_Case.cls
@RestResource(urlMapping='/UDB_Add_Task_To_Case/*')
global with sharing class UDB_Add_Task_To_Case {
	
	@HttpPost
	global static String insertMessage() {
		RestRequest req = RestContext.request;
		String caseId = req.params.get('id');
		String messageSubject = req.params.get('tSubject');
		List<UDB_Secure_Messaging__c> messageList = new List<UDB_Secure_Messaging__c>();
		String msg;
		Case c;
		UDB_Secure_Messaging__c sm = new UDB_Secure_Messaging__c();

		if(caseId != null || caseId != '') {


			c = [select Id, caseNumber from Case where Id =:caseId];
			
			sm.Related_To__c = c.Id;
			sm.Description__c = messageSubject;
			sm.Customer_Read__c = System.now();
			sm.ActivityDate__c = System.today();
			insert sm;

			for(UDB_Secure_Messaging__c notRead : [select Id, Customer_Read__c from UDB_Secure_Messaging__c where Related_To__r.Id =: c.Id and Customer_Read__c = null]) {
				messageList.add(notRead);
			}
			if(messageList.size() > 0) {
				c.IsVisibleSelfService__c = true;
				update c;
			}

			msg = 'USDB Secure Message was created Message comments:' + sm.Description__c;
			return msg;
		}
		else { 
			msg = 'Error while adding messages, please review the Case Id';
			return msg;
		}
	}
}