objects/UDB_Secure_Messaging__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>UDB Secure Messagings</relationshipLabel>
        <relationshipName>UDB_Secure_Messagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UDB Secure Messaging</label>
    <nameField>
        <displayFormat>SecureMessage-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDB Secure Messagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UDB_User_Update_Test.cls
@isTest
private class UDB_User_Update_Test {
	static String createTestRecords() {
    	Case caseTest = new Case(
     		Origin = 'UDB',
     		Priority = 'Standard',
     		Status = 'New',
     		Description = 'Running Test',
     		IsVisibleSelfService__c = false,
            recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('UDB Inquiry').getRecordTypeId());

    	insert caseTest;
    	UDB_Secure_Messaging__c taskTest = new UDB_Secure_Messaging__c(
    		Related_To__c = caseTest.Id,
    		Description__c = 'This is a test',
    		ActivityDate__c = System.Today(),
            Assigned_To__c = UserInfo.getUserId()
    		);

        return caseTest.Id;
    }

    @isTest 
    static void testUserUpdate() {
    	String caseId = createTestRecords();
    	
    	String testUpdate = UDB_User_Update.updateData(caseId);
    }
}