objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Contact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hedging_Reports__c</fullName>
        <label>Hedging Reports</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Analyst Email</fullName>
                </value>
                <value>
                    <fullName>Analyst Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QLR_Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - (AC/ARC/QLR) Creation</fullName>
                    <default>true</default>
                    <label>1 - (AC/ARC/QLR) Creation</label>
                </value>
                <value>
                    <fullName>2 - Documents Received and Complete</fullName>
                </value>
                <value>
                    <fullName>3 - Moody&apos;s Entry</fullName>
                </value>
                <value>
                    <fullName>4 - Analysis (AC/ARC/QLR) Complete</fullName>
                </value>
                <value>
                    <fullName>5 - Analysis (AC/ARC/QLR) Internally Audited</fullName>
                </value>
                <value>
                    <fullName>6 - Signature Submitted (Approved)</fullName>
                </value>
                <value>
                    <fullName>7 - Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CertificationTriggerHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CertificationTriggerHandler_Test {

  /**
  * Tests the handleStatusHistoryCreation trigger functionality
  */
  @isTest
  static void testHandleStatusHistoryCreation() {
    Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
    WLD_Certification__c cert = TestDataFactory.createTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
    cert.Status__c = 'Test1';
    
    System.test.startTest();
    insert cert;
    cert.Status__c = 'Test2';
    update cert;
    System.test.stopTest();
  }
    
  /**
  * Tests the populateContactEmailFields method that is triggered in the afterUpdate for Accounts
  */
  @isTest
  static void testPopulateContactEmailFields() {
  	//Create test Account for WLD
  	String wldRTId = '012i0000001QAvX';  	
  	Account a = TestDataFactory.createTestBusinessAccount();
  	a.Contact_Email__c = 'test@test.com';
  	a.Contact_Email_2__c = 'test2@test.com';
  	a.RecordTypeId = wldRTId;
  	insert a;
  	
  	//create a test Certification record for the Account
  	Test.startTest();
  	WLD_Certification__c cert = new WLD_Certification__c(Account__c=a.Id,QLR_Year__c=String.valueOf(Date.today().year()),Name='Test');
  	insert cert;
  	Test.stopTest();
  	
  	for(WLD_Certification__c c : [SELECT Contact_Email__c, Contact_Email_2__c FROM WLD_Certification__c WHERE Account__c = :a.Id]) {
  		System.assertEquals('test@test.com', c.Contact_Email__c);
  		System.assertEquals('test2@test.com', c.Contact_Email_2__c);
  	}
  }
  
  /**
  * Tests the processAnalystCallUpdate method that is triggered in the afterinsert, afterUpdate for Certifications
  */
  @isTest
  static void testProcessAnalystCallUpdate() {
  	//Create test Account for WLD
  	String wldRTId = '012i0000001QAvX';  	
  	Account a = TestDataFactory.createTestBusinessAccount();
  	a.Contact_Email__c = 'test@test.com';
  	a.RecordTypeId = wldRTId;
  	insert a;
  	
  	//create a test Certification record for the Account
  	Test.startTest();
  	WLD_Certification__c cert1 = new WLD_Certification__c(Account__c=a.Id,QLR_Year__c=String.valueOf(Date.today().year()),Name='Test', Hedging_Reports__c='Requested');
  	WLD_Certification__c cert2 = new WLD_Certification__c(Account__c=a.Id,QLR_Year__c=String.valueOf(Date.today().year()),Name='Test', Hedging_Reports__c='Analyst Call');
  	WLD_Certification__c[] certs = new List<WLD_Certification__c>{cert1,cert2}; 
  	insert certs;
  	cert2 = certs.get(0);
  	cert2.Hedging_Reports__c = 'Analyst Call';
  	update cert2;
  	Test.stopTest();
  	
  }
}