objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QLR_Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QTR1</fullName>
                </value>
                <value>
                    <fullName>QTR2</fullName>
                </value>
                <value>
                    <fullName>QTR3</fullName>
                </value>
                <value>
                    <fullName>QTR4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QLR_Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <recordTypes>
        <fullName>Account_Certification</fullName>
        <active>true</active>
        <description>Used during the initial certification process</description>
        <label>Account Certification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Recertification</fullName>
        <active>true</active>
        <description>Used annually for recertification</description>
        <label>Account Recertification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quarterly_Certification</fullName>
        <active>true</active>
        <description>Used quarterly</description>
        <label>Quarterly Certification</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountCertificationDisplayExt_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AccountCertificationDisplayExt_Test {

	/**
	* Tests the AccountCertificationDisplayExtension class
	*/
	@isTest
    static void testAccountCertificationDisplayExtension() {
        //create test account
        Account a = TestDataFactory.createAndInsertTestBusinessAccount();
        List<RecordType> recordTypes = [
        								SELECT DeveloperName
        								FROM RecordType
        								WHERE SobjectType = 'WLD_Certification__c'
        								];
        System.assert(recordTypes.size() > 0, 'No record types defined for Certification object');
        
        //test with no Account defined
        AccountCertificationDisplayExtension ext = new AccountCertificationDisplayExtension(new ApexPages.StandardController(new Account()));
        
        //set up with test Account record
        ApexPages.currentPage().getParameters().put('id',a.Id);
        ApexPages.Standardcontroller ctr = new ApexPages.StandardController(a);
        ext = new AccountCertificationDisplayExtension(ctr);
        
        System.assertEquals(0, ext.AccountCertifications.size(), 'Account should not have any Account Certifications');
        System.assertEquals(0, ext.QuarterlyCertifications.size(), 'Account should not have any Quarterly Certifications');
        System.assertEquals(false, ext.shouldRedirect);
        PageReference ref = ext.newAccountCertification();
        System.assertEquals(null, ref);
        System.assert(ext.shouldRedirect);
        Boolean hasRt = false;
        for(RecordType rt : recordTypes) {
        	if(rt.DeveloperName == 'Account_Certification') {
        		System.assert(ext.redirectURL.contains(rt.Id), 'Issue retrieving initial Account Certification url');
        		hasRt = true;
        		break;
        	}
        }
        if(!hasRt) {
        	System.assert(false, 'Account_Certification record type not found');
        }
        ref = ext.newQuarterlyCertification();
        System.assertEquals(null, ref);
        hasRt = false;
        for(RecordType rt : recordTypes) {
        	if(rt.DeveloperName == 'Quarterly_Certification') {
        		System.assert(ext.redirectURL.contains(rt.Id), 'Issue retrieving Quarterly Certification url');
        		hasRt = true;
        		break;
        	}
        }
        if(!hasRt) {
        	System.assert(false, 'Quarterly_Certification record type not found');
        }
        
        List<WLD_Certification__c> certs = new List<WLD_Certification__c>();
        Id acRt;
        Id qcRt;
        for(RecordType rt : recordTypes) {
        	if(rt.DeveloperName == 'Account_Certification') {
        		acRt = rt.Id;
        	} else if (rt.DeveloperName == 'Quarterly_Certification') {
        		qcRt = rt.Id;
        	}
        }
        WLD_Certification__c ac = new WLD_Certification__c(Name='Test',Account__c=a.Id,QLR_Year__c=String.valueOf(Date.today().year()), RecordTypeId=acRt);
        WLD_Certification__c qc = new WLD_Certification__c(Name='Test',Account__c=a.Id,QLR_Year__c=String.valueOf(Date.today().year()), RecordTypeId=qcRt, QLR_Quarter__c='QTR 1');
        certs.add(ac);
        certs.add(qc);
        insert certs;
        
        ext = new AccountCertificationDisplayExtension(ctr);
        System.assertEquals(1, ext.AccountCertifications.size(), 'Account should have 1 Account Certification');
        System.assertEquals(1, ext.QuarterlyCertifications.size(), 'Account should have 1 Quarterly Certification');
        ref = ext.newAccountCertification();
        hasRt = false;
        for(RecordType rt : recordTypes) {
        	if(rt.DeveloperName == 'Account_Recertification') {
        		System.assert(ext.redirectURL.contains(rt.Id), 'Issue retrieving Account Recertification url');
        		hasRt = true;
        		break;
        	}
        }
        if(!hasRt) {
        	System.assert(false, 'Account_Recertification record type not found');
        }
    }
}