objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WLD_Status_History__c.object
<CustomObject>
    <description>Tracks status changes for Certifications and Credit Reviews</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>WLD_Certification__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>Status_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Review</label>
        <referenceTo>WLD_Credit_Review__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>Status_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date/time status changed</description>
        <label>Status Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_in_Status_days__c</fullName>
        <formula>IF(
  ISBLANK(Next_Status__c),
    /* Current Status */
    /*days*/ 
    FLOOR( NOW() - Status_Date_Time__c ) + 1,
    /* Diff between this status and next status */
    FLOOR( Next_Status__r.Status_Date_Time__c - Status_Date_Time__c) + 1
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time in Status (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Status History</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StatusHistoryDisplayExtension.cls
public with sharing class StatusHistoryDisplayExtension {
	/** Current record */
	private Sobject obj;
	
	/** Constructor */
	public StatusHistoryDisplayExtension(ApexPages.StandardController ctr) {
		obj = ctr.getRecord();
	}
	
	/**
	* Retrieves the Status History records for the current record
	*/
	public List<WLD_Status_History__c> getStatusHistory() {
		//dynamically determine record type
		String objectAPIName = (obj.id).getSObjectType().getDescribe().getName();
		return Database.query('SELECT Name, Status_Date_Time__c, Time_in_Status_days__c ' +
								'FROM WLD_Status_History__c ' +
								'WHERE ' + 
								((objectAPIName == 'WLD_Certification__c') ? 'Certification__c' : 'Credit_Review__c') +
								' = \'' + obj.Id + '\' ' +
								'ORDER BY Status_Date_Time__c DESC, ID DESC');
								
	}
}