objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <fields>
        <fullName>Credit_Review_Status__c</fullName>
        <description>Auto-populate with credit review status upon user entry in that object&apos;s status field</description>
        <label>Credit Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>On Hold - Resubmission Request</fullName>
                </value>
                <value>
                    <fullName>Submitted for Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Obligor_Score__c</fullName>
        <label>Obligor Score</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk_Rating__c</fullName>
        <label>Risk Rating</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - (AC/ARC/QLR) Creation</fullName>
                    <default>true</default>
                    <label>1 - (AC/ARC/QLR) Creation</label>
                </value>
                <value>
                    <fullName>2 - Documents Received and Complete</fullName>
                </value>
                <value>
                    <fullName>3 - Moody&apos;s Entry</fullName>
                </value>
                <value>
                    <fullName>4 - Analysis (AC/ARC/QLR) Complete</fullName>
                </value>
                <value>
                    <fullName>5 - Analysis (AC/ARC/QLR) Internally Audited</fullName>
                </value>
                <value>
                    <fullName>6 - Signature Submitted (Approved)</fullName>
                </value>
                <value>
                    <fullName>7 - Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WLD_Credit_Review__c.object
<CustomObject>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification</label>
        <referenceTo>WLD_Certification__c</referenceTo>
        <relationshipLabel>Credit Reviews</relationshipLabel>
        <relationshipName>Credit_Reviews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Document Approval</fullName>
                    <default>true</default>
                    <label>Pending Document Approval</label>
                </value>
                <value>
                    <fullName>Complete Package Received</fullName>
                </value>
                <value>
                    <fullName>Moody&apos;s Spreading</fullName>
                </value>
                <value>
                    <fullName>QLR Prep</fullName>
                </value>
                <value>
                    <fullName>Management Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Obligor_Score__c</fullName>
        <label>Obligor Score</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk_Rating__c</fullName>
        <label>Risk Rating</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriggerApprovedProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by the approval process upon approval and used in Credit Review trigger after update to set the associated Certification record Status to Completed</description>
        <label>TriggerApprovedProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TriggerDeniedProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by the approval process upon rejection and used in Credit Review trigger after update to set the associated Certification record Status to Denied</description>
        <label>TriggerDeniedProcess</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Review</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WLD_Status_History__c.object
<CustomObject>
    <description>Tracks status changes for Certifications and Credit Reviews</description>
    <fields>
        <fullName>Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification</label>
        <referenceTo>WLD_Certification__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>Status_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Review</label>
        <referenceTo>WLD_Credit_Review__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>Status_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Status</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Linked statuses must belong to the same Certification/Credit Review record</errorMessage>
            <filterItems>
                <field>$Source.Certification__c</field>
                <operation>equals</operation>
                <valueField>WLD_Status_History__c.Certification__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Credit_Review__c</field>
                <operation>equals</operation>
                <valueField>WLD_Status_History__c.Credit_Review__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WLD_Status_History__c</referenceTo>
        <relationshipLabel>Status History (Next Status)</relationshipLabel>
        <relationshipName>Status_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Status History</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreditReviewTriggerHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CreditReviewTriggerHandler_Test {

    /**
    * Tests the handleCreditReviewApproved trigger functionality
    */
    @isTest
    static void testHandleCreditReviewApproved() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
        WLD_Certification__c cert = TestDataFactory.createAndInsertTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
        WLD_Credit_Review__c cred = TestDataFactory.createTestCreditReview(cert);
        cred.Credit_Status__c = 'QLR Prep';
        insert cred;
        
        System.test.startTest();
        cred.TriggerApprovedProcess__c = true;
        update cred;
        System.test.stopTest();
        
        cred = [
                SELECT TriggerApprovedProcess__c, Certification__r.Status__c 
                FROM WLD_Credit_Review__c 
                WHERE Id = :cred.Id];
        System.assertEquals(false, cred.TriggerApprovedProcess__c, 'TriggerApprovedProcess did not reset');
        System.assertEquals('Completed', cred.Certification__r.Status__c, 'Certification Status did not update');
    }
    
    /**
    * Tests the handleCertFieldUpdates trigger functionality
    */
    @isTest
    static void testHandleCertFieldUpdates() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
        WLD_Certification__c cert = TestDataFactory.createAndInsertTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
        WLD_Credit_Review__c cred = TestDataFactory.createTestCreditReview(cert);
        cred.Obligor_Score__c = 1;
        cred.Risk_Rating__c = 2;
        cred.Credit_Status__c = 'Test1';
        insert cred;
        
        cert = [
                SELECT Obligor_Score__c, Risk_Rating__c, Credit_Review_Status__c 
                FROM WLD_Certification__c
                WHERE Id = :cert.Id];
        System.assertEquals(1, cert.Obligor_Score__c, 'Obligor Score was not updated on Credit Review insert');
        System.assertEquals(2, cert.Risk_Rating__c, 'Risk Rating was not updated on Credit Review insert');
        System.assertEquals('Test1', cert.Credit_Review_Status__c, 'Credit Review Status was not updated on Credit Review insert');
        
        cred.Obligor_Score__c = 3;
        cred.Risk_Rating__c = 4;
        cred.Credit_Status__c = 'Test2';
        update cred;
        
        cert = [
                SELECT Obligor_Score__c, Risk_Rating__c, Credit_Review_Status__c
                FROM WLD_Certification__c
                WHERE Id = :cert.Id];
        System.assertEquals(3, cert.Obligor_Score__c, 'Obligor Score was not updated on Credit Review update');
        System.assertEquals(4, cert.Risk_Rating__c, 'Risk Rating was not updated on Credit Review update');
        System.assertEquals('Test2', cert.Credit_Review_Status__c, 'Credit Review Status was not updated on Credit Review update');
    }
    
    /**
    * Tests the handleCreditReviewUniquenessForCert trigger functionality
    */
    @isTest
    static void testHandleCreditReviewUniquenessForCert() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
        WLD_Certification__c cert = TestDataFactory.createAndInsertTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
        WLD_Credit_Review__c cred = TestDataFactory.createTestCreditReview(cert);
        cred.Credit_Status__c = 'QLR Prep';
        insert cred;
        
        System.test.startTest();
        WLD_Credit_Review__c[] credArray = new List<WLD_Credit_Review__c>{TestDataFactory.createTestCreditReview(cert),TestDataFactory.createTestCreditReview(cert)};
        try {
            insert credArray;
            System.assert(false, 'Should not be able to create more than one Credit Review for a Certification');
        } catch (Dmlexception e) {}
        System.test.stopTest();
    }
    
    /**
    * Tests the handleStatusHistoryCreation trigger functionality
    */
    @isTest
    static void testHandleStatusHistoryCreation() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
        WLD_Certification__c cert = TestDataFactory.createAndInsertTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
        WLD_Credit_Review__c cred = TestDataFactory.createTestCreditReview(cert);
        cred.Credit_Status__c = 'Test1';
        
        System.test.startTest();
        insert cred;
        cred.Credit_Status__c = 'Test2';
        update cred;
        System.test.stopTest();
        
        cred = [
                SELECT Id, 
                    (SELECT 
                        Name, Credit_Review__c, Next_Status__c
                     FROM Status_History__r) 
                FROM WLD_Credit_Review__c WHERE Id = :cred.Id];
        System.assertEquals(2, cred.Status_History__r.size(), 'Did not create appropriate number of Status History records');
        Id linkedStatus;      
        Id latestStatus;
        
        for(WLD_Status_History__c sh : cred.Status_History__r) {
            if(sh.Next_Status__c == null) {
                //last status should be Test2
                latestStatus = sh.Id;
                System.assertEquals('Test2', sh.Name, 'Last status was not created properly');
            } else {
                //first status should be Test1
                linkedStatus = sh.Next_Status__c;
                System.assertEquals('Test1', sh.Name, 'Second status was not created properly');
            }
        }
        System.assertEquals(latestStatus, linkedStatus, 'First Status not linked properly');
    }
    
    /**
    * Tests the handleCreditReviewDenied trigger functionality
    */
    /*@isTest
    static void testHandleCreditReviewDenied() {
        Account acct = TestDataFactory.createAndInsertTestBusinessAccount();
        WLD_Certification__c cert = TestDataFactory.createAndInsertTestCertification(acct, TestDataFactory.CertificationType.ACCOUNT);
        WLD_Credit_Review__c cred = TestDataFactory.createTestCreditReview(cert);
        cred.Credit_Status__c = 'QLR Prep';
        insert cred;
        
        System.test.startTest();
        cred.TriggerDeniedProcess__c = true;
        update cred;
        System.test.stopTest();
        
        cred = [
                SELECT TriggerDeniedProcess__c, Certification__r.Status__c 
                FROM WLD_Credit_Review__c 
                WHERE Id = :cred.Id];
        System.assertEquals(false, cred.TriggerDeniedProcess__c, 'TriggerDeniedProcess did not reset');
        System.assertEquals('Denied', cred.Certification__r.Status__c, 'Certification Status did not update');
    }*/
}