objects/WLD_Certification__c.object
<CustomObject>
    <description>Used by WLD for Account Certifications, Recertifications, and Quarterly Certifications</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QLR_Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QTR1</fullName>
                </value>
                <value>
                    <fullName>QTR2</fullName>
                </value>
                <value>
                    <fullName>QTR3</fullName>
                </value>
                <value>
                    <fullName>QTR4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QLR_Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - (AC/ARC/QLR) Creation</fullName>
                    <default>true</default>
                    <label>1 - (AC/ARC/QLR) Creation</label>
                </value>
                <value>
                    <fullName>2 - Documents Received and Complete</fullName>
                </value>
                <value>
                    <fullName>3 - Moody&apos;s Entry</fullName>
                </value>
                <value>
                    <fullName>4 - Analysis (AC/ARC/QLR) Complete</fullName>
                </value>
                <value>
                    <fullName>5 - Analysis (AC/ARC/QLR) Internally Audited</fullName>
                </value>
                <value>
                    <fullName>6 - Signature Submitted (Approved)</fullName>
                </value>
                <value>
                    <fullName>7 - Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <recordTypes>
        <fullName>Account_Certification</fullName>
        <active>true</active>
        <description>Used during the initial certification process</description>
        <label>Account Certification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Recertification</fullName>
        <active>true</active>
        <description>Used annually for recertification</description>
        <label>Account Recertification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quarterly_Certification</fullName>
        <active>true</active>
        <description>Used quarterly</description>
        <label>Quarterly Certification</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountCertificationDisplayExtension.cls
public with sharing class AccountCertificationDisplayExtension {
    /** Current account record */
    private Account acct;
    public List<WLD_Certification__c> AccountCertifications {public get; private set;}
    public List<WLD_Certification__c> QuarterlyCertifications {public get; private set;}
    public String redirectURL {public get; private set;}
    public Boolean shouldRedirect {public get; private set;}
    
    /** Constructor */
    public AccountCertificationDisplayExtension(ApexPages.StandardController ctr) {
        shouldRedirect = false;
        acct = (Account)ctr.getRecord();
        if(acct.Id != null) {
            acct = [SELECT Name FROM Account WHERE Id = :acct.Id];
            getCertifications();
        }
    }
    
    /**
    * Retrieves Account Certifications, Recertifications, Quarterly Certifications
    * for the given account and stores in the appropriate lists
    */
    private void getCertifications() {
        AccountCertifications = new List<WLD_Certification__c>();
        QuarterlyCertifications = new List<WLD_Certification__c>();
        
        for(WLD_Certification__c cert : [
                        SELECT 
                            Name, Status__c, Due_Date__c, RecordType.DeveloperName
                        FROM
                            WLD_Certification__c
                        WHERE
                            Account__c = :acct.Id AND
                            RecordType.DeveloperName in (
                                                            'Account_Certification',
                                                            'Account_Recertification',
                                                            'Quarterly_Certification')
                        ORDER BY
                            QLR_Year__c DESC, QLR_Quarter__c DESC
                        ]) {
            if(
                cert.RecordType.DeveloperName == 'Account_Certification' ||
                cert.RecordType.DeveloperName == 'Account_Recertification') {
                AccountCertifications.add(cert);    
            } else if(cert.RecordType.DeveloperName == 'Quarterly_Certification') {
                QuarterlyCertifications.add(cert);
            }
        }
    }
    
    public PageReference newAccountCertification() {
        return newCertification('ac');
    }
    
    public PageReference newQuarterlyCertification() {
        return newCertification('qc');
    }
    
    /**
    * Redirects user to appropriate Certification form: for Account Certifications,
    * if no Certifications exist, 
    * it will return the url for the Account Certification record type, otherwise,
    * it will return the url for the Account Recertification record type; for 
    * Quarterly Certications, it will just launch the QC record type
    * @return null if no account defined; otherwise a formatted url for certification creation
    */
    public PageReference newCertification(String certType) {
        shouldRedirect = true;
        PageReference ref;
        
        if(acct.Id != null) {
            //dynamically determine prefix for Certification object
            Schema.DescribeSObjectResult r = WLD_Certification__c.sObjectType.getDescribe();
            String keyPrefix = r.getKeyPrefix();
            List<RecordType> rtList = [
                                        SELECT
                                            DeveloperName
                                        FROM
                                            RecordType
                                        WHERE
                                            SobjectType = 'WLD_Certification__c'
                                        ];
            
            RecordType certRecordType;
            for(RecordType rt : rtList) {
                if(
                    (certType == 'ac' &&
                        (
                            (AccountCertifications.size() == 0 && rt.DeveloperName == 'Account_Certification') ||
                            (AccountCertifications.size() > 0 && rt.DeveloperName == 'Account_Recertification')
                        )
                    ) ||
                    (certType == 'qc' && 
                        rt.DeveloperName == 'Quarterly_Certification'
                    )
                    
                ) {
                    certRecordType = rt;
                    break;
                }
            }
            if(certRecordType != null) {
                ref = new PageReference('/' + keyPrefix + '/e');
                ref.getParameters().put('retURL', '/' + acct.Id);
                ref.getParameters().put('RecordType',certRecordType.Id);
                ref.getParameters().put('ent','WLD_Certification__c');
                String nameSuffix = '';
                if(certRecordType.DeveloperName == 'Account_Certification') {
                    nameSuffix = ' AC';
                } else if (certRecordType.DeveloperName == 'Account_Recertification') {
                    nameSuffix = ' ARC';
                }
                ref.getParameters().put('Name',acct.Name + nameSuffix);
                ref.getParameters().put('CF00Ni000000FvDjU_lkid', acct.Id);
                ref.getParameters().put('CF00Ni000000FvDjU', acct.Name);
            }
        }
        redirectUrl = ref.getUrl();
        return null;
    }
}